### ISSUE TITLE
Docstring for ExponentialWeatherer

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1010]
I was looking of the documentation for the ExponentialWeatherer on readthedocs and noticed a few possible errors in the equation. I also mentioned this to @gregtucker. As it is right now, the equation reads:

<a href="https://www.codecogs.com/eqnedit.php?latex=\dot{w}&space;=&space;w_0&space;\exp(d/w^*)" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\dot{w}&space;=&space;w_0&space;\exp(d/w^*)" title="\dot{w} = w_0 \exp(d/w^*)" /></a>

The sign on the argument of the exponential should be negative, and some of the other notation seems unclear to me. There's a dot on the weathering rate, but not on the constant w0, and w is also used for the characteristic depth. Can I suggest something more like this? 

<a href="https://www.codecogs.com/eqnedit.php?latex=w&space;=&space;w_0&space;\exp(-d/d^*)" target="_blank"><img src="https://latex.codecogs.com/svg.latex?w&space;=&space;w_0&space;\exp(-d/d^*)" title="w = w_0 \exp(-d/d^*)" /></a>

**Comment by kbarnhart** [comment]
@DavidLitwin thanks for making this comment. Best thing to do would be to make a pull request proposing these changes! Start by making a brach off of the `master` branch. Let me know if you have any questions.
