### ISSUE TITLE
BC/BAD_INDEX flags

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1018]
@mcflugen cleaned up some usage of bc flags in #997. Namely, rather than using `CLOSED_NODE` the new usage would be `grid.BC_NODE_IS_CLOSED`

Why is this better than importing `CLOSED_NODE` from Landlab... I'm not 100% sure, but my suspicion is that keeping the BC flags bound means that there is less of a chance that they get messed up. 

@mcflugen this brings up some questions:
1. I think we need to put `BAD_INDEX_VALUE` as a grid attribute. 
2. We have lots and lots of examples (in docstrings, code, and test) where the unbound variables are used. I find this confusing. I think we should either decide that 
    a. Its OK to do things two ways
    b. Fix things to make them consistent. 

What do you think?

**Comment by mcflugen** [comment]
@kbarnhart Yes, `BAD_INDEX_VALUE` could be a grid attribute. Or how about a `Graph` attribute? I think it's usually used in the graph topology data structures, is that right?

There may be times when it makes more sense to import the boundary condition codes directly but, apart from those cases, I guess we should be consistent. Although, having two ways of doing things in this case doesn't seem too bad. I'm happy to go through and make those changes.

**Comment by kbarnhart** [comment]
@mcflugen many of these changes are in docstrings, so I've started to make them over on the docs branch (#1003). I'll push my (in progress changes there shortly, then perhaps you can help finish them... (and fix the nagging error about `@classproperty`)

**Comment by mcflugen** [comment]
@kbarnhart thanks!

I'll have a look at the `@classproperty` error. Just to make sure, this is only a problem in the docs, correct?

Since we're on the topic of having multiple ways of doing the same thing, do you have thoughts about the following (I do!),
```python
grid.add_field("topographic__elevation", at="node")
```
vs.
```python
grid.add_field("node", "topographic__elevation")
```
and
```python
>>> grid.at_node["topographic__elevation"]
```
vs.
```python
>>> grid["node"]["topographic__elevation"]
```
We use both quite a lot in landlab and the tutorials.

**Comment by kbarnhart** [comment]
@mcflugen `@classproperty` results in a warning (and I've now made all warnings errors with a -W flag) in the docs. In the docs it [looks like this](https://landlab.readthedocs.io/en/barnhark-bring_wiki_to_docs/reference/core/index.html#landlab.core.model_component.Component.name)... it looks to me like it is documenting `@classmethod` instead of `Component.name`. 

To the best of my ability to tell, I think that is the only problem with that particular attribute (though whether some of the other things in `Component` that are doubly decorated will show this same error (they show no docstrings at the moment)...

**Comment by kbarnhart** [comment]
I favor 
```python
grid.add_field("topographic__elevation", at="node")
```
over 
```python
grid.add_field("node", "topographic__elevation")
```

And I favor 
```python
>>> grid.at_node["topographic__elevation"]
```
over 
```python
>>> grid["node"]["topographic__elevation"]
```

But I don't know that I favor one of them so much more that I'd want to make sure they are all the same in the docstrings...

**Comment by kbarnhart** [comment]
I think opening an issue and putting it on the Friday call docket would make the most sense.

**Comment by kbarnhart** [comment]
A checklist for the BC's (taken out of #1003 and to be placed in the PR addressing this issue eventually)

- [ ] Real docstrings for the BC flags AND references to them throughout. 
- [ ] No more use of unbound BC flags (in docs, in code, in tests)
    - [ ] BAD_INDEX_VALUE
    - [ ] FIXED_VALUE_BOUNDARY
    - [ ] FIXED_GRADIENT_BOUNDARY
    - [ ] LOOPED_BOUNDARY
    - [ ] CLOSED_BOUNDARY
    - [ ] ACTIVE_LINK
    - [ ] FIXED_LINK
    - [ ] INACTIVE_LINK

**Comment by gregtucker** [comment]
On grid vs graph property, I favor grid simply because it is less cognitive load on users. If graph is a backend support of grid, then they shouldn't need to know about it in order to do their science, but they clearly do need to know about grid.

**Comment by gregtucker** [comment]
Also, FWIW, I worry that

>>> grid.add_field("node", "topographic__elevation")

is so deeply entrenched that it would be painful to change (even though I see the logic of the alternative pattern). If we decide to make the change, it would be good to be backward-compatible with the above, even if we have to give a deprecation warning.

**Comment by kbarnhart** [comment]
@mcflugen @gregtucker I think that it makes sense to change all examples in the docstrings AND the tutorials to use 
```python
grid.add_field("topographic__elevation", at="node")
```
instead of 
```python
grid.add_field("node", "topographic__elevation")
```
BUT to leave the code so that the first option is still supported. 

@mcflugen can you do the add_field, add_zeros, add_ones task?
I will finish the BC code task?

**Comment by mcflugen** [comment]
@kbarnhart Yes, I will finish the *add_field*, *add_zeros*, etc. task. I totally agree with changing everything but keeping the old way.

I can finish the *BC* code task. I have a branch, which is just about ready for a pull request, that fixes the node and link flags in the main repo. It's pretty much done.

**Comment by kbarnhart** [comment]
Spiffy. Does that mean you've done everything except for BAD_INDEX_VALUE... I say, b/c I just dealt with that one on this branch: https://github.com/landlab/landlab/tree/barnhark/bc_flags

**Comment by mcflugen** [comment]
@kbarnhart Yes, everything except for *BAD_INDEX_VALUE*. I'll have a look at your branch and cherry-pick as necessary.

I've fixed all of the `add_*` methods in the tutorials. I'll get a pull request ready shortly.

**Comment by gregtucker** [comment]
I'm fine with @kbarnhart's suggested change above, as long as we preserve the ability to use the older syntax.

**Comment by kbarnhart** [comment]
This got changed. Closing
