### ISSUE TITLE
Multiple ways to create and set fields

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#1021]
Currently in *landlab* there are multiple ways to create and access fields. I think it would be good if we could reduce this to just one way. Having multiple ways of doing things might be confusing to users and is more complicated for us to maintain and test.

For creating fields, we can do one of the following,
```python
>>> grid.add_field("topographic__elevation", at="node")
>>> grid.add_field("node", "topographic__elevation")
```
For getting fields, we can do one of the following,
```python
>>> grid.at_node["topographic__elevation"]
>>> grid["node"]["topographic__elevation"]
```
For both cases, I think we should first pick a favorite, and then we have some options (and this is just for *landlab* 2, not for *landlab* 1):
1. enforce our favorite by removing backward compatibility
2. recommend users use our favorite but maintain backward compatibility (and add a deprecation warning)
3. keep things as-is

**Comment by kbarnhart** [comment]
This got settled. Closing.
