### ISSUE TITLE
Getting *did not find HDF5 header* error when installing on Windows

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#1030]
It seems that the newest version of *netcdf4* (*v1.5.3*) does not yet have a binary version for Windows deployed to *PyPI*. Because of this, trying to *pip* install *netcdf4* (and, so, *landlab*) on Windows results in an error,
```python
    ValueError: did not find HDF5 headers
```
This version of *netcdf4* was released just a few days ago so this will probably fix itself within the next day or so. With version *v1.5.2* the Windows binary came 2 days after the rest. In the meantime, requiring *netcdf4==1.5.2* should fix things.

**Comment by mcflugen** [comment]
It appears the Windows builds are now up on [PyPI](https://pypi.org/project/netCDF4/1.5.3/#files) so this issue should be resolved.

**Comment by veenstrajelmer** [comment]
This issue occurs again, but it is solved by updating to python=3.8

**Comment by Crissan85** [comment]
I have Python 3.8.9 but I get the same error..

**Comment by veenstrajelmer** [comment]
You might want to update it anyway, Python 3.8 is not supported anymore: https://devguide.python.org/versions/. Old python versions is the source for many dependency conflicts, most issues are resolved by updating Python. I have no clue if that is the case here, but you could give it a try.
