### ISSUE TITLE
Install instructions on splash page are *very* outdated

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#1042]
Notably, still says install from the `-landlab` channel.

**Comment by kbarnhart** [comment]
Also many links go to the wiki. These links should go to the rtfd page.

**Comment by SiccarPoint** [comment]
Got it...

**Comment by kbarnhart** [comment]
Another thought for the pr that revises the splash page (from the bus!): it
should have a quick sentence that says ll2.0beta exists and gives a link to
rtfd, notebooks repo, code.

**Comment by SiccarPoint** [comment]
Now complete over at https://github.com/landlab/landlab.github.io. Note I pointed the links at the v.2 docs. I think this works, but might need attention at switchover time.
