### ISSUE TITLE
the conda -c landlab channel

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#1044]
This needs killing, provided there's no urgent reason to keep it. It's running way behind conda-forge and pip in terms of version, and isn't supported in our install instructions (any more).

Any reason why it can't just be hacked out?

@mcflugen This is your baby, so thoughts welcome!

**Comment by kbarnhart** [comment]
I think we discussed this on another channel and it was resolved. 
@SiccarPoint can you comment or close?
