### ISSUE TITLE
calculating curvature

### ISSUE THREAD

**Issue by Glader011235** [landlab/landlab#1063]
This is not an issue per se, but a best-practices question- does anyone have an example to look at for calculating curvature? I'm working with a flux equation that includes it, so I'd like to diff slopes and map the resulting curvature to links. I'm struggling to find the best way to do this while preserving the proper direction for slope differencing and mapping the curvature to the correct links.

**Comment by SiccarPoint** [comment]
There's c. 2012 (?) paper led by Martin Hurst (I think - it's def Simon Mudd's group) that tackles this extensively for ridge lines.

**Comment by Glader011235** [comment]
Thanks- that is somewhat helpful, though I'm more looking for an example in landlab to make sure that maps a gradient of gradients to links.

**Comment by SiccarPoint** [comment]
Ah, sorry. To my knowledge, there isn't. Have a close look at the grid methods, but I don't think you'll find what you're after. This would be awesome to have though, if you wanted to design one...?

**Comment by Glader011235** [comment]
Ok cool, if I end up figuring out a good way I'll try to formalize it
