### ISSUE TITLE
FlowDirector D8 returns link ids that don't exist in grid

### ISSUE THREAD

**Issue by Glader011235** [landlab/landlab#1070]
When using FlowDirectorD8, mg.at_node['flow__link_to_receiver_node'] returns link IDs that don't exist in the grid. The total number of links for my example is 19800, but a substantial portion of flow__link_to_receiver_node are higher than 19800 (up to 39197). 

Perhaps I'm doing something wrong or don't understand link IDs- has this behavior been seen before?

**Comment by Glader011235** [comment]
I am a dumb dumb. Was only looking at total number of D4 links.

**Comment by kbarnhart** [comment]
@Glader011235 glad you figured it out. 

When the FlowDirector's use diagonals, then `flow__link_to_receiver_node` might be better named `flow__d8_to_receiver_node`... but then we'd have two names... and we decided against that.
