### ISSUE TITLE
Request help with pytest

### ISSUE THREAD

**Issue by saisiddu** [landlab/landlab#1087]
I have been struggling with pytest today. I am trying to run pytest on a single component-folder (for example: flexure - as shown below). I got a bunch of AttributeErrors. I am struggling to understand what went wrong? This might be a conda issue.
Computer: Windows 10
Python: Anaconda
Install: Developer
Branch: saisiddu/merge_runon_to_v1
![image](https://user-images.githubusercontent.com/7194053/71511755-4e061800-2848-11ea-8c8a-e480e7735c97.png)

**Comment by kbarnhart** [comment]
@saisiddu this sort of error often happens if the dependencies for the expected developer environment have changed. 

Can you verify that everything in `requirements-dev.txt` is installed.

Can you also provide the command you are using to run pytest?

**Comment by saisiddu** [comment]
Thanks, @kbarnhart! I did suspect that. It was particularly hard updating conda this time. I think I wasn't able to install pytest-datadir. I will have to remove anaconda completely and reinstall. There have been similar issues reported (stackoverflow). Will keep you guys posted.

**Comment by kbarnhart** [comment]
@saisiddu would you think about where in [the documentation](https://landlab.readthedocs.io/en/release/) you might have looked for help on this issue and identify whether the documentation has sufficient information for you to have troubleshoot this problem (I don't think it does, which is why I want to know where you would have looked). 

I'd like to use your issue as motivation to revise the part of the docs that would have looked at and make sure it has the information that you would have needed. 

I just opened #1088 (a related, but slightly different issue). 

I know that the docs now reflect `v2` but I think that improving this aspect of them is really version independent.

**Comment by saisiddu** [comment]
@kbarnhart: First of all, I think the documentation is awesome. I was able to clearly navigate to the pages for developer installation (including the Windows compiler issues). I do agree that we can update the documentation regarding this issue. I am still trying to solve this issue. Once I do that, I will add information to #1088.

**Comment by saisiddu** [comment]
Alright! I solved my issue. I **removed the existing Anaconda installation** from my computer and **installed the latest version**. 

Summary of the problem:
As mentioned in the beginning of this issue, pytest was reporting 'AttributeErrors'. I explored landlab.github.io documentation. Based on the instructions there, I tried installing/updating the packages 'pytest'  and 'pytest-cov'. I used commands similar to 'conda install pytest' and 'conda update pytest'. I noticed a weird response immediately as conda was trying to create 'custom-version numbers'. The update/install attempts failed when I tried to see through the process. 

How I solved the issue:
I googled the errors displayed when conda was unable to update the packages. There is a thread (in stackoverflow) addressing this issue. I tried a band-aid fix (**which I DONT RECOMMEND**). It involved replacing DLL files. Then, I uninstalled the existing anaconda python and deleted all folders (including the ones that start with a dot in the folder where anaconda3 folder resided). **I installed the latest version (in my case **Windows 10 64-bit** - Anaconda website automatically recognizes the best Python 3 distribution accordingly).** It worked like a charm. I was able to install/update pytest and pytest-cov. I tried installing all packages listed in 'requirements-dev.txt'. **It failed to install 'pytest-datadir'**. I only tried conda install though. **Therefore installing all packages using 'conda install --yes --file requirements-dev.txt' DID NOT work'.

**Comment by saisiddu** [comment]
I forgot to mention that I also searched the **issues page** here in this repository. I stumbled upon an issue listed by @SiccarPoint a few months back. I also found follow up issues that tried to address this (probably by @kbarnhart and @mcflugen).

**Comment by kbarnhart** [comment]
@saisiddu is this resolved? If so can you close?

**Comment by saisiddu** [comment]
Yes, this is resolved. Thanks, Katy!
