### ISSUE TITLE
Error encounted in running CA and GrainHill related modules

### ISSUE THREAD

**Issue by JTQIN** [landlab/landlab#1090]
Hi everyone,

I try to run the "test_celllab_cts.py" in the subroutine "landlab\ca\tests" with my anaconda (with python 3.7). However, the error as following is reported. Also, similar errors are encountered in many functions related to the ca and grainhill module, e.g., those in the directories as "examples\ca" and "landlab\components\grain_hill". Could you please help me deal with it? Thanks.

Jintang

(landlab_dev) D:\landlab-master\landlab\ca\tests>python test_celllab_cts.py
Traceback (most recent call last):
  File "test_celllab_cts.py", line 406, in <module>
    test_grain_hill_model()
  File "test_celllab_cts.py", line 266, in test_grain_hill_model
    from .grain_hill import GrainHill
ImportError: attempted relative import with no known parent package

**Comment by JTQIN** [comment]
Error in ca module again.

Today, I reinstalled the landlab 2.0 under the Aroconda 3.0. I run the "test_grain_hill_model" in the "tests" directory. However, the parent package error occurs again. Can I have some way to deal with it? Thank you.


(landlab_dev) E:\landlab-master\tests\ca>dir


 E:\landlab-master\tests\ca 

2020/01/06  22:14    <DIR>          .
2020/01/06  22:14    <DIR>          ..
2020/01/06  22:14    <DIR>          boundaries
2020/01/06  12:11             5,412 cts_model.py
2020/01/06  12:11            16,375 grain_hill.py
2020/01/06  12:11               377 grain_hill_params.txt
2020/01/06  12:11            37,438 lattice_grain.py
2020/01/06  12:11            14,687 test_celllab_cts.py
2020/01/06  12:11                 0 __init__.py
2020/01/06  22:14    <DIR>          __pycache__
               6 个文件         74,289 字节
               4 个目录 342,634,090,496 可用字节

(landlab_dev) E:\landlab-master\tests\ca>python test_celllab_cts.py
Traceback (most recent call last):
  File "test_celllab_cts.py", line 418, in <module>
    test_grain_hill_model()
  File "test_celllab_cts.py", line 278, in test_grain_hill_model
    from .grain_hill import GrainHill
**ImportError: attempted relative import with no known parent package**

**Comment by kbarnhart** [comment]
@JTQIN the tests are intended to be run by pytest from the command line.

can you run the following?

```
pytest tests/ca
```

**Comment by JTQIN** [comment]
@kbarnhart 
Thanks, Katy.
I ran the pytest tests/ca just now. It looks good, with no error, although 77 warnings.

(landlab_dev) E:\landlab-master>pytest tests/ca
================================================= test session starts =================================================
platform win32 -- Python 3.8.1, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: E:\landlab-master, inifile: setup.cfg
plugins: cov-2.8.1, datadir-1.3.1
collected 17 items

tests\ca\grain_hill.py ..                                                                                        [ 11%]
tests\ca\lattice_grain.py ..                                                                                     [ 23%]
tests\ca\test_celllab_cts.py ...........                                                                         [ 88%]
tests\ca\boundaries\test_hex_normal_fault.py ..                                                                  [100%]

================================================== warnings summary ===================================================
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
landlab\utils\decorators.py:143
  E:\landlab-master\landlab\utils\decorators.py:143: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    argspec=inspect.formatargspec(*argspec),

landlab\core\utils.py:334
  E:\landlab-master\landlab\core\utils.py:334: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
  E:\landlab-master\landlab\graph\voronoi\voronoi_to_graph.py:312: PendingDeprecationWarning: dropping variables using `drop` will be deprecated; using drop_vars is encouraged.
    self._mesh = self._mesh.drop(

tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
tests/ca/test_celllab_cts.py::test_hex_cts
tests/ca/test_celllab_cts.py::test_hex_cts
tests/ca/test_celllab_cts.py::test_oriented_hex_cts
tests/ca/test_celllab_cts.py::test_oriented_hex_cts
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_grain_hill_model
tests/ca/test_celllab_cts.py::test_transitions_as_ids
tests/ca/test_celllab_cts.py::test_transitions_as_ids
tests/ca/test_celllab_cts.py::test_handle_grid_mismatch
tests/ca/test_celllab_cts.py::test_handle_grid_mismatch
tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
  E:\landlab-master\landlab\graph\voronoi\voronoi_to_graph.py:320: PendingDeprecationWarning: dropping variables using `drop` will be deprecated; using drop_vars is encouraged.
    self._mesh = self._mesh.drop(list(at_))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================== slowest 16 test durations ==============================================
0.36s call     tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.get_profile_and_soil_thickness
0.19s call     tests/ca/test_celllab_cts.py::test_grain_hill_model
0.12s call     tests/ca/grain_hill.py::tests.ca.grain_hill.GrainHill.initialize_node_state_grid
0.03s call     tests/ca/boundaries/test_hex_normal_fault.py::test_links_to_update
0.03s call     tests/ca/test_celllab_cts.py::test_raster_cts
0.03s call     tests/ca/boundaries/test_hex_normal_fault.py::test_shift_link_and_transition_data_upward
0.02s call     tests/ca/test_celllab_cts.py::test_handle_grid_mismatch
0.02s call     tests/ca/test_celllab_cts.py::test_transitions_as_ids
0.02s call     tests/ca/test_celllab_cts.py::test_hex_cts
0.02s call     tests/ca/test_celllab_cts.py::test_oriented_hex_cts
0.01s call     tests/ca/test_celllab_cts.py::test_run_oriented_raster
0.01s call     tests/ca/test_celllab_cts.py::test_oriented_raster_cts
0.01s call     tests/ca/test_celllab_cts.py::test_setup_transition_data

(0.00 durations hidden.  Use -vv to show these durations.)
=========================================== 17 passed, 77 warnings in 4.20s ===========================================

**Comment by kbarnhart** [comment]
@JTQIN it looks like we've addressed your issue so I'm closing this. If you have any other questions, please comment or open another issue.
