### ISSUE TITLE
Remove cruft and organization

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1100]
We discussed removing cruft on the the call this morning. I've compiled some of the places we might look/remove. We can discuss each of these on this issue

Looks clear to me it should be removed:
- [x] landlab/testing (these are things that should be replaced with pytest or numpy testing?)

Already identified:
- [x] duplicate field creation (issue #1058)

Uncertain:
- [x] landlab/io/gebco 
- [x] landlab/io/vtk (its clear that having this would be good, but it is not done, I gather)
- [x] ~landlab/plot/event_handler.py (this and the next are very old and seem to me to be unused)~ KEEP
- [ ] landlab/plot/video_out.py 

I didn't look at (assigned to @mcflugen):
- [x] landlab/grid
- [x] landlab/graph
- [x] landlab/field

Other things I noticed:
 - [ ] Should landlab/framework get a new name or be moved to landlab/bmi. it seems everything in there has to do with bmi. 
- [ ] Its not clear why some things are in landlab/core/utils.py and some things are in landlab/utils... perhaps the distinction should be clearer. 

:wave: @landlab/core

**Comment by nathanlyons** [comment]
`event_handler` still works and is used to click on imshow_grid plots (eg in spyder, interactive jupyter plots) to get the node info where clicked.

**Comment by kbarnhart** [comment]
@nathanlyons thank you! I have removed it from the above list.

**Comment by nathanlyons** [comment]
Could the `animate_landlab_output` tutorial be the recommended method/replacement to `video_out`? Something like the latter is nice to make quick video, although not being able to animate grids and deep customization of plot elements is limited.

**Comment by nathanlyons** [comment]
Regarding distinctions of utilities, I think especially the user audience (sensu Barnhart et al, in progress) could benefit from having a groupings of 

- things that fall under earth surface dynamics (eg, `fault_fact_finder`, `flow_distance`, and `watershed`) and
- things associated with programming tasks, objects, and data structures (eg, `add_halo`, `count_repeats`, `decorators`).

The programmy things could live in landlab/core/utils/ along with `utils.py`. The earth surface dynamics things in their current location.

Maybe some things will be hard to fit in these designations (eg `source_tracking_algorithm`, maybe bad example) in which case if there is not a clear reason, I advocate to leave with the earth surface dynamics things.

**Comment by kbarnhart** [comment]
Three of four uses of the 
```
FAILED landlab/io/esri_ascii.py::landlab.io.esri_ascii.write_esri_ascii
FAILED landlab/io/native_landlab.py::landlab.io.native_landlab.load_grid
FAILED landlab/io/native_landlab.py::landlab.io.native_landlab.save_grid
=== 3 failed, 2931 passed, 61 skipped, 20933 warnings in 227.19s (0:03:47) 
``` 

fail with recursion associated with 

```
______________ [doctest] landlab.io.esri_ascii.write_esri_ascii _______________
3311528     --------
3312529     >>> import numpy as np
3313530     >>> import os
3314531     >>> import tempfile
3315532     >>> from landlab import RasterModelGrid
3316533     >>> from landlab.io.esri_ascii import write_esri_ascii
3317534 
3318535     >>> grid = RasterModelGrid((4, 5), xy_spacing=(2., 2.))
3319536     >>> _ = grid.add_field("air__temperature", np.arange(20.), at="node")
3320537     >>> with tempfile.TemporaryDirectory() as tmpdirname:
3321UNEXPECTED EXCEPTION: RecursionError('maximum recursion depth exceeded while calling a Python object')
3322Traceback (most recent call last):
3323  File "c:\python38-x64\lib\shutil.py", line 610, in _rmtree_unsafe
3324    os.rmdir(path)
3325PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpn49wm6bq'
3326During handling of the above exception, another exception occurred:
3327Traceback (most recent call last):
3328  File "c:\python38-x64\lib\tempfile.py", line 800, in onerror
3329    _os.unlink(path)
3330PermissionError: [WinError 5] Access is denied: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpn49wm6bq'
3331During handling of the above exception, another exception occurred:
3332Traceback (most recent call last):
3333  File "c:\python38-x64\lib\shutil.py", line 610, in _rmtree_unsafe
3334    os.rmdir(path)
3335PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpn49wm6bq'
3336During handling of the above exception, another exception occurred:
3337Traceback (most recent call last):
3338  File "c:\python38-x64\lib\tempfile.py", line 800, in onerror
3339    _os.unlink(path)
3340PermissionError: [WinError 5] Access is denied: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpn49wm6bq'
3341During handling of the above exception, another exception occurred:
3342Traceback (most recent call last):
3343  File "c:\python38-x64\lib\shutil.py", line 610, in _rmtree_unsafe
3344
```

@mcflugen any recommendations?
