### ISSUE TITLE
DataRecord calc_aggregate_value edit

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#1102]
Hey @nathanlyons @margauxmouchene : I believe I've found a minor glitch in DataRecord, and I'm wondering if one of you can implement a (hopefully quick and easy for you) fix. 

When using `calc_aggregate_value` with a `filter_array` that is all `False`, I get a traceback error.

Example: I have an instance of DataRecord called `parcels` with the variable "volume". I want to sum up the total volume of parcels on each link that meet some criteria (as defined by the filter_array). 
```
Test= parcels.calc_aggregate_value(
    np.sum, "volume", at="link", filter_array=np.zeros_like(parcels.dataset.volume.values,dtype=bool)
) 
```

If at least one parcel meets the filter_array criteria (at least one `True`), all works as expected. However, if none of the parcels meet the filter_array criteria (all `False`), I get the following traceback error: 

```
Traceback (most recent call last):

  File "<ipython-input-80-fe96b9d0c10c>", line 2, in <module>
    np.sum, "volume", at="link", filter_array=np.zeros_like(parcels.dataset.volume.values,dtype=bool)

  File "c:\users\pfeif\documents\github\landlab\landlab\data_record\data_record.py", line 1122, in calc_aggregate_value
    vals = filtered.apply(func, *args, **kwargs)  # .reduce

  File "C:\Users\pfeif\Anaconda3\envs\landlab_dev\lib\site-packages\xarray\core\groupby.py", line 761, in apply
    return self._combine(applied)

  File "C:\Users\pfeif\Anaconda3\envs\landlab_dev\lib\site-packages\xarray\core\groupby.py", line 765, in _combine
    applied_example, applied = peek_at(applied)

  File "C:\Users\pfeif\Anaconda3\envs\landlab_dev\lib\site-packages\xarray\core\utils.py", line 154, in peek_at
    peek = next(gen)

StopIteration

```
I believe that a small edit to the `calc_aggregate_value` method should fix this, something to just output all `nan` values if `np.all(filter_array==False)` is `True`. 

tagging @kbarnhart on this, too.

**Comment by nathanlyons** [comment]
Thanks for making this issue. May you please confirm that the example below is equivalent to the issue you are describing?

```python
import numpy as np
from landlab.data_record import DataRecord
from landlab import RasterModelGrid

# Create an example DataRecord.

grid = RasterModelGrid((3,3))
element_id = [0, 0, 0, 0, 1, 2, 3, 4, 5, 9999]
volumes = [4, 5, 1, 2, 3, 4, 5, 6, 7, 1234]
ages = [10, 11, 12, 13, 14, 15, 16, 8, 10, 3456]
grid_element = 'node'
data = {'ages': ages, 'volumes': volumes}

dr = DataRecord(
    grid,
    dummy_elements={"node": [9999]},
    items={'grid_element' : 'node', 'element_id' : np.array(element_id)},
    data_vars={
        'ages' : (['item_id'], np.array(ages)),
        'volumes' : (['item_id'], np.array(volumes))
    }
)

# Create a filter with all False elements.

f = dr.dataset['ages'] > 4000

v_f = dr.calc_aggregate_value(
    func=np.sum,
    data_variable='volumes',
    filter_array=f
)
```
The error I get `Failed to group data. Are you grouping by a variable that is all NaN?`

**Comment by pfeiffea** [comment]
thanks for the quick reply, @nathanlyons 

When you say you "get an error", do you mean that a specific error message comes up? (I don't get that, I just get the `StopIteration` above... 

The filtering I'm trying to do occasionally results in  a filter array of all `False`. 

Perhaps this is not worth fixing at the level of DataRecord. It just means that every time I use a filter_array I have to put it in an `if` statement to check for the all `False` condition...

Let me know what you think

**Comment by nathanlyons** [comment]
Thanks for indicating you believe my minimum reproducible example is equivalent. I am not sure about the details of how our different error messages come about. I do think the issue can be addressed by DataRecord checking if `filter_array` is all False as you described. 

To me it makes sense to return an array of size number-of-grid_elements where each element is the `fill_value` of the `calc_aggregate_value` method. The default `fill_value` is np.nan. I will aim to submit a pull request to make this modification by tomorrow.

**Comment by pfeiffea** [comment]
That makes great sense. Thank you!
