### ISSUE TITLE
JOSS Review groundwater component: JOSS paper

### ISSUE THREAD

**Issue by rreinecke** [landlab/landlab#1105]
Please consider adding a short paragraph on:
State of the field: Do the authors describe how this software compares to other commonly-used packages?

**Comment by kbarnhart** [comment]
[Linking to the JOSS Review Issue](https://github.com/openjournals/joss-reviews/issues/1935)

**Comment by DavidLitwin** [comment]
I have addressed this [here](https://github.com/landlab/landlab/commit/bb2db392b868a9f96f6d2a8829911d3187856d7c) by updating the docstring for the component to caution users about model assumptions. 

The supplemental theory page [here](https://landlab.readthedocs.io/en/master/reference/components/dupuit_theory.html#dupuit-theory) also describes the assumptions made when using the Dupuit-Forcheimer approximation, and how this affects the governing equations solved.

**Comment by DavidLitwin** [comment]
Referencing pull request #1122.

**Comment by rreinecke** [comment]
@DavidLitwin very nice paragraph. I think this provides a much more complete view on the issue. (even though I like to again to self-promote my publication here: https://www.geosci-model-dev.net/12/2401/2019" - maybe be future research into this topic ;))

**Comment by rreinecke** [comment]
@DavidLitwin can be closed as soon as it is merged.
