### ISSUE TITLE
JOSS review groundwater component: Tutorial

### ISSUE THREAD

**Issue by rreinecke** [landlab/landlab#1106]
Can you please add a step that verifies whether the mass balance is conserved also with varying step sizes and recharge rates?

What about different boundary conditions? Could you at least summarize what else is possible?

**Comment by kbarnhart** [comment]
[Linking to the JOSS Review Issue](https://github.com/openjournals/joss-reviews/issues/1935)

**Comment by DavidLitwin** [comment]
Yes, can do. I think that all of these are good ideas. It won't happen today but I will work on it when I'm able.

**Comment by DavidLitwin** [comment]
Referencing pull request #1123 Thank you for suggesting this, I think it adds a lot to the tutorial!
