### ISSUE TITLE
JOSS review groundwater component: Equations and documentation

### ISSUE THREAD

**Issue by rreinecke** [landlab/landlab#1107]
You say that you are using the Dupuit–Forchheimer assumption to calculate groundwater flow right? That requires a lot of assumptions and is often used wrongly. Could you please show me where in the documentation this issue is discussed? If not please make it visible to potential users what the limitations of your approach are and what assumption need to hold! I think this is pivotal.

**Comment by kbarnhart** [comment]
[Linking to the JOSS Review Issue](https://github.com/openjournals/joss-reviews/issues/1935)

**Comment by DavidLitwin** [comment]
I have addressed this [here](https://github.com/landlab/landlab/commit/bb2db392b868a9f96f6d2a8829911d3187856d7c) by updating the docstring for the component to caution users about model assumptions. 

The supplemental theory page [here](https://landlab.readthedocs.io/en/master/reference/components/dupuit_theory.html#dupuit-theory) also describes the assumptions made when using the Dupuit-Forcheimer approximation, and how this affects the governing equations solved.
