### ISSUE TITLE
cannot import Landlab after updating to Landlab 2.0

### ISSUE THREAD

**Issue by alangston** [landlab/landlab#1129]
Hi LL team, 

@kbarnhart advised me that Landlab 2.0 had been released and that when I updated to LL2.0 on my local machine, I would have a few conflicts that would need to be resolved. 

I resolved conflicts and updated to LL2.0. Now when I call landlab: import landlab  I get the following error message:

`ImportError: cannot import name 'map_pairs_to_values' from 'landlab.graph.sort.ext.remap_element' (c:\users\abby\documents\github\landlab\landlab\graph\sort\ext\remap_element.cp37-win_amd64.pyd)`

I updated conda --all. I am on a windows machine.

Any advice or direction is appreciated. 

Abby

**Comment by mcflugen** [comment]
@alangston You probably need to recompile/install. From the top-level landlab folder, try running the following,
```bash
$ pip install -e .
```

**Comment by alangston** [comment]
Awesome, problem solved!
