### ISSUE TITLE
Launching notebooks locally

### ISSUE THREAD

**Issue by nathanlyons** [landlab/landlab#1157]
Docs [here](https://landlab.readthedocs.io/en/master/install/index.html#conda-environment) and [here](https://github.com/landlab/landlab/tree/release#conda-environment-with-pre-packaged-binary-distribution) give instructions to clone the repo. Does this mean that the following two copies of landlab will exist on the user's computer:
1. the downloaded copy from the repo existing for the sole purpose of including the notebooks, and
2. the binary installed copy that is used to run the notebooks?

I am helping a prof offline who uses Landlab in courses who has transitioned to Landlab 2.

**Comment by kbarnhart** [comment]
@nathanlyons I think this can be closed? correct?

**Comment by nathanlyons** [comment]
I kept it open because the current approach to disseminate tutorials as described in docs is temporary, not that this issue makes that clear. I'll close it because there's plenty of overlapping tutorial issues.
