### ISSUE TITLE
Updating flow accumulation without updating flow directions

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1176]
When working with the groundwater model, there are circumstances where the hydrological state may be updated much more frequently than the geomorphology. Because of that, it would be efficient to separate updating flow direction from updating accumulated flow. 

From a brief email exchange with @kbarnhart, it seems like the best way to do this is to use `FlowAccumulator.accumulate_flow(self, update_flow_director=False)`, but there is a lack of clarity in the documentation about how to do this in combination with a flow director that's already instantiated. I'll attach some simplified code to give you an idea of what I'm after. I'm not yet sure whether this is doing what I think it should be, as noted in the inline comments.

[separate_flow_direction_accum.zip](https://github.com/landlab/landlab/files/4428541/separate_flow_direction_accum.zip)

**Comment by kbarnhart** [comment]
@DavidLitwin what you have written should accomplish what you want. There is something about your code that doesn't make sense to me, and I've noted it below. 

I'll take a stab on improving the docstring, link to it here, and ask for your recommendations on it. 
In looking at this, I've also noticed that IF a depression finder is passed (as is not the case in your example), you can turn off recalculating flow directions, but you can't turn off recalculating depressions. So I'll add the ability to do that too. 

```python
import numpy as np
from landlab import RasterModelGrid
from landlab.components import (
    GroundwaterDupuitPercolator,
    FlowDirectorD8,
    FlowAccumulator,
    FastscapeEroder,
    LakeMapperBarnes,
)

# create grid, sest boundary conditions
grid = RasterModelGrid((10, 10), xy_spacing=10.0)
grid.set_closed_boundaries_at_grid_edges(True, True, False, True)

# add fields.
elev = grid.add_zeros("topographic__elevation", at="node")
grid.add_zeros("aquifer_base__elevation", at="node")
elev[:] = 1 + 0.1 * np.random.rand(len(elev))
wt = grid.add_zeros("water_table__elevation", at="node")
wt[:] = elev

# initialize components
gdp = GroundwaterDupuitPercolator(grid)
fd = FlowDirectorD8(grid)
fa = FlowAccumulator(
    grid, flow_director=fd, runoff_rate="surface_water__specific_discharge"
)
lm = LakeMapperBarnes(grid)
sp = FastscapeEroder(grid, discharge_field="surface_water__discharge")

# run geomorph
for i in range(100):

    # find flow directions on updated topography
    fd.run_one_step()

    # route flow through depressions in topography
    lm.run_one_step()

    # run a series of hydrological steps
    for j in range(100):

        # run groundwater model for dt=1000
        gdp.run_one_step(1000)

        # update surface_water_discharge withotu re-routing flow
        _, _ = fa.accumulate_flow(update_flow_director=False)

        # Question: I don't understand why you would do this unless there were
        # something you were doing with the field "surface_water_discharge"
        # within this loop. If reinfiltration were supported, then this would
        # make sense to me. Similarly, if you wanted to run calc_sw_flux_out
        # within the hydrological timesteps, then this would make sense. 
        # My assumption is that in your simple example, you've left out the 
        # reason for needing to recalculate surface_water_discharge, so please
        # correct me if I'm wrong. 

    # update topography with erosion from surface_water_discharge
    sp.run_one_step(10)
```
