### ISSUE TITLE
ErosionDeposition/Space mass conservation and interior nodes that drain to themselves

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1177]
Through careful and creative toy experiments @vaga3461 has identified that the way ErosionDeposition and Space handle sediment results in "evaporation" of sediment at ALL nodes that flow to themselves. This is reasonable behavior in only one circumstance: when that node is located at model grid edge and is an open boundary. 

Under other circumstances (e.g., closed boundary, bottom of an interior drained pit) the sediment should be deposited locally. 

There has been some discussion (mostly between @cmshobe @gregtucker and myself) about exactly how this should be handled. 

I am very very unlikely to be the person who actually fixes this, but since I've now had a few conversations about it I'm taking these notes for all our benefit (tag: @gregtucker @cmshobe @vaga3461 @BCampforts).

In the absence of a depression finder, there is no information about the size of "lakes" and thus the only real option for mass conservation is to dump all the sediment in the single pit node. I *think* however, that we will still lose any sediment that goes to fraction of fines. 

In the presence of a depression finder there are some options:
1) Option easiest is to handle this in the same way as without a depression finder. 
2) If a lake exists and has connectivity to an open boundary, how much sediment should get trapped in the lake (since we do route water and sediment through the lake). 
3) If a lake exists and it does not have any connectivity to an open boundary (e.g., a true Endorheic basin), how should sediment be distributed across it.?

A related, but distinct issue is #1172. A PR that addresses that should probably be merged before this issue is addressed.

**Comment by SiccarPoint** [comment]
I tangled with this a little in the course of trying to get the SedDepEroder and also a lake fill algorithm going. The "just drop all the sediment" is extremely prone to a. inducing model instability (if it's just dropped); b. grindingly slow run times (if normal timestep limited procedures are followed; and c. ...the same thing proceeding to crashes, as there are a subset of combinations of sediment flux and topography that aren't solvable under b without introducing some rules like your 2 and 3 (e.g., more than one node supplying a single pit node with sediment, IIRC).

I don't have much specific advice, but to say I suspect fixing this is going to be no fun at all. Ironically, you may find that the easiest and most robust solution is a, i.e., just turn off the rate limiting and dump all the sediment. Or, retain the mass loss and note this in the documentation. 

[This](https://github.com/landlab/landlab/tree/SiccarPoint/lake-filling-with-flux-for-realsies) is an abortive effort to do something similar but tracking water not sediment as a lake fills. May or may not be useful. IIRC I concluded that a sed transfer approach (i.e., your 2 and 3) requires fairly intense iteration over the lake nodes to get it to behave, and thus will *significantly* slow any component you try it in.

**Comment by gregtucker** [comment]
I can report that the CHILD model handles closed depressions and lakes by dumping all incoming sediment. This method conserved mass and produced the expected behavior of making delta-like features. See for example Figure 2B in

[https://onlinelibrary.wiley.com/doi/epdf/10.1002/esp.1952](https://onlinelibrary.wiley.com/doi/epdf/10.1002/esp.1952)

and Figure 8 in

[https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1365-2117.2012.00559.x](https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1365-2117.2012.00559.x)

That doesn't guarantee of course that the same approach will work in SPACE or ErosionDeposition, but it at least suggests that instability/freezing isn't necessarily inevitable.
