### ISSUE TITLE
space_dt

### ISSUE THREAD

**Issue by colineA** [landlab/landlab#1181]
I have an issue with the 'dt' in the Space component. In your example in the space component, I don’t understand why there is a “space_dt”? Why is it different of the “dt” of the loop?
Moreover, usually you use dt = 100 or dt =1 in your example but, if I understand it well, the default of dt is 0.001. It's a such big difference, why did you choose this value for the default?

Hope that my questions are clear enough;
Thanks a lot for your answers,
Coline

**Comment by gregtucker** [comment]
There is only one time step value used in the call to Space's `run_one_step` method. This seems to be just a matter of getting familiar with syntax, so I'm closing this.
