### ISSUE TITLE
Add Height Above Nearest Drainage (HAND) component? 

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1204]
Height Above Nearest Drainage (HAND) is a relatively new topographic metric that quantifies the elevation difference between any point in a DEM and the nearest point that is identified as a stream channel (Nobre et al 2011). In this way, it is the vertical complement of a flow path length, and average HAND is the vertical complement of 1/DD. Lately, it's appeared in the hydrological literature for prediction of areas of saturation, and even in a "calibration-free" rainfall runoff model (Nobre et al 2011, Gao et al 2018). 

I intend to use this metric to analyze synthetic topography generated from a landscape evolution model, but it would serve equally well for DEM analysis. To my knowledge, there are no python libraries that are currently set up to calculate it. HAND feels like a good fit for landlab in the spirit of the DrainageDensity and ChannelProfiler components. 

My intuition (and later a conversation with @kbarnhart) tells me that all of the information needed to calculate HAND should already be available from the single direction (D4, D8) FlowDirector components, but I am not an expert in these and it would likely be difficult for me to do this alone. [Nobre et al (2011)](https://github.com/landlab/landlab/files/4657155/Nobre.et.al_2011_Height.Above.the.Nearest.Drainage.a.hydrologically.relevant.new.terrain.model.pdf) describe the method they used to calculate HAND, attached here. I think it would be a substantial contribution to Landlab that others may find very useful too. Is anyone willing to help me on this?
@kbarnhart, @mcflugen, or @gregtucker?

Cited:
Gao, H., Birkel, C., Hrachowitz, M., Tetzlaff, D., Soulsby, C., & Savenije, H. H. G. (2018). A simple topography-driven and calibration-free runoff generation module. Hydrology and Earth System Sciences Discussions, 787–809. https://doi.org/10.5194/hess-2018-141

Nobre, A. D., Cuartas, L. A., Hodnett, M., Rennó, C. D., Rodrigues, G., Silveira, A., et al. (2011). Height Above the Nearest Drainage – a hydrologically relevant new terrain model. Journal of Hydrology, 404(1), 13–29. https://doi.org/10.1016/j.jhydrol.2011.03.051

**Comment by kbarnhart** [comment]
@DavidLitwin I think this is a great idea and would make a great contribution. I'm not able to commit a lot of time, but am happy to provide guidance on using the data structures built by the flow director components.

**Comment by DavidLitwin** [comment]
Thank you, @kbarnhart. I know we talked about this before, but could you sketch out briefly for me what method you might use to associate a nearest drainage node with every node? No code required, just trying to think this through.

**Comment by gregtucker** [comment]
@DavidLitwin this paper might provide one approach: Tucker, G. E., Catani, F., Rinaldo, A., & Bras, R. L. (2001). Statistical analysis of drainage density from digital terrain data. Geomorphology, 36(3-4), 187-202.

**Comment by kbarnhart** [comment]
@DavidLitwin 

Given a node id `id`, and an at-node array called `is_drainage_node` that indicates whether a node is a drainage or not, lets create an new at_node array that is the ID of the nearest downstream node. 

My sense is that you want that ID rather than, say the distance between them... yes?

This should be able to be cythonized, made faster, but you get the idea. 
 
```python
receivers = grid.at_node["flow__receiver_node"] # created by FlowDirectors
downstream_drainage_id = np.empty()

for i in range(number of nodes):
    reached_drainage = False
    cur_node = i
    while not reached_drainage:
        downstream_id = receivers[cur_node]
        if is_drainage_node[downstream_id]:
            downstream_drainage_id[i] = downstream_id
            reached_drainage = True
        else:
            cur_node = downstream_id
```

Agree with @gregtucker that looking at the DrainageDensity component and the paper he mentioned is a good idea.

**Comment by DavidLitwin** [comment]
Thanks so much! That's very helpful, I'll see what I can do.
