### ISSUE TITLE
Ran the pytest and returned 22 errors, but did not see fixes - any suggestions?

### ISSUE THREAD

**Issue by smchartrand** [landlab/landlab#1209]
I use Linux Mint 18.3, Cinnamon environment.

Anaconda Navigator 1.9.12 and Python 3.x

I installed Landlab using the conda installation procedure.

I navigated to the following directory: 

> ~/anaconda3/pkgs/landlab-2.1.1-py37h03ebfcd_0/lib/python3.7/site-packages/tests 

and ran the pytest as this is the only directory where the test would actually run.

The test returned the following details [the attached file contains the full print out to terminal of the pytest]
[Landlab_pytest_results.txt](https://github.com/landlab/landlab/files/4686502/Landlab_pytest_results.txt)
:

- 1608 passed, 19 skipped, 281 warnings, 22 errors in 39.56s

- All errors had the following message: 

> E       fixture 'datadir' not found

- Here is the test short summary:

> ========================================== short test summary info ===========================================
ERROR grid/test_create.py::test_esri_ascii_create
ERROR grid/test_create.py::test_read_netcdf_create
ERROR grid/test_create.py::test_bad_boundary_condition_functions
ERROR io/test_read_esri_ascii.py::test_hugo_read_file_name
ERROR io/test_read_esri_ascii.py::test_hugo_read_file_like
ERROR io/test_read_esri_ascii.py::test_hugo_reshape
ERROR io/test_read_esri_ascii.py::test_4x3_read_file_name
ERROR io/test_read_esri_ascii.py::test_4x3_read_file_like
ERROR io/test_read_esri_ascii.py::test_name_keyword
ERROR io/test_read_esri_ascii.py::test_halo_keyword
ERROR io/test_read_esri_ascii.py::test_halo_keyword_no_nodata_value
ERROR io/netcdf/test_from_netcdf.py::test_from_grid[HexModelGrid]
ERROR io/netcdf/test_from_netcdf.py::test_from_grid[RadialModelGrid]
ERROR io/netcdf/test_from_netcdf.py::test_from_grid[RasterModelGrid]
ERROR io/netcdf/test_read_netcdf.py::test_read_netcdf
ERROR io/netcdf/test_read_netcdf.py::test_read_netcdf_64bit
ERROR io/netcdf/test_read_netcdf.py::test_read_netcdf4_bad_field_name
ERROR io/netcdf/test_read_netcdf.py::test_read_netcdf3_64bit
ERROR io/netcdf/test_read_netcdf.py::test_read_netcdf4
ERROR io/netcdf/test_read_netcdf.py::test_bad_data_size
ERROR io/netcdf/test_read_netcdf.py::test_bad_dx
ERROR io/netcdf/test_read_netcdf.py::test_bad_llc

It is probably operator error on my part. Thanks in advance for help.

**Comment by kbarnhart** [comment]
@smchartrand a clarification question:

When you say "using the conda installation procedure" do you mean you [installed with conda-forge](https://landlab.readthedocs.io/en/master/install/index.html#conda-instructions), or do you mean you created a conda environment as part of the [developer installation instructions](https://landlab.readthedocs.io/en/master/development/install/index.html)?

Running the tests using pytest is intended for the latter "source code" install and the conda environment specified for development includes a the dependency to make the fixture data-dir go away.

Let me know if you have follow up questions.

**Comment by smchartrand** [comment]
Ahhh. Yes, I used conda forge. So I take it this.means I am good to go, no issues? Thanks so much for the very fast response.
Best,
- Shawn

On May 27, 2020 6:27 a.m., Katy Barnhart <notifications@github.com> wrote:

@smchartrand<https://github.com/smchartrand> a clarification question:

When you say "using the conda installation procedure" do you mean you installed with conda-forge<https://landlab.readthedocs.io/en/master/install/index.html#conda-instructions>, or do you mean you created a conda environment as part of the developer installation instructions<https://landlab.readthedocs.io/en/master/development/install/index.html>?

Running the tests using pytest is intended for the latter "source code" install and the conda environment specified for development includes a the dependency to make the fixture data-dir go away.

Let me know if you have follow up questions.

**Comment by kbarnhart** [comment]
@smchartrand Yes you should be good to go. We tests that the prebuilt binaries (what you get from pypi or conda-forge) pass all the tests before we build them. 

Happy modeling!

**Comment by smchartrand** [comment]
Excellent! I knew the issue was on my end. Have a great day and thanks again for the quick responses!

best,

-shawn

________________________________
