### ISSUE TITLE
Error in hydrograph_class_notebook (Teaching Module)

### ISSUE THREAD

**Issue by kxwhipple** [landlab/landlab#1227]
Since the migration to landlab 2 this teaching module appears to generate all zeros for the plotted hydrographs. Using all default parameters here is the resulting plot:
![hydrographs_landlab2_output](https://user-images.githubusercontent.com/40966478/89717085-e086a200-d967-11ea-9c1d-0b43665d5683.png)

Of course it should look like the output under the version prior to the migration to landlab 2:
![hydrographs_landlab1_output](https://user-images.githubusercontent.com/40966478/89717101-06ac4200-d968-11ea-9301-d938ae362ab1.png)

Love the new Binders - super easy to deploy in a classroom. Love the exercises, hoping to use this one again.
Operator error is always possible.
Kelin

**Comment by kbarnhart** [comment]
@kxwhipple definitely not operator error. thanks for finding this. 

I'm pretty sure figured it out... a forthcoming PR should fix it. After that we'll make a new landlab release so that the version on Binder reflects those changes.

**Comment by kxwhipple** [comment]
Thanks for the quick response!

**Comment by kbarnhart** [comment]
No problem! Glad you caught this at the beginning of the semester! I've made the PR, I don't know the timeline for when relevant folks (@nicgaspar, @mcflugen, @gregtucker) will be able to look at it (in part bc they are all involved in the ESPIN workshop/summer school). 

But I bet we'll be able to get this fix reflected in binder in the next week or two.

**Comment by kxwhipple** [comment]
A zero rain rate would certainly explain it!  Timing is good.  I wasnt even setting out to test, just updating links and instructions for how to use the teaching notebooks and discovered the beauty of the Binder solution.  So great. So easy.  Was only running through it to test speed. Thanks again.
