### ISSUE TITLE
Broken unit tests

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#124]
The unit tests seem to be broken again. It can't be anything too major. I'll have a look.

**Comment by mcflugen** [comment]
Fixed with PR #125.

**Comment by mcflugen** [comment]
The tests are broken again. I don't think it's anything major. Some doctests in the `cellular_automata` component aren't importing `landlab`. Probably just adding

    import landlab

before these doctests should fix things.

**Comment by gregtucker** [comment]
I added import statements to the doctests in cellular_automata, which seems to have fixed these test failures. I'm also seeing failures related to netcdf. The tests seem to think I don't have netCDF4 installed, but when I run pip it thinks I have them:

Gregorys-MacBook-Pro:cellular_automata gtucker$ pip install netcdf4
Requirement already satisfied (use --upgrade to upgrade): netcdf4 in /anaconda/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in /anaconda/lib/python2.7/site-packages (from netcdf4)

Yet:

>>> from netCDF4 import Dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: /opt/anaconda1anaconda2anaconda3/lib/libnetcdf.7.dylib
  Referenced from: //anaconda/lib/python2.7/site-packages/netCDF4/_netCDF4.so
  Reason: image not found

**Comment by mcflugen** [comment]
Do you know how you installed `netcdf4`? Was it with `pip`? Try uninstalling `netcdf4` and then reinstalling with conda. So,

    $ pip uninstall netcdf4
    $ conda install netcdf4

**Comment by gregtucker** [comment]
netCDF4 isssue now resolved by using conda to install. link_orientation issue fixed in the cellular automata module.

**Comment by mcflugen** [comment]
Broken again.

The offending files appear to be:
* `landlab/components/flow_routing/lake_mapper.py`
* `landlab/grid/structured_quad/links.py`

It looks like super-easy fixes but I don't have time to get to it right now.

**Comment by jadams15** [comment]
I'm going to work on fixing some of the errors in links.py starting now.

**Comment by mcflugen** [comment]
All tests are passing again!
