### ISSUE TITLE
SoilInfiltrationGreenAmpt

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1244]
Comment submitted via email:

We were looking at the SoilInfiltrationGreenAmpt component of LandLab and we have some thoughts that we hope will be useful for both this component and LandLab overall. 
 
Although the source code is available, it might be useful to structure the page more similar to how you have the model repository entries to highlight this and other information better. For example we missed the hyperlink at the top of the page initially due to the assumption that "source" was a link to the references; perhaps saying “source code” would clarify this. Other information could be more systematically displayed, such as information about units and time steps. Units of time would, be particularly useful to make explicit, since with Green-Ampt, the units for hydraulic conductivity are what determine the time step and someone could easily overlook that if they aren't as familiar with the formula. Version/date information would be useful too. 
 
I have two other more specific concerns about the Green-Ampt component. First, its code example produces an error if just copied pasted into a Jupyter notebook. We ultimately figured out the problem – the formatting makes it look like the output is part of the code – but the formatting could be improved. A user trying to quickly try out a component might be discouraged from proceeding further. 
 
Second, the implementation of the formula to determine the potential infiltration amount appears different from the reference from the model  (Rengers et al. 2015). Landlab implements it as: 
```
            dt 
            * self._hydraulic_conductivity 
            * ( 
                (wettingfront_depth + self._capillary_pressure + water_depth) 
                / wettingfront_depth 
            ) 
        ) 
```

However, Rengers says:

 
![image](https://user-images.githubusercontent.com/7528207/94459194-3f9cb200-0174-11eb-9cfd-282396ae2856.png)

This formula is in line with how we have it implemented in L-GrID. If LandLab is using a non-standard implementation of Green-Ampt they should be more explicit about this and about their rationale.

**Comment by gregtucker** [comment]
@SiccarPoint any insights on this issue?

**Comment by SiccarPoint** [comment]
Probably need to ping @frengers on the implementation question, as IIRC I transliterated this straight from his parent code. Assuming I didn't screw up the recoding, hopefully he will have the necessary technical insight?

**Comment by jonaslenz** [comment]
From my view the implementation in landlab does not equal the equation in the paper.

I compared the landlab approach to another Green-Ampt-implementation (https://github.com/csdms-contrib/GreenAmptInfiltrationModel/). In this implementation the GA-equation is written as:

```   
 def f(self, F):
        """
        Generate Green-Ampt Infiltration Rate at time t
        """
        if F == 0:
            return -9999
        else:
            return self.K * (self.psi * self.dtheta / F + 1)    
```
which comes much closer to the equation in the paper, only missing the "h" parameter (the ponding depth on soil surface).

You can find the comparison in a jupyter notebook on: https://github.com/jonaslenz/GreenAmptInfiltrationModel/blob/master/GA_comparison.ipynb

Please be patient with my coding, as I'm just entering python world.

**Comment by gregtucker** [comment]
Thanks for sharing this comparison @jonaslenz. Have you tested these calculations against a known analytical solution? If so it would be good to incorporate the solution as a formal test of the component (and if it does not currently match the expected solution, diagnose and correct it).

**Comment by jonaslenz** [comment]
@gregtucker I'm not aware of a known analytical solution for Green-Ampt-Infiltration, which could be used as a formal test. But would be interested in such a solution.

The solution used for my comparison uses a newton solver to find the penetration depth.
For my knowledge the calculation of the penetration depth is one crucial point with all Green-Ampt implementations. Basically the infiltration depth is the integral function of the infiltration rate, but this integral can hardly be solved. So all implementations I know use either a newton-like solver or an approximation for the penetration depth.

**Comment by gregtucker** [comment]
Thanks @jonaslenz. In that case it would be good to have a test case that compares the component's output with an independently verified numerical solution. I noticed that @SiccarPoint has doctests: Dan, are these based on a solution that you worked out independently?

**Comment by SiccarPoint** [comment]
No, I believe those are smoke tests to check for disruption of the code by future changes, rather than actual validation. Sorry...

**Comment by jonaslenz** [comment]
I'm sorry that I did not spot this earlier - actually the implemented equation in landlab **does** equal the equation in the paper.

 - The term "\phi-\theta_i" equals the _moisture_deficit - expressed in code in function calc_moisture_deficit (lines 244-283)
 - divide the whole term in inner brackets by moisture deficit
 - substitutes infiltration depth ("F") with the wetting front depth ("F / _moisture_deficit")   - line 344 in code
 - By rearanging this equation (apply divisor "F" to whole term in brackets) the implemented equation can be derived.

The differences found in my comparison may then result from different solver strategies for the wetting front penetration depth.
For example landlab does not calculate time to ponding, to distinct between time periods in which rainfall is below/exceeding potential infiltration.

> it would be good to have a test case that compares the component's output with an independently verified numerical solution

I totaly agree on this. Even there are published comparisons of green-ampt-implementation (e.g. DOI: https://doi.org/10.1007/s11269-011-9868-0) on base of described equations, a common test one may use to verify ones code (not limited to landlab) would be a great development.

**Comment by gregtucker** [comment]
Thanks @jonaslenz, this is good to hear. I'm going to close this issue, but if you would like to make a new issue requesting an independent test to use as a unit test (and for other implementations), or to add the time-to-ponding element, please feel free to do so.
