### ISSUE TITLE
Accumulating generic fields (not just runoff) using FlowAccumulator

### ISSUE THREAD

**Issue by AlexLipp** [landlab/landlab#1249]
Hi all, 

LandLab v1 had a function `find_drainage_area_and_discharge` as part of the FlowAccumulator component which allowed discharge at any point in a catchment to be calculated, given a variable runoff across the model grid. 
A very helpful (possibly unintended) use for this function, which colleagues and I made use of, is that it can be used to accumulate any generic variable that enters a drainage network. For example, if you feed the function (in place of the `runoff` argument) a `bedrock_incision` array, it then outputs the cumulative sediment flux at any point in the landscape (as the `discharge` output of the tuple). This has been a very useful functionality for us!  

However, this specific function has been removed as part of LandLab2. To produce the same results, it is now necessary to instantiate a new FlowAccumulator for every different field you want to accumulate (sediment flux, pollutant etc...), and then run it one step. This involves overwriting a field (`surface_water__discharge`) at every point, which throws a warning (albeit not an error). The major issue with this is that this whole process is around 50x slower than the method using LandLab1. For our purposes we need to able to run this many many times, and as such this reduction in speed is essentially breaking.  

My main request/question is whether it is possible to reintroduce the `find_drainage_area_and_discharge` function that takes variable runoff, but doesn't involve instantiating a new FlowAccumulator everytime. In otherwords, a way to calculate discharge given variable run-off for an already existing drainage network. Alternatively, is it possible to implement a generic `accumulate_field` function which takes as input a raster map of values and then accumulates them along the flowpaths. This is useful, as stated, for calculating cumulative sediment fluxes, but I can imagine uses for any number of things which travel along drainage networks. 
I was going to try defining such a function myself for LandLab2 but, looking at the source code, the original function in LandLab1 is basically just a call to something called `_accumulate_bw` which appears imported from a library called `.cfuncs` which I can't find the source of.  

Additionally, if there is a way to do this using LandLab2 components that I'm not aware of, please let me know! I have hunted around but to no avail...

I'm keen to upgrade fully to LandLab2 because of increased functionality (specifically the better stream profiling) and to stay aligned with the community but I can't find a way to efficiently implement this 'generic accumulator' which is essential for what I'm trying to do. Currently I have LandLab2 and LandLab1 in separate environments for separate, but switching between them is not ideal!

Cheers! 
Alex

**Comment by kbarnhart** [comment]
@AlexLipp this function still exists. Import 
```python
from landlab.components.flow_accum import flow_accum_bw, flow_accum_to_n
```

flow_accum_bw (bw=Braun & Willett (2012) only one flow receiver, to_n = multiple receivers)

these two submodules both contain the function you want (find_drainage_area_and_discharge). 

I'm not 100% sure whether you can use them in exactly the same way in LL2, but a code example of how you used this function before would be helpful for more detailed usage advice. 

It looks like the documentation for both of these functions exists in the sourcecode docstrings but isn't exposed in the sphinx docs yet... (a todo). You can also see how these two functions are used in the current flow accumulator. 

If a generic `accumulate_field` function that is bound to the FlowAccumulator is useful to you, I'd encourage making it in a pull request with those changes. It should be pretty straightforward. I'd take a look at what FlowAccumulator.accumulate_flow() does (honestly copy it to start). I designed the FlowAccumulator to have the same interface no matter whether its running to-one or to-many... which means that under the hood it has to handle both cases. There are also some tricks to handling the generic case of field name or array. If you go down this path, and have questions about this, let me know.  

And (in general) if you have questions about porting code from LL1 to LL2, please let us know (simple code examples that illustrate what you want to do are best, but longer examples can be fine too).

**Comment by AlexLipp** [comment]
Hi Katy, 

Thanks for this. Not sure how I managed to miss this, that's pretty embarrassing. Apologies! I will try out the functionality of the LL2 `find_drainage_area_and_discharge` function tomorrow and see if its still working as I want it to and post code snippets. When I've definitely got something up and running in LL2 I'm happy to close the comment.

I am keen to try and implement a generic accumulator. As you say, shouldn't be challenging and your pointers have been helpful. I had previously butted up against the fact that I couldn't actually find the source for the key `_accumulate_bw`  or `_accumulate_to_n` as this appears to be imported from a (C?) library. However, I see that I could simply modify the accumulate_flow() wrapper functions instead as you suggest. 

My one concern for this approach is that one of the arguments passed to `_accumulate_bw/n` is specifically hardcoded to be `discharge` which is not strictly speaking what it would be in case I envisage. This is I appreciate a matter of semantics but these things can rapidly get confusing.

**Comment by kbarnhart** [comment]
no prob @AlexLipp glad to help. 

here's how I'd approach making the generic function. I think this should all work just fine, but something might come up:

1. Modify `_accumulate_A_Q_to_one` and `_accumulate_A_Q_to_one` to take an optional final keyword argument (a string, that would be "water__unit_flux_in") such that by default what is accumulated would be self._grid.at_node["water__unit_flux_in"]. 

use `return_array_at_node` (imported already) to manage the fact that what is passed in might be a field or an array. You can see other instances of this being used in FlowAccumulator. 

2. Then create a second function `generic_accumulation` that is very similar to `accumulate_flow` takes one additional argument argument, a float, at-node-field str name, or an at-node sized field that is the value you want to accumulate. You'll need to delete the parts of `accumulate_flow` which points to `surface_water__discharge`, and then just pass your additional argument into the `_accumulate_A_Q_XXX` functions. 

That will remove hard  coding in accumulating water flux in (and thus producing discharge) with a minimal change to the code. 

By accomplishing this using an optional keyword argument that by default maintains current functionality, you maintain backwards compatiblity (yay). Though those functions start with underscores (means they are private and thus we don't promise they'll stay exactly the same).

**Comment by AlexLipp** [comment]
Ok, yup I can confirm the function still works as intended. Will close this issue now. 

Code snippet to give example of how to generate cumulative sediment flux using the `find_drainage_area_and_discharge` function below. Assumes model grid `mg` with topographic elevation defined. Additionally, we consider a field `incise` which is lowering rate defined at all nodes in model grid (which could be calculated, for example, using Fastscape component)

```

from landlab.components.flow_accum.flow_accum_bw import find_drainage_area_and_discharge

frr = FlowAccumulator(mg, 'topographic__elevation',  flow_director='D8')
frr.run_one_step()  

a,cum_sed_flux = find_drainage_area_and_discharge(mg.at_node['flow__upstream_node_order'],
                             mg.at_node['flow__receiver_node'],
                             runoff = incise) 
```

Will try and get on to defining a generic accumulator function at some point... at the moment AGU looms large!

**Comment by kbarnhart** [comment]
Sounds good @AlexLipp. Good luck preparing for AGU. Eventually as you move forward on generic accumulator, open an issue if you have questions or thoughts to discuss.

**Comment by kbarnhart** [comment]
@AlexLipp FYI. These functions are now in the docs https://landlab.readthedocs.io/en/master/reference/components/flow_accum.html#functions-to-support-flow-accumulation

**Comment by AlexLipp** [comment]
Awesome. thanks!
