### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by fzeng2** [landlab/landlab#1253]
![Screen Shot 2020-10-26 at 4 22 50 PM](https://user-images.githubusercontent.com/20801383/97238872-a202c580-17a7-11eb-8caf-5ef3de559f1d.png)

**Comment by gregtucker** [comment]
@fzeng2 is this triggered by running pytest on your local machine? If so I believe it has to do with a missing pytest utility for creating temporary files in your installation, and can be safely ignored, but pinging @mcflugen for verification.

**Comment by mcflugen** [comment]
@fzeng2 I believe @gregtucker is correct. You most likely just need to install the requirements for testing *landlab*. These requirements are listed in *requirements-testing.txt*. You can install them with,
```bash
$ pip install -r requirements-testing.txt
```

**Comment by fzeng2** [comment]
Thanks, solved.
