### ISSUE TITLE
New functionality request: generate MODFLOW SFR input using predefined linework

### ISSUE THREAD

**Issue by emorway-usgs** [landlab/landlab#1256]
It was recently suggested on the flopy repo (a python package for MODFLOW) that landlab could be used to generate the  streamflow routing package input file for MODFLOW ([here](https://github.com/modflowpy/flopy/issues/1015)).  I asked a follow up question to that post that I'll ask again below.  In short, this request is for additional functionality that likely would help many MODFLOW users, though there is no money to support its development.

The request: Does landlab have something that can take predefined linework (e.g., .shp file) representative of a irrigation system and generate SFR input from that? For example, irrigation ditch diversions typically follow DEM contours rather than flow perpendicular to them. To show you what I mean, consider the image below. Segments labeled "180," "182," "188," "193," & "196" represent the mainstem of a major river, whereas the other displayed segments represent features associated with an irrigation system built around the mainstem. There are numerous diversions (red arrows) and man-made return ditches that may not lend themselves to flow-accumulation algorithms. Also, there are locations where siphons are used to "cross" natural tributaries without interacting with them (orange arrows). It'd be great if landlab could add functionality for processing predefined linework with an under-lying model grid like what I've described/shown?  I could provide example .shp files if that'd be helpful. 
![canal_network](https://user-images.githubusercontent.com/3236576/98738429-84635d80-235c-11eb-84ed-5abf659451b2.png)

**Comment by kbarnhart** [comment]
@emorway-usgs Thanks for your inquiry. Landlab does not have this capability, though we always welcome community contributions. 

In theory, it would not be difficult to read in a shapefile that represents drainage ditches and use it to modify the flow direction data structures used by components such as the Landlab FlowAccumulator. Presumably these shapefiles contain metadata that indicate the direction of flow along each segment. This would allow you do simulate surface water flow influenced by these drainage features within Landlab. 

Presumably one could then export the Landlab flow direction data structures into the MODFLOW srf format. However, I'm less sure of this, not being familiar with this format. 

If you have other follow up questions, feel free to post them here.
