### ISSUE TITLE
FlowAccumulator needs to run the depression finder even if no pits are present. 

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1276]
Investigating TerrainBento/terrainbento/issues/156 I've found that the divide nodes get labeled as flooded, and thus, when erode_flooded_nodes is set to False, they turn into pinnacles. 

This seemed pretty odd to me, until I looked at the change history of the FlowAccumulator. In #1210 I saw that re-running the depression finder only occurs when pits are present. 

```python
if update_depression_finder and self.pits_present():
                     self._depression_finder.update()
```
This was probably meant to save time, but it means that if there are no pits, but there are flooded nodes, those flooded nodes don't get re-labeled. Because all of the stream power components can turn on/off erosion on flooded nodes depending on user specification, getting those flooded nodes re-labeled is important. Removing `and self.pits_present()` has no (local) impact on Landlab tests. ~Terrainbento tests are in progress (they take 1 hour), but many that were failing are now passing. I suspect they will all pass and will update this in the morning.~ Removing this line completely addresses the issue in Terrainbento (all tests pass with this line modified).

@gregtucker 

MWE 
```python
from landlab import RasterModelGrid
from landlab.components import FlowAccumulator, FastscapeEroder
from landlab.components.depression_finder.lake_mapper import _FLOODED

import matplotlib.pylab as plt

grid = RasterModelGrid((3, 21), 100)
grid.set_closed_boundaries_at_grid_edges(False, True, False, True)
z = grid.add_zeros("topographic__elevation", at="node")

fa = FlowAccumulator(
    grid, 
    depression_finder="DepressionFinderAndRouter", 
    routing='D4')
sp = FastscapeEroder(grid, K_sp=0.001, erode_flooded_nodes=False)

for i in range(10):
    fa.run_one_step()
    sp.run_one_step(2000)
    z[grid.core_nodes] += 10
    
    where_flooded = fa.depression_finder.flood_status == _FLOODED
    
    plt.plot(grid.x_of_node[grid.core_nodes], z[grid.core_nodes])
    plt.plot(grid.x_of_node[where_flooded], z[where_flooded], "ko")
```
<img width="396" alt="Screen Shot 2021-02-23 at 8 52 40 PM" src="https://user-images.githubusercontent.com/6589339/108945014-14ca6300-7619-11eb-8851-abeb8045e4fa.png">

**Comment by gregtucker** [comment]
IIRC the idea here was to avoid running the full algorithm in LakeMapperBarnes if there was no need. LMB and friends are much faster than DepressionFinderAndRouter if pits are present, but on the other hand DFAR is lightning fast if there aren't any pits because it doesn't do anything.

**Comment by kbarnhart** [comment]
It makes sense that this would be why the pits flag was there. But checking the pits flag is insufficient to ID whether depression finding should get run again if a user uses `erode_flooded_nodes=False`

Easy, slightly better than the initial change in #1277, might be to make the logic be:
if there are no pits AND all nodes have flood status code of _UNFLOODED.

I can check whether this addresses the issue in terrainbento and the MWE.
