### ISSUE TITLE
Include docs requirements in dev environment

### ISSUE THREAD

**Issue by mdpiper** [landlab/landlab#1289]
This is a request to add `requirements-docs.txt` to `environment-dev.yml`.

While using the dev environment to work with the LL source, I wanted to update corresponding documentation. I was surprised when the docs didn't build because sphinx wasn't installed in the environment.

**Comment by mdpiper** [comment]
(Give me the 👍 and I can quickly fix this.)

**Comment by gregtucker** [comment]
👍
