### ISSUE TITLE
Documentation about building wheels

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#131]
Right now @mcflugen is the only one that knows how to build landlab wheels. Although it's good job security for him, it would be better if everyone on the team could build new wheels for the supported platforms and Python versions. We need documentation for this.

**Comment by nicgaspar** [comment]
I’m pretty sure mcflugen already has plenty of job security!

**Comment by mcflugen** [comment]
Thanks, @nicgaspar!

Fixed with #137.
