### ISSUE TITLE
issue with load_grid()?

### ISSUE THREAD

**Issue by hjgray10** [landlab/landlab#1318]
Hi all,

I accidentally updated my landlab install when installing/updating a conda package for another project. Now when my code executes load_grid(), I get the following error:

Traceback (most recent call last):

  File "C:\Users\hgray\OneDrive - DOI\Gray_PortaOSL-ColluvialWedges\Manuscript\LongForm\Figures\Soil Sensititivity\Finalized Results2\CW_Model_V5_graphing_V2.py", line 225, in <module>
    grid_for_plotting = load_grid(grid_file_name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\landlab\io\native_landlab.py", line 101, in load_grid
    loaded_grid = pickle.load(file_like)

AttributeError: Can't get attribute 'PandasIndexAdapter' on <module 'xarray.core.indexing' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\xarray\\core\\indexing.py'>

Admittedly, the docstring for load_grid() cautions that future versions of landlab may break it and I should be using netcdf files. All of my model results from a parameter space exploration are stored in native .grid files so it would save me a lot of time if I didn't have to re-run them all to save the same results in netcdf. 

Thanks!!!

**Comment by SiccarPoint** [comment]
Hi Harrison! As a short-term fix, you should be able to roll back your LL version in both `pip` and `conda` by specifying it in update/upgrade. Though, if you don't know when you last updated/what the version was, some trial and error may be needed to figure the version out. You may also be able to persuade your package manager to tell you what it did, but I'm not sure if you can/how.

`pickle` is very sensitive to the underlying code. If the grid code changes at all, your pickles will always break. Which is annoying.

**Comment by hjgray10** [comment]
Awesome. Ok Thanks!!! I was able to do the rollback, but had issues with something deep trying to import from __future__ when I think it was already released and thus not in __future__ anymore (ha!). 

Luckily, I had the prior landlab version installed on a laptop and was able to import the native files  and rewrite them as netcdf. Thanks anyway for the help!
