### ISSUE TITLE
Use of keywords vmin and vmax in imshow_node_grid

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#132]
I'd like to be able to control the color range in imshow. The matplotlib documentation claims that one can do this with the vmin and vmax keywords. However, when these are passed to imshow_node_grid, the following results:

  File "/Users/gtucker/Documents/Papers/_InProgress/CellLab-CTS/Models/turbulent_suspension_with_settling_and_bleaching.py", line 362, in go
    imshow_node_grid(self.grid, 'osl_display', vmin=0.0, vmax=2.0)

  File "/Users/gtucker/Dev/Landlab/landlab/landlab/plot/imshow.py", line 76, in imshow_node_grid
    myimage = _imshow_grid_values(grid, data, **kwds)

TypeError: _imshow_grid_values() got an unexpected keyword argument 'vmax'

Shouldn't the keywords simply be passed on via **kwds?

**Comment by SiccarPoint** [comment]
Error in the docs; I'll fix it.

You actually want to use the keyword limits=(vmin, vmax) to set these, as described (correctly) in the docstring for imshow_node_grid.

**Comment by SiccarPoint** [comment]
imshow_node_grid now happily takes vmin and vmax as keywords, as alternatives to the existing kwd limits. Note this also means you can now also readily specify either limit alone, per imshow proper.
