### ISSUE TITLE
Broken doctest on Windows and Python 3

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#133]
There is one failing doctest on Windows using Python 3. The broken test is for the `ModelGrid` method, `_assign_boundary_nodes_to_grid_sides`. It's a pretty minor failure that doesn't really matter but would be nice to fix up.

```
Failed example:
    l
Expected:
    array([ 7, 12,  3])
Got:
    array([ 7, 12,  3], dtype=int32)
```

**Comment by gregtucker** [comment]
Is the dtype platform-dependent? If so, is there a way to report the array contents without specifying what flavor of int it contains?

**Comment by mcflugen** [comment]
Yes, the dtype of arrays is platform-dependent. Depending on the platform (and, it seems, the Python version) integer arrays are not always created with their dtype being the native integer type.

We could certainly make the doctest pass by converting the array to a particular flavor of integer. However, I think that's really just masking an underlying problem. That is, sometimes our element ID arrays are 32-bit integers and sometimes they're 64-bit integers. In addition, modifying the doctest in this way would make for a somewhat confusing example.

Have a look at the doctest for `ModelGrid.boundary_nodes` in the `mcflugen/fix-issue-133` branch. The first test, which uses `RasterModelGrid` passes while the second test, which uses `HexModelGrid`, fails. That is, `RasterModelGrid.boundary_nodes` is an array of `int`, while `HexModelGrid.boundary_nodes` is an array of `int32` (on Python 3 for Windows, anyway). Somewhere in `VoronoiDelaunayGrid` or `HexModelGrid` the array of boundary nodes is being set as `int32`.

**Comment by mdpiper** [comment]
Verified that docs are passing.
