### ISSUE TITLE
Do we currently have support for netCDF and/or VTK output for hex or unstructured grids?

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#134]

**Comment by SiccarPoint** [comment]
I don't believe so. This was the main motivation for my introduction of a "landlab native" save method, which uses pickle.

See landlab.io.native_landlab:
https://github.com/landlab/landlab/blob/master/landlab/io/native_landlab.py

**Comment by mcflugen** [comment]
That is correct. However, I think we have all the tools required to write unstructured grids to VTK (and might already even work for writing). For netCDF, we should probably look to the UGRID standard for unstructured grids (https://github.com/ugrid-conventions/ugrid-conventions).

As @SiccarPoint says, we can use pickles for storing grids. Advantages are:
* Easy to implement
* One-liners to read and write grids
* We store everything about the grid so we're sure to get the exact same grid that we wrote. This is great for checkpointing long simulations or restarting simulations after some spin-up period, for instance.

Some disadvantages:
* Not backward compatible. If we modify `ModelGrid` even slightly we won't be able to read an old pickle file into the new grid.
* Other, non-Python, software won't be able to easily read our native-landlab files.
* We're storing everything (big files, slow) about the grid. Even stuff that can be regenerated (like neighbor node arrays, for instance).

So, I guess I'm saying that we really should have both.

**Comment by SiccarPoint** [comment]
Agreed. IIRC I noted much of this in the docstrings for my pickling methods.

We certainly need both! I just added pickling first as I don’t understand these open source formats well enough to do it myself, and better some way to save irregular grids than none at all…

D
