### ISSUE TITLE
Flow director issue when providing LakeMapperBarnes to FlowAccumulator

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1341]
Until recently, I was able to provide a string or instantiated class of LakeMapperBarnes to a FlowAccumulator where I have also specified that the flow_director should be 'D8'. Since recent pull requests to master (I'm not sure which one, I'm sorry!) I receive an error saying that there is an incompatibility because the depression finder method is D4. Of course LakeMapperBarnese has a D8 option, but it seems to not be selected. This makes it very difficult or impossible to use LMB in this fashion with D8 flow directors, as near as I can tell. 

I have two questions: when I did not receive this error before, was the FlowAccumulator actually running a D4 instance of LMB? Second, if that is the case, can we make a change such that the director of the depression finder matches the director given to the flow accumulator? 

Minimal example is here, traceback of the error below. 
```
import numpy as np
from landlab import RasterModelGrid
from landlab.components import (
    FlowAccumulator,
    LakeMapperBarnes,
    )

grid = RasterModelGrid((10,10), xy_spacing=10)
z = grid.add_zeros('node', 'topographic__elevation')
z[:] = 0.1*np.random.rand(len(z))
fa = FlowAccumulator(grid, surface='topographic__elevation', flow_director='D8', depression_finder='LakeMapperBarnes')
```

![image](https://user-images.githubusercontent.com/45630470/133671655-b5f0868e-5be1-4fc6-a19c-74596278a40b.png)

Version is Master at `e59cdb8ee9f15ade796dd03f3c947baaa3d59e3c`

**Comment by gregtucker** [comment]
@DavidLitwin this was a modification I wrote to handle an error-detection problem in `FlowAccumulator` (it had been written assuming the user passed a `DepressionFinderAndRouter`, and that sometimes caused it to raise inappropriate errors when using `LakeMapperBarnes` instead).

You are correct, `LakeMapperBarnes` defaults to D4.

The fix for your code above is easy: just add the `LakeMapperBarnes` keyword argument `method='D8'`:

```
fa = FlowAccumulator(
    grid,
    surface='topographic__elevation',
    flow_director='D8',
    depression_finder='LakeMapperBarnes',
    method='D8'
)
```

**Comment by DavidLitwin** [comment]
Ah this is great. I didn't realize I could provide method like that. Thanks!
