### ISSUE TITLE
Better handling of fixed_gradient BCs

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#135]
I've been playing with the set_fixed_gradient_Cs_at_grid_edges() method I hade ages ago. Basically, it sucks (as also noted by Jordan last week).

Need to replace it with a mechanism based around links, not nodes.

**Comment by jadams15** [comment]
Thoughts on fixed gradient conditions: we *may* want to assign fixed gradient condition to links between a closed boundary node and a perimeter node. I've started playing around with this idea, but nothing concrete yet. This would be especially important in equations like de Almeida where you need to look at neighbor links and we want the "boundary" link neighbors to have a fixed gradient. In the case of closed boundaries, the "boundary" link would technically be inactive, which wouldn't help for solving de Almeida. Another way to think about this: flux goes into the perimeter nodes but is unable to travel into the closed nodes. This might work better with fixed value nodes... Open to suggestions!!!

**Comment by jadams15** [comment]
We've successfully implemented new fixed_link boundary conditions into the master branch. For a raster this is "set_fixed_link_boundaries_at_grid_edges". In base.py there is a new function called "set_nodata_nodes_to_fixed_gradient". Old stuff is still in there ("set_fixed_gradient_boundaries") but is noted as deprecated, per version 0.29.
