### ISSUE TITLE
lateral_erosion component not resetting and division by zero error

### ISSUE THREAD

**Issue by josh-wolpert** [landlab/landlab#1352]
Hello,

I'm using the lateral_erosion component, and I've noticed pits developing after a node meets the condition for a lateral erosion event. I think self._dzlat needs to be reset each time run_one_step is called. Since self._dzlat doesn't reset, once a node experiences lateral erosion, it will continue to erode by lateral erosion at every subsequent timestep. Below is the relevant code from the component (lines 520-526):

                    if vol_lat[lat_node] >= voldiff:
                         self._dzlat[lat_node] = z[flowdirs[i]] - z[lat_node]  # -0.001
                        # after the lateral node is eroded, reset its volume eroded to
                        # zero
                        vol_lat[lat_node] = 0.0
        # combine vertical and lateral erosion.
        dz = dzdt + self._dzlat

Even when the condition for lateral erosion is not met (line 520), a node continues to erode by lateral erosion (line 526).

I've also noticed division by zero errors coming from the angle_finder method in node_finder.py. I think this happens when current nodes (cn) have the same x or y coordinates as their donor (dn) or receiver (rn) nodes.

I've made minor modifications that I'll submit for your consideration in a pull request.

Best,
Josh

**Comment by gregtucker** [comment]
@josh-wolpert thank you for posting this issue and submitting a PR that fixes it!
