### ISSUE TITLE
Including field units with create_grid

### ISSUE THREAD

**Issue by alexmitchell** [landlab/landlab#1358]
I can't figure out how to include field units when creating a grid from a dictionary using landlab's `create_grid` function. Here is the minimum code to show the issue:
```python
from landlab import create_grid
params = {
        "RasterModelGrid": [
            {
                "shape": (5,7), "xy_spacing": (10,10),
            },
            {
                "fields": {
                    "node": {
                        "topographic__elevation": {
                            "constant": [{"value": 0.0}],
                        },
                    }
                },
            },
        ],
}

grid = create_grid(params)
print(grid.at_node.units)
```
The output will be:
`{'topographic__elevation': '?'}`

I want to add information about the units (e.g. `"units" : "m"`) somewhere within the `"topographic__elevation"` dictionary. However the `"topographic__elevation"` dictionary only accepts synthetic field functions and they do not accept units either.

I can manually set the units of a field after creating the grid, but it does not behave as expected:
```python
f_name = 'topographic__elevation'
print("Before:")
print(grid.at_node.units[f_name])
print(grid.field_units('node',f_name))

grid.at_node.units[f_name] = 'm'

print("After:")
print(grid.at_node.units[f_name])
print(grid.field_units('node',f_name))
```
Produces:
```
Before:
?
?
After:
m
?
```

Is there a "best way" to assign units to fields when creating grids from dictionaries or after a field already exists? If not, I think it might make the most sense to modify the `add_fields_from_dict` or `add_field_from_function` methods in landlab/grid/create.py to accept units. In other words, I would like the following to be a valid input dictionary:
```python
params = {
        "RasterModelGrid": [
            {
                "shape": (5,7), "xy_spacing": (10,10),
            },
            {
                "fields": {
                    "node": {
                        "topographic__elevation": {
                            "constant": [{"value": 0.0}],
                            "units" : 'm',
                        },
                    }
                },
            },
        ],
}
```

**Comment by mcflugen** [comment]
@alexmitchell Thank you for this. You are correct, you cannot set a field's units when using the `create_grid` function. I believe this is just an oversight and it should be easy to add that functionality. Using your example, I think the dictionary would look something like the following,
```python
params = {
    "RasterModelGrid": [
        {
            "shape": (5, 7),
            "xy_spacing": (10, 10),
        },
        {
            "fields": {
                "node": {
                    "topographic__elevation": {
                        "constant": [{"value": 0.0, "units": "m"}]
                    },
                }
            },
        },
    ],
}
```
The only difference in what you had is that here the units are included in the keywords for the *constant* function.

It should also be easy to add the ability to set the units after the field has been created.

I'll try to get a pull request together in the next few days that adds this functionality.

**Comment by alexmitchell** [comment]
Thanks!

Adding it to the synthetic function makes sense too. The only (minor) hangups I had about that was 1) that you'd have to change all the synthetic functions and 2) that people are supposed to be able to use multiple synthetic functions at the same time (e.g. a plane with some randomness added) so they might define the units for one and not the others in no particular order. I figured it would be (slightly) easier to catch the units before the synthetic functions are called. But again, these barely count as issues against adding units to the synthetic functions.

**Comment by mcflugen** [comment]
@alexmitchell Actually, I think I like your idea better.
