### ISSUE TITLE
How to test new module when landlab is already a site-package of the python interpreter?

### ISSUE THREAD

**Issue by pohleric** [landlab/landlab#1367]
Hello,
I have been playing around with the GroundwaterDupuitPercolator to have 2 instead of 1 layer. I am stuck on how to test it. I tried adding the module to the landlab components in my python environment; inside the component folder (the installed version using conda --> conda/env/.../landlab/mycomponentname/; I added an __init__.py in the new folder and added the name of the component in the __init__.py within the components folder (import and with the COMPONENTS list).

If I try to import the module it is not found though. I guess it is not the correct way. 

If I try to import the module within my local (not the environment) landlab-master folders I run into a name-space issue. "import" yields two options for importing landlab, but it will always choose the module from the installed package using conda and not my local folder. Before I do something that is anyways wrong, I would like to ask what would be the best way to import my component.

Many thanks in advance,
Eric

**Comment by mcflugen** [comment]
Hi @pohleric,

It sounds to me like you need to install *landlab* following the developer installation instructions. You can find instructions on how to do this in our [documentation](https://landlab.readthedocs.io/en/latest/development/install/install.html).

If you're using *conda*, which it sounds like you are, the following steps should do it,
1. Get the landlab source code. You can do this either by downloading a *.tar.gz* file from GitHub or cloning the *landlab* GitHub repository.
2. Create a conda environment to install *landlab* into, install *landlab*'s dependencies, and then install *landlab* (these commands should be run from the top-level folder of the *landlab* source code you just downloaded)
```bash
$ conda create -n landlab python=3.9
$ conda activate landlab
$ conda install --file=requirements.txt
$ pip install -e .
```
Now when you edit the code within this folder you should see your changes.

Please give that a try and let me know how it goes.

**Comment by pohleric** [comment]
Hi @mcflugen,
It seems to work with the instructions you provided. Many thanks,
Eric

**Comment by mcflugen** [comment]
@pohleric That's great to hear! Please let us know if you have any more questions.
