### ISSUE TITLE
Developer installation error

### ISSUE THREAD

**Issue by pullulation** [landlab/landlab#1381]
Hello,

I am trying to install landlab from source code using Anaconda on Windows. I followed the developer installation instructions.

When I run the command of  `conda env create --file=environment-dev.yml` , the process of creating new environment seems never end. I checked it and the `landlab_dev` virtual env do exist. So I tried mannually install the dependencies from the .txt file, however the error happens when I tried `pip install -r requirements.txt`

```
Collecting rasterio
  Using cached rasterio-1.2.10.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\anaconda3\envs\landlab_dev\python.exe' 'd:\anaconda3\envs\landlab_dev\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Bowen\AppData\Local\Temp\tmpt1u2vxwy'
       cwd: C:\Users\Bowen\AppData\Local\Temp\pip-install-9u58fg4v\rasterio_b8b6a822c73747c8a01a1422286af828
  Complete output (2 lines):
  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/44/5e/9f19e1e6fe980b59d8da8809f2e8f81eb7f0322c71914f077edcbcd9a110/rasterio-1.2.10.tar.gz#sha256=6062456047ba6494fe18bd0da98a383b6fad5306b16cd52a22e76c59172a2b5f (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'd:\anaconda3\envs\landlab_dev\python.exe' 'd:\anaconda3\envs\landlab_dev\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Bowen\AppData\Local\Temp\tmpt1u2vxwy' Check the logs for full command output.
```
I tried different python version (3.7, 3.8 and 3.9) but it did't work.

And when I run the command `pip install -r requirements-dev.txt `, the error is 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
markdown 3.3.6 requires importlib-metadata>=4.4; python_version < "3.10", but you have importlib-metadata 4.2.0 which is incompatible.
```

I upgraded `importlib-metadata` to `4.10.1`, then I got another error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flake8 4.0.1 requires importlib-metadata<4.3; python_version < "3.8", but you have importlib-metadata 4.10.1 which is incompatible.
```
It seems the `flake8` and `markdown` has different requirements on `importlib-metadata`

Any idea or advice on solving these two problems? 
Thanks in advance!

Bowen

**Comment by mcflugen** [comment]
@pullulation Thank you for the detailed description of your issue!

I believe you are having this problem because the *rasterio* package is not available for your environment from *PyPI* (i.e. through *pip*). *environment-dev.yml* is instructing *conda* to install  *rasterio* using *pip* but because it can't find it, it's trying to build it from source and is not able to, which is why it's taking so long.

Please try the following alternative way of installing *landlab*,
1. Remove your *landlab_dev* environment (`conda remove -n landlab_dev --all`)
2. Create a new environment `conda create -n landlab_dev python=3.9 -c conda-forge`
2. Install *landlab*'s requirements from *conda-forge* (rather than *PyPI*) `conda install --file=requirements.txt -c conda-forge`

The *landlab_dev* environment should now have all of the requirements for installing *landlab*. Please let me know how it goes.

My apologies for your trouble. I'm trying to fix this issue, along with some other related installation issues (including documentation), in #1379. I'm hoping to have it straightened out today.

**Comment by pullulation** [comment]
> @pullulation Thank you for the detailed description of your issue!
> 
> I believe you are having this problem because the _rasterio_ package is not available for your environment from _PyPI_ (i.e. through _pip_). _environment-dev.yml_ is instructing _conda_ to install _rasterio_ using _pip_ but because it can't find it, it's trying to build it from source and is not able to, which is why it's taking so long.
> 
> Please try the following alternative way of installing _landlab_,
> 
> 1. Remove your _landlab_dev_ environment (`conda remove -n landlab_dev --all`)
> 2. Create a new environment `conda create -n landlab_dev python=3.9 -c conda-forge`
> 3. Install _landlab_'s requirements from _conda-forge_ (rather than _PyPI_) `conda install --file=requirements.txt -c conda-forge`
> 
> The _landlab_dev_ environment should now have all of the requirements for installing _landlab_. Please let me know how it goes.
> 
> My apologies for your trouble. I'm trying to fix this issue, along with some other related installation issues (including documentation), in #1379. I'm hoping to have it straightened out today.

**Comment by pullulation** [comment]
@mcflugen Thanks for your prompt reply. It worked perfectly for me!

**Comment by mcflugen** [comment]
Excellent! Happy to hear to got it working!

**Comment by mcflugen** [comment]
@pullulation Could you please provide a link to the installation instructions you followed? There are installation instructions in several places and I want to make sure I've updated the ones you followed. Thanks!

**Comment by pullulation** [comment]
No problem. I followed this instruction [https://landlab.readthedocs.io/en/master/development/install/install.html#install](url)

**Comment by mcflugen** [comment]
Thanks!
