### ISSUE TITLE
Trouble re-compiling landlab on Windows after Cython updates

### ISSUE THREAD

**Issue by shelbyahrendt** [landlab/landlab#1382]
I recently pulled some Landlab changes, and subsequently ran into an error associated with 'cfuncs.pyx' when I import landlab. This has happened in the past, and has been fixed by running `pip install -e .` in the top level landlab folder within my landlab_dev environment. When I ran it this time, I had a 'wheel build error' when trying to build the wheel for rasterio--it seemed like the setup cycled through multiple versions of rasterio but continually failed with the error 'Building on Windows requires extra options to setup.py to locate GDAL files' and 'Provide a path to gdal-config using a GDAL_CONFIG environment variable' (a snip of one of these errors is below)
![image](https://user-images.githubusercontent.com/36043125/150324246-fcbad5f8-36d1-4b49-ba3b-83169396a540.png)

Since I have been using a developer install, I tried troubleshooting by uninstalling/reinstalling landlab using the [Additional Issues directions](https://landlab.readthedocs.io/en/master/development/install/updating.html#additional-issues). After uninstalling landlab, running `$python setup.py develop -u` and then `$conda env update landlab_dev environment-dev.yml ` I once again recieved an error while 'building the wheel' for rasterio, with the note 'Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.'

I am having difficulty finding this information in the README.rst located in the top level landlab folder. Is this something others have run into while trying to update landlab on a Windows machine?

**Comment by mcflugen** [comment]
@shelbyahrendt Please have a look at #1381 and #1378 to see if that solves your problem. It looks like your issue is that *pip* is trying to install *bmi-topography*, which requires *rasterio*, which is not available for your platform from *PyPI* (*bmi-topography* was mistakenly added to the requirements file). Likely, the instructions in #1381 should fix your problem. Please try that and let me know how it goes.

**Comment by shelbyahrendt** [comment]
@mcflugen The instructions in #1381 also seemed to work for me! When reinstalling landlab, I additionally pulled the most recent changes from #1379 and followed the [updated instructions](https://landlab.readthedocs.io/en/master/development/install/install.html) in case there were further edits to the setup/requirement files there.
