### ISSUE TITLE
Is there a way to temporarily turn off the landlab tests while developing on a fork?

### ISSUE THREAD

**Issue by shelbyahrendt** [landlab/landlab#1387]
I noticed that all the landlab tests now automatically run whenever I push changes to a fork of landlab. If I am working on something that I know is still a little messy (and I know will fail), but I just want to commit my changes for peace of mind is there a way to pause the automatic tests?

If it makes sense for best practice to run the tests with every commit, then I will close this, but I noticed that it sometimes takes awhile for the tests to run; is there is an option to toggle them off and save whatever it costs to run them?

**Comment by mcflugen** [comment]
@shelbyahrendt If you are pushing changes that are a work in progress and, particularly, if you know the tests will fail or you aren't interested in the results, you should tell GitHub to skip the tests.

There are a [number of ways to do this](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) but, basically, you just need to include something like `[skip ci]` in the commit message.

**Comment by shelbyahrendt** [comment]
Thank you @mcflugen!
