### ISSUE TITLE
looking for a simple method to get or set and individual "cell", or the central value

### ISSUE THREAD

**Issue by RichardEllicott** [landlab/landlab#1393]
Hi

I've found the product easy to understand but am a little lost in the reference material

I have created an object? from RasterModelGrid (i'm not sure what this is, some sort of structure is returned)

i can actually fill it with basic noise etc all at once

how can get and set a cell's (ed: sorry i think i may mean node here, am unsure) "topographic__elevation" elevation individually? i want to do this is then i can make a simple in and out process with Pillow, take what i do and export heightmaps

Thanks

**Comment by gregtucker** [comment]
Hi @RichardEllicott - 
Please take a look at the tutorials, which I think will answer your questions. If you have cloned a copy of the repo, you can find them (Jupyter Notebooks) in the folder landlab/notebooks. I recommend starting with `welcome.ipynb`.

**Comment by RichardEllicott** [comment]
thanks i have found an into tutorial from that link
