### ISSUE TITLE
get_link/active_link_connecting_node_pair() broken?

### ISSUE THREAD

**Issue by jadams15** [landlab/landlab#140]
Using get_link_connecting_node_pair() and get_active_link_connecting_node_pair() both seem to be broken in RasterModelGrid...

Example behavior....

>>> mg = RasterModelGrid(4, 5)
>>> mg.get_active_link_connecting_node_pair(6, 7) 
array([10])  

This should return ID of 20 per our new numbering scheme. so this is just outdated (old numbering scheme). We already know about this problem but it needs to be fixed. The REAL problem is below:

>>> mg.get_link_connecting_node_pair(6, 7)
array([], dtype=int64)

So now NO link is returned between nodes 6 and 7. It should still return ID of 20. I think this is an issue with the numpy function intersect1d. Changing the flag in assume_unique to 'False' fixes this behavior. Anyway, this might be a good time to try to  speed these up. I don't know how widely used they are, so wanted to share this info.

**Comment by mcflugen** [comment]
This function should be removed. Since we no longer have different numbering schemes for active links and links, this function is the same as `get_link_connecting_node_pair`. Right?

**Comment by SiccarPoint** [comment]
I’m fairly sure I also concluded these where really quite broken recently. Need removing/replacing.

IIRC they’re also reeeeeeally badly written (i.e., super inefficient).

Am I right in thinking get_link_connecting_node_pair is only for raster though? We need generalised methods too…

D

**Comment by jadams15** [comment]
well, I think there should be a case where, if the link is inactive it SHOULD return an empty array (get_active_link_connecting_node_pair), while if you want all links (active and inactive) it would be get_link_connecting_node_pair. 

That being said, yes they are broken. I raised this issue in case they are used anywhere else in the code. I want to go in and hack them up and make them faster. I will likely do so in the link_status branch.

**Comment by mcflugen** [comment]
`get_link_connecting_node_pair` seems pretty fast. It also seems general and, if so, should be moved to `ModelGrid`. I imagine a slightly faster version could, if necessary, be written for a raster grid.

`get_link_connecting_node_pair` looks good to me. @jadams15, you think it's broken? It definitely needs a better docstring and some example doctests but it seems like it should return the correct value.

**Comment by mcflugen** [comment]
Sorry. Yes. Definitely broken. I'll fix it.

**Comment by jadams15** [comment]
OK. Thanks Eric! I'm happy to help work on these as well. I wanted everyone to be aware of the issue in case it was widely used (I couldn't find many instances on the master branch but there could be individual problems).

**Comment by mcflugen** [comment]
I'm not sure if I fixed the problem to your satisfaction or not however `get_link_connecting_node_pair` at least works now. There are some significant changes to its behavior:
* `get_link_connecting_node_pair` only operates on a single node pair. That is, you can't get the links connecting a bunch of node pairs.
* If nodes aren't connected or are the same node, raises `ValueError`.
* The return value is an `int` not an array.
* If you only want active links, you'll have to check if the returned link is active yourself.
* `get_active_link_connecting_node_pair` is now gone.

**Comment by jadams15** [comment]
That sounds like exactly what I needed! Thank you! I think in the future there may be a need for a function that can handles arrays of nodes (so array of node_a and array of node_b) but I can think on that - the functions we had now were a little slow to do anything fancy like that. 

The only reason I was lobbying for keeping get_active_link_connecting_node_pair was so that if there was automatic way to address the second-last bullet point. But if we aren't returning an array, I guess it would have to return BAD_INDEX_VALUE? 

Because Dan and I have been working on adding link BC handling, I could see having a third option too: get_fixed_link_connecting_node_pair(). Again though, I am not sure when they would be used, just that it might be good to keep uniformity across the board. At any rate, if I decide we need it, I can just add it myself. Thanks again for handling this!!
