### ISSUE TITLE
Height Above Nearest Drainage

### ISSUE THREAD

**Issue by rishav-karanjit** [landlab/landlab#1411]
Can we use landlab to calculate Height Above Nearest Drainage using TIFF file?

**Comment by gregtucker** [comment]
The documentation for the `HeightAboveDrainageCalculator`:

https://landlab.readthedocs.io/en/latest/reference/components/hand_calculator.html

Uses a simple DEM generated as a RasterModelGrid field. So the question is how to create a RasterModelGrid from a TIFF file. I don't think we currently have a reader for TIFF files. Some options to consider:

- Convert your data to an ESRI Ascii Grid format file, and read it using `read_esri_ascii`
- Use the [CSDMS GeoTiff Data Component](https://bmi-geotiff.readthedocs.io/en/latest/) to read your TIFF file, and copy it into the `topographic__elevation` field of a RasterModelGrid that has the same dimensions.

**Comment by kbarnhart** [comment]
rasterio is another good option for reading tifs into numpy arrays

https://rasterio.readthedocs.io/en/latest/index.html

**Comment by kbarnhart** [comment]
@rishav-karanjit I'd recommend you start by working through the tutorials we have created to help new users.

https://landlab.readthedocs.io/en/master/user_guide/tutorials.html

Then look through the components to determine what might be appropriate for delineating channels in your use case. Likely the FlowAccumulator will be suitable for your needs. 

https://landlab.readthedocs.io/en/master/reference/components/index.html
