### ISSUE TITLE
New implementation of the compilation of the cython files with cythonize

### ISSUE THREAD

**Issue by sebastien-lenard** [landlab/landlab#1467]
Since #869, landlab install collects the cython files and compiles the cython extensions in executables. This is done with the help of the **setup.py** script. Files are compiled in c-executables by including the numpy library and without the "new" cython function "cythonize()". The setup script works well but remains limited, whatever its use in standard or dev mode. 

I propose a major update of this script, with the double aim to ease its parametering at the global level and to specify some compilation instructions at the cython file level. For this, a new setup_cython.yml configuration file will be designed. The template of the setup_xxx.yml configuration file at the cython file level will be also supplied.

This implementation adds new functionalities at the **global** (cython) level:

- to force the recompilation of all files, whatever the previous compilation date and edition date of the cython files.
- to restrict the directories where to look the extensions: e.g. to landlab and test directories and sub.
- to exclude some directories according to the text within them: e.g. .ipynb_checkpoints
- to exclude some files according to the text within their filename
- to parameter the build of the extensions with cythonize arguments, which include:
- - the compilation of the extensions using Python 3 (Python 2 is the default today)

And at the **file** level:
- to include c or cpp file codes
- to compile in c++ (not working when include c++ libraries without the cythonize function)
- to add extra c/c++ compilation arguments, such as -fopenmp which opens the avenue to parallelization on several computer cores in Landlab components.

**Comment by sebastien-lenard** [comment]
@mdpiper, using extra-compilation options for the c/c++ compiler (as described in the specs of this issue) is a bit tricky. There are two famous compilers, gcc and clang, and their arguments can be slightly different. For instance, gcc can accept -fopenmp (to enable multithreading). But clang rejects this argument alone. One solution is to specify the complementary argument -Xpreprocessor, which yields the string of arguments "-Xpreprocessor -fopenmp". This string works both for gcc and clang.

Additional remark: on the Jupyterhub, gcc is the compiler, while on the github action platform, clang is the compiler. It might be interesting in the future to have clang rather than gcc on the Jupyterhub.

**Comment by mdpiper** [comment]
@sebastien-lenard I agree: this will be tricky, there's no way around it. I'm biased--I like to use the [conda compilers.](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html) But not everyone uses conda, so this isn't a solution.

The gcc on the Hub is just what came with the underlying Linux AMI. I can also install clang (or other compilers) on the AMI, although again, I'm a fan of the conda compilers, and since we use conda intrinsically on the Hub, I'd lean toward installing them.

**Comment by sebastien-lenard** [comment]
Compared to the initial specs, only a very limited modification of setup.py has been pushed.

Implemented:
- The cython files are now compiled with the "new" cython function "cythonize()".
- Compilation is done using Python 3 and embedding function signatures in C code.
- Compilation is done across the landlab + tests directories (and subdirectories).
- Compilation instructions can be added at the top of the .pyx and .pxd files (see landlab/components/flow_router/ext/single_flow/priority_routing/breach.pyx and .pxd), especially to 
               - to include c or cpp file codes
               - to compile in c++ of a certain version (not working when include c++ libraries without the cythonize function)
               - to compile with -fopenmp which opens the avenue to parallelization on several computer cores in Landlab components.

Not implemented:
- The yml conf files have not been implemented.
- There's still a problem with .ipynb_checkpoints directories (see #1474).
- There's still a problem with forced recompilation of all files done every time we pip install -e. or python setup.py.
