### ISSUE TITLE
Is FlowRouter.route_flow working properly?

### ISSUE THREAD

**Issue by saisiddu** [landlab/landlab#147]
Please check the attached code. 

Code:
import numpy as np
from landlab import RasterModelGrid as rmg
from landlab.components.flow_routing.route_flow_dn import FlowRouter

grid = rmg(4,5,1.)
z = np.array([5., 0., 5., 5., 5.,
                 5., 1., 2., 2.5, 5.,
                 5., 3., 4., 3., 5.,
                 5., 5., 5., 5., 5.])
				 
grid['node']['topographic__elevation'] = z
grid.set_closed_boundaries_at_grid_edges(True, True, True, True)
grid.node_status[1]=0  # Setting drainage point for the eg.1 basin
fr = FlowRouter(grid)
fr.route_flow()
r = grid.at_node['flow_receiver']

Current answer:
r = array([ 0,  1,  2,  3,  4,  5,  6,  1,  7,  9, 10,  6,  6,  7, 14, 15, 16,
       17, 18, 19])
Correct answer ??
r_correct = array([ 0,  1,  2,  3,  4,  5,  1,  1,  7,  9, 10,  6,  6,  7, 14, 15, 16,
      17, 18, 19])

Comment: Receiver of node# 6 should be node# 1 (isn't it?)

**Comment by saisiddu** [comment]
Probably, the issue is with the recognition of core and boundary nodes.

**Comment by jadams15** [comment]
So, based on your e-mails, it sounds like you set a perimeter node to a core node status? I thought we had all agreed that all perimeter nodes MUST be boundary nodes of some kind. I believe the standard is fixed_value_boundary (node_status==1). Someone, please correct me if I'm wrong... but if I'm understanding everything correctly that could be part of this problem? 

If we do allow for boundaries to become core_nodes (I'm still not convinced of this), Sai, you may need to update the node and link status list after making that change. It's in base.py, something like "update node and link status". I know it calls _reset_link_status_list(). This may not work, for the reason I listed above...

**Comment by SiccarPoint** [comment]
I've figured out the problem. It's that you can't do a node status re-assignment like you are, i..e, 

>>> mg.node_status[1] = 1  #As Jordan notes, this can't possibly be a 0, as it's a boundary node

...without then also calling:

>>>mg.update_links_nodes_cells_to_new_BCs()

This is because you're only resetting the BC status of the nodes right now - so the links are still closed leading into the node until you call this. We have notes to this effect somewhere in the documentation (...tutorials???), but agree it's not clear. Note that all the formal BC interaction *methods* already call this internally, but by using a slice, you miss it.

Your problem will go away if you call that function after opening the node.

In an ideal world we should overload the [] operator so it can detect if resetting the BCs, and call the helper function automatically. But I don't actually know how to do this/if we can.

**Comment by saisiddu** [comment]
Thank you guys! I kind of guessed that the issue is with node/link status.

Here is another question: How do you assign a basin exit (to collect the output flow from a basin)?

**Comment by jadams15** [comment]
I would assign a fixed value boundary to your outlet. You can still update that boundary value dynamically in the code.

**Comment by saisiddu** [comment]
But, if I do that, flow router doesn't consider this node as a core node and hence wouldn't drain to it. Am I correct in saying that? 

I want to drain a basin to the outlet node. How do I get flow router to recognize this basin outlet as a node to consider draining to?

**Comment by nicgaspar** [comment]
It needs to be an open boundary node.

**Comment by jadams15** [comment]
we don't have a "open boundary" status, I don't think? isn't that what fixed_value is?

**Comment by jadams15** [comment]
(At least in our case...)

**Comment by SiccarPoint** [comment]
No, that’s not right. BC types 0-3 are all “open”, so can receive flow. Only closed nodes (4) can’t.

Core nodes simply means “not boundary”.

**Comment by saisiddu** [comment]
So, will flow_router (route_flow_dn.FlowRouter.route_flow) recognize an open boundary node (0-3) on the boundary (perimeter) and drain to it?

**Comment by jadams15** [comment]
Ok. I understand now. I am pretty much exclusively using node BC 2 now, but don't allow flow outside of my core nodes. I set up my boundary conditions such that my outlet *is* a core node... thus my confusion.

**Comment by saisiddu** [comment]
So, should we be able to use inbuilt system, to label all perimeter nodes as boundary nodes, to our advantage? I think, we should only convert one of the boundary nodes to an open node to drain to it. Isn't that right?

**Comment by SiccarPoint** [comment]
Yes. Your code was exactly right, you just need to add

>grid.node_status[1]=1 # Setting draining node as fixed elev
>grid.update_links_nodes_cells_to_new_BCs()

in place of your line

>grid.node_status[1]=0 # Setting drainage point for the eg.1 basin

I'm 99% sure that if you aren't getting draining to node types 0-3, you are probably doing something else unexpected. Will need to see code again.

**Comment by SiccarPoint** [comment]
(should emphasise, I'm thinking how to remove the need for calls to mg.update...() as a separate issue now)

**Comment by saisiddu** [comment]
Thanks Dan! I will try the above fix.
