### ISSUE TITLE
Github workflows: failing notebooks due to http 401 error linked to bmi_topography calls

### ISSUE THREAD

**Issue by sebastien-lenard** [landlab/landlab#1470]
Presently, the github workflows include testing of all notebooks, each time we update a pull-request by pushing a commit. Some notebooks include http calls with pseudo (?) user-id key having a limited number of requests per day. This is notably the case of the flow_direction_and_accumulation/PriorityFlood_realDEMs.ipynb with calls through the bmi topography library. When too many tests call bmi-topography in 24 h, the notebook fails with http 401 error (more details below).

There are several solutions not to exceed the number of calls to the bmi topography and all of them require some thinking before implementation:
- increase the number of allowed requests for the user-id
- limit the number of notebooks which include bmi topography. This probably requires finding and using a server where to store the DEMs of the notebooks which don't use the bmi topography.
- put a condition on the testing of the notebooks, which would depend on the success of all the other jobs (docs, black, flake8, pytests).

 @mdpiper @mcflugen @BCampforts

Error details:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Input In [4], in <cell line: 2>()
      1 # Download or reload topo data with given buffer
----> 2 dim_x, dim_y, cells, grid_LL, z_LL, dem = get_topo(0.05)
      4 fa_LL = FlowAccumulator(
      5     grid_LL, flow_director="D8", depression_finder="DepressionFinderAndRouter"
      6 )
      7 fa_LL.run_one_step()

Input In [2], in get_topo(buffer, north, south, east, west)
      8 params["cache_dir"] = Path.cwd()
      9 dem = Topography(**params)
---> 10 name = dem.fetch()
     11 props = dem.load()
     12 dim_x = props.sizes["x"]

File /usr/local/miniconda/envs/test/lib/python3.9/site-packages/bmi_topography/topography.py:156, in Topography.fetch(self)
    150         msg = (
    151             "It looks like you are using a user-supplied key. This error may mean "
    152             "that your key is out of date or there is a typo in the supplied key. "
    153             f"(source={self._api_key.source})"
    154         )
    155     response.reason = os.linesep.join([response.reason, "", msg, ""])
--> 156 response.raise_for_status()
    158 with fname.open("wb") as fp:
    159     for chunk in response.iter_content(chunk_size=None):

File /usr/local/miniconda/envs/test/lib/python3.9/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: 401

**Comment by mdpiper** [comment]
We could try [disabling/enabling](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) the *test-notebooks* workflow. I'm not sure about permissions, though.

**Comment by mdpiper** [comment]
Another option is we could [store](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) the data downloaded from OpenTopography in the *test-notebooks* workflow. *bmi-topography* will check its cache directory first before attempting to download data.

**Comment by mcflugen** [comment]
I believe these notebook tests are only failing on *landlab* forks. When pull requests are initiated from the main *landlab* repository, the notebooks use a token that doesn't have this limitation (it's my personal token). The token is set as part of the notebook testing workflow through an [environment variable](https://github.com/landlab/landlab/blob/5c93da5f4519476a6ea62d5faf12b7e11f69ce5c/.github/workflows/test-notebooks.yml#L76) that's set using a GitHub secret. If that environment variable is not set or is invalid, the demo token (with a limited number of downloads) is used as a default.

My preference is the following:
* Have developers who are working from forks do the same thing as us. That is, add a GitHub secret that encrypts their own *opentopography* token.
* Simply ignore these notebook failures and merge despite them. This is what I've been doing thus far.

**Comment by sebastien-lenard** [comment]
@mcflugen thank you for advice. Since I noticed the problem I tried to relaunch the failed job and it has usually worked. So I close the issue.
