### ISSUE TITLE
Component import error cfuncs threshold_eroder 

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#1483]
Hey @mcflugen (and maybe @sebastien-lenard). I'm having a similar issue to that described in [#1165](https://github.com/landlab/landlab/issues/1165). When I try to import landlab components, I get: 

```
ModuleNotFoundError: No module named 'landlab.components.threshold_eroder.cfuncs'
```

As described in #1165, I re-entered `python setup.py develop` in Anaconda Powershell Prompt, but in this case it didn't resolve the issue. I get: 
```
c1: fatal error C1083: Cannot open source file: 'landlab\components\threshold_eroder\cfuncs.c': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

Any hints?

**Comment by sebastien-lenard** [comment]
Hey @pfeiffea!
If you didn't do this, I think you can try to reinstall Landlab using
```
pip install -e .
```
see Landlab developer instructions here: https://landlab.readthedocs.io/en/master/development/install/install.html

@mdpiper

**Comment by pfeiffea** [comment]
Excellent, thanks @sebastien-lenard! That's all it took. By now I should know that when in doubt, just reinstall...
