### ISSUE TITLE
BC assignment

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#150]
As Sai has discovered, when interacting with BCs, you often want to set the condition of a single node manually. It's very tempting to do:

> mg.node_status[my_node] = new_cond

...but this is a BAD IDEA unless you know what you're doing, as it will only update the *node* statuses, not links, cells, etc.

We already have mg.update_links_nodes_cells_to_new_BCs(), but you have to *know* to call it. Obvious solutions are:

1. Make mg.node_status read-only (somehow...? not trivial, as many methods already mess with it directly), and force users to use a new BC_assign() -type method.
2. Overload [] so it can sense if you're trying to assign to node_status, and call mg.update... automatically.

**Comment by nicgaspar** [comment]
Good find.  This seems really dangerous.  I like your second solution.

**Comment by SiccarPoint** [comment]
I think a good solution will be to replace mg.node_status in all its current uses with mg._node_status, as we should be discouraging users from messing with it directly. Then we do...

```
def node_status:
    def __getitem__(self, index):
        if is instance(index, slice):
        return self._node_status[index]

    def __setitem__(self, index, vals):
        self._node_status[index] = vals
        self.update_links_nodes_cells_to_new_BCs()
```

This should work, right?

**Comment by SiccarPoint** [comment]
Nudge @mcflugen...

**Comment by SiccarPoint** [comment]
Oooh, also, we could also add to the __setitem__ override to incorporate a test to stop users being able to set perimeter nodes as core. That would seem sensible...

**Comment by mcflugen** [comment]
One way to do this is to make `node_status` a property and decorate it with `make_return_array_immutable` (defined in `landlab/utils/decorators.py`). This creates a view of the array that has the `writable` flag set to `False`. We already do this with other arrays we don't want users messing with. In fact, I was just about to do this with `node_status` with my latest code clean-up.

We could also have a setter for the `node_status` property that calls `update_links_nodes_cell_to_new_BCs` when `node_status` is changed (and also do checks like @SiccarPoint  suggests).

So, for the getter, something like,
```
@property
@make_return_array_immutable
def node_status(self):
    return self._node_status
```
and the setter,
```
@node_status.setter
def node_status(self, new_node_status):
    self._node_status[:] = new_node_status[:]
    self.update_links_nodes_cells_to_new_BCs()
```

**Comment by SiccarPoint** [comment]
This sounds good, Eric. Are you on this? I’ve just spent half an hour reading about decorators, and concluded I don’t get it. So that might be a good call if you do it. (Though equally, I should probably make more effort with decorators)

I do note though that a common use case will be

    node_status[2] = 1

So if I’m reading it right your example setter will fail when it tries new_node_status[:], as new_node_status would be an int. But that would be a simple fix. Should it also cope with generic iterables, if a user tries e.g. a list??

**Comment by SiccarPoint** [comment]
...Also, I was just messing about with this, and couldn't get the setter as you are doing it to "take" in my simple use case above. Isn't it the case that the setter only gets called if I do

```
mg.node_status = some_array_of_node_statuses
```

...but the very, very common usage is

```
mg.node_status[5] = 1
```

which is the direct equivalent of

```
mg.node_status.__getitem__(5) = 1
```

...which would be very troublesome.

**Comment by mcflugen** [comment]
You are correct. The method I described was only for setting the `node_status` attribute - not an element of the array. If that's something we need, we could do one of the following:
- Overload `__setitem__` for the node_status array - as you suggested.
- Create a new method to do the setting (maybe `def set_status_at_node(self, ind, status)`) where `ind` is one or more indices and `status` is one or more statuses.

The first method would definitely be slicker but I think I'm leaning toward the second.

Some use cases,
```
>>> grid.node_status[5] = 1
>>> grid.node_status[1:4] = 1
```
vs.
```
>>> grid.set_node_status(5, 1)
>>> grid.set_node_status(range(5), 1)
```
When you put it like that, the first way sure seems nicer (and clearer!). I think I've changed my mind. I'll look into this later this evening.

**Comment by SiccarPoint** [comment]
Thanks Eric. I also think the former would be way nicer, if we can arrange it. This is the way that is instinctive to do it...

**Comment by mcflugen** [comment]
#151 gives an initial shot at this.

Notice that the new getter/setter for `node_status` is called, `status_at_node`. The `node_status` attribute is still as it was before. With `status_at_node` you should be able to do things like,
``` python
grid.status_at_node[2] = 1
grid.status_at_node[:4] = 2
```
and have things update correctly.

The following example now works as @saisiddu expects. 
``` python
import numpy as np
from landlab import RasterModelGrid as rmg
from landlab.components.flow_routing.route_flow_dn import FlowRouter

grid = rmg(4,5,1.)
z = np.array([5., 0., 5., 5., 5.,
              5., 1., 2., 2.5, 5.,
              5., 3., 4., 3., 5.,
              5., 5., 5., 5., 5.])

grid['node']['topographic__elevation'] = z
grid.set_closed_boundaries_at_grid_edges(True, True, True, True)
grid.status_at_node[1] = 1 # Setting drainage point for the eg.1 basin
fr = FlowRouter(grid)
fr.route_flow()
r = grid.at_node['flow_receiver']
```
The value of `r` is,
``` python
array([ 0  1  2  3  4  5  1  1  7  9 10  6  6  7 14 15 16 17 18 19])
```

**Comment by SiccarPoint** [comment]
Just wondering what the rationale was for the new name, instead of node_status->_node_status, mg.node_status becomes the property?

**Comment by mcflugen** [comment]
This is one of the things I had in mind when I said the pull request wasn't complete. The `node_status` attribute should definitely be changed to `_node_status` so that it's private. I just wanted to try this out quickly before going through the code with a search/replace.

However, `status_at_node` does fit with the new naming convention we talked about.

**Comment by SiccarPoint** [comment]
Sweet. Just happy it works!

**Comment by mcflugen** [comment]
What do you all think of (the existing) methods like:
* `boundary_node_status`
* `get_node_status`
* `get_boundary_code`
* `set_fixed_value_boundaries`

There are probably others. Personally, I think if we go this new way, we should get rid of all of these functions (and some of them we should get rid of no matter what).

**Comment by mcflugen** [comment]
What about the name? I had temporarily called it `status_at_node` so it wouldn't conflict with everything that was already there. However, it would be easy enough to have it be `node_status`. `status_at_node` is longer but it fits in with other names we're using (`cell_at_node`, `node_at_cell`, etc.)

**Comment by SiccarPoint** [comment]
I like status_at_node!

**Comment by mcflugen** [comment]
OK. `status_at_node` it is!

**Comment by SiccarPoint** [comment]
Pretty sure we got this nailed...
