### ISSUE TITLE
Jupyter Notebook Syllabus Binder Page 424 Error

### ISSUE THREAD

**Issue by alderonruiner** [landlab/landlab#1506]
On the Jupyter Notebook syllabus, under section 1.1, the binder link results in a 424 error.

**Comment by gregtucker** [comment]
I just tested it, and it worked for me. I wonder whether this might be a temporary binder issue. Are you still seeing it @alderonruiner ?

**Comment by alderonruiner** [comment]
Looks like it is all working now.
