### ISSUE TITLE
Links to 404 pages in tutorials user guide

### ISSUE THREAD

**Issue by sebastien-lenard** [landlab/landlab#1519]
I tried to follow the guidelines [https://landlab.readthedocs.io/en/master/user_guide/tutorials.html] to install the tutorials locally, but the code
```curl -L https://raw.githubusercontent.com/landlab/landlab/mcflugen/fetch-notebooks-script/notebooks.py | python -```
 leads to a 404. I think this page might require an update of the procedure.

**Comment by mdpiper** [comment]
This is a quick fix--I can do it now.

**Comment by mcflugen** [comment]
@mdpiper I've already done it!

**Comment by mcflugen** [comment]
> @mdpiper I've already done it!

Oh, but I see you've already create a pull request. Let's use that.

**Comment by mdpiper** [comment]
@mcflugen I can ditch the PR. It's overkill for this, especially if you've already fixed it.

**Comment by mcflugen** [comment]
Let's keep your pull request. I only made the change in a branch but hadn't created a new pull request.
