### ISSUE TITLE
SPL slope computation

### ISSUE THREAD

**Issue by carpetit** [landlab/landlab#1522]
Sorry if my question is a bit stupid, but I don't understand why the "slope" term in the stream power or fast scape eroders is equal to 1/length_of_link and not equal to the actual donor-to-receiver slope. Do I miss something ? Thanks.

**Comment by gregtucker** [comment]
@carpetit can you point to the code where you see this? The slope should be (donor-to-receiver elevation difference) / (length-of-link between them), which is the donor-to-receiver slope. The length of the link (which in the case of a rectiliear grid with D8 routing is actually the length of the "d8": either a link or a diagonal, depending on flow direction) is the horizontal distance between donor and receiver.

**Comment by carpetit** [comment]
Hi,
Thank you for your reply,
It's on lines 323-328 of the FastscapeEroder component; maybe I'm mistaken but I thought alpha was the 1-step erosion height, equal to alpha=K.dt.A**m.S**n according to the SPL. Here it seems alpha= K.dt.A**m.(1/L)**n. Same thing on lines 396-411 of StreamPowerEroder. I don't understand where the elevation difference is accounted for. 

            self._alpha[defined_flow_receivers] = (
                self._K[defined_flow_receivers]
                * dt
                * self._A[defined_flow_receivers] ** self._m
                / (flow_link_lengths**self._n)
            )

**Comment by mcflugen** [comment]
@carpetit I believe *alpha* is multiplied by the elevation difference inside the [brent_method_erode_variable_threshold](https://github.com/landlab/landlab/blob/101c53677bc33be6446e80331075e338f7673f79/landlab/components/stream_power/cfuncs.pyx#L23) and [brent_method_erode_fixed_threshold](https://github.com/landlab/landlab/blob/101c53677bc33be6446e80331075e338f7673f79/landlab/components/stream_power/cfuncs.pyx#L150) functions, which are called from the `FastscapeEroder`'s `run_one_step` method.

**Comment by carpetit** [comment]
ah yes, I missed this point. Thank you very much for your help.
