### ISSUE TITLE
Incorrect version string

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#1531]
It seems as though *Landlab*'s version string (contained in `landlab._version.py`) didn't get updated with the last release (v2.5.0). Instead of being,
```python
__version__ = "2.5.1.dev0"
```
it remained as,
```python
__version__ = "2.4.2.dev0"
```
This hadn't been much of an issue until I tried to use our notebook downloader script to fetch the notebooks that match the currently installed version of *landlab*.

**Comment by mdpiper** [comment]
Fixed with #1532.
