### ISSUE TITLE
error when importing window_statistic

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#1548]
I'm trying to use the **window_statistic** utility in a Jupyter Notebook running on the CSDMS hub. I get an error when I try to import the **window_statistic**. I assumed it was my typing, so I went back and tried to tab after **_import_** and I saw lots of other utils, but not the **widow_statistic** or **calculate_window_statistic**. Any hints? Please see attached screenshot. Thanks!
<img width="886" alt="Screen Shot 2023-02-23 at 1 57 24 PM" src="https://user-images.githubusercontent.com/6990475/221016323-2a2e93b8-c47c-4b45-b37b-003df501526d.png">

**Comment by mdpiper** [comment]
Landlab v2.5.0 is installed in the CSDMS kernel on the *lab* Hub instance. It looks like this utility is newer, included in v2.6.0.

I had planned to update the software in the CSDMS kernel before ESPIn. Maybe it's good to do so now?

**Comment by nicgaspar** [comment]
It's not urgent. I just wanted to make sure I hadn't lost my mind!

**Comment by mdpiper** [comment]
This has me concerned now, so I'll plan to do it tomorrow.

**Comment by mdpiper** [comment]
@nicgaspar This should be fixed now with https://github.com/csdms/jupyterhub-management/issues/6. Please let me know if this works for you & we can close this issue.

**Comment by nicgaspar** [comment]
It worked! All systems go! Thank you!
