### ISSUE TITLE
Pit filler

### ISSUE THREAD

**Issue by jadams15** [landlab/landlab#155]
This came up during our last call. ArcGIS D8 pit filling is not sufficient for the overland flow component, as that operates in D4. Could be a useful utility to have a pit filler algorithm that operates in D8 by default and functions as D4 when flagged by the user to do so.

**Comment by jadams15** [comment]
I've reached out to one of Garry Willgoose' (former?) students about some Cythonized pit fillers he wrote for an Australian modeling conference. Otherwise I'm going to take a crack at this.

**Comment by SiccarPoint** [comment]
Hold up - we now have two new components. The lake_mapper now performs transient routing (i.e., of water) across depressions, and the new sink_fill component can modify an existing topo to allow clean routing of flow across the whole landscape.

Does either of these address your needs? D4 routing isn't implemented in either yet, but in principle isn't hard.

**Comment by jadams15** [comment]
Where is this new component? Does it create flats or inclines? Flats are sufficient for my case, but it would be good functionality to have both. I can take a look and see if I can adapt it for d4.

**Comment by SiccarPoint** [comment]
I can probably do the D4 today anyway. There's a pull request open for it right now: #168. No-one is assigned yet.

**Comment by jennyknuth** [comment]
Just assigned this to Jordan (took Eric off since it sounds like Jordan
wants to look at it anyway).

**Comment by jadams15** [comment]
OK. Should I wait to review until you've added d4? Or do you want me to look at it now. Either works.

**Comment by SiccarPoint** [comment]
Review what’s there. The D4 can be a separate thing.

**Comment by jadams15** [comment]
Ok. Can do.

**Comment by SiccarPoint** [comment]
Pit filler now I think works. D4 should be implemented. I'll re-open if we find bugs.
