### ISSUE TITLE
Provide links to open notebooks on EarthscapeHub

### ISSUE THREAD

**Issue by mdpiper** [landlab/landlab#1555]
Currently, there are links in the README to open the Landlab example and teaching notebooks on the *jupyter* instance of EarthscapeHub. We should provide links to open these notebooks on the *lab* instance, as well.

**Comment by mdpiper** [comment]
While doing this, also change "CSDMS JupyterHub" to "EarthscapeHub".

**Comment by mdpiper** [comment]
Two sections of the docs:

1. https://landlab.readthedocs.io/en/master/getting_started/10min.html
2. https://landlab.readthedocs.io/en/master/getting_started/teach_yourself_landlab.html

should also have links to the _lab_ and _jupyter_ Hubs.

**Comment by mdpiper** [comment]
Sample text for the second above:

> If you have access to [EarthscapeHub](https://csdms.colorado.edu/wiki/JupyterHub) through class or CSDMS membership, you can access this course on the [lab](https://lab.openearthscape.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Flandlab%2Flandlab&urlpath=lab%2Ftree%2Flandlab%2Fnotebooks%2Ftutorials%2Fsyllabus.ipynb%3Fautodecode&branch=master) and [jupyter](https://jupyter.openearthscape.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Flandlab%2Flandlab&urlpath=lab%2Ftree%2Flandlab%2Fnotebooks%2Ftutorials%2Fsyllabus.ipynb%3Fautodecode&branch=master) instances (login required for both) using the *CSDMS* kernel.

**Comment by mdpiper** [comment]
Whoops, this is a dup of #1508!

**Comment by nicgaspar** [comment]
Mark, thanks for jumping on this. Are we removing links to Binder?

**Comment by mdpiper** [comment]
No, the Binder links remain; I'm adding new sections on launching the notebooks on EarthscapeHub.

Would it be OK to list you as a reviewer on the associated PR, #1556? I'm almost done with it.

**Comment by nicgaspar** [comment]
Yes, but is this closed already?

**Comment by mdpiper** [comment]
I'm sorry, I merged the changes too hastily. If you'd like, you can see what I did in the PR, and the changes are live at https://landlab.readthedocs.io/en/master/user_guide/tutorials.html
