### ISSUE TITLE
field of arrays

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#1583]
Hi!
How do I create a field of arrays? E.g. an array of length 10 at every note? I looked at JaggedArray but I'm a little confused about how it works. But is this what I should be using? e.g. make a jagged array of length nodes, but then query the core node members of the jagged array? Sorry if I'm missing an example somewhere.
Thanks,
nicole

**Comment by mcflugen** [comment]
@nicgaspar If you want an array of constant length at each node (say, 10) you could do it like the following,
```pycon
>>> values_per_node = 10
>>> data = np.arange(grid.number_of_nodes * values_per_node)  # some made up data
>>> grid = RasterModelGrid((3, 4))
>>> grid.at_node["data"] = data
>>> grid.at_node["data"][1]  # get the data array at node 1
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
```
Is this what you're looking for?

**Comment by nicgaspar** [comment]
Oh wow. I never would have figured that out. Thank you.

**Comment by nicgaspar** [comment]
Did you actually run that? Doesn't the third line need to be before the second line? I don't want other people to get confused. (I don't actually have Landlab working on my computer right now so I can't try it without logging onto the hub and I'm lazy.)

**Comment by mcflugen** [comment]
> Doesn't the third line need to be before the second line?

Quite right! Fixed. (I had run it but I pasted it incorrectly into the comment)
