### ISSUE TITLE
Update the dev environment on jupyterhub and creation of the same in lab.openearthscape hub

### ISSUE THREAD

**Issue by sebastien-lenard** [landlab/landlab#1611]
@mdpiper recreated the development environment on jupyterhub today.
It would be great to have a similar environment on lab.openearthscape to demo the new components still in finalization of development (FlowRouter).

A/ Presently, the jupyterhub dev environment still lacks these packages, which should be installed.
- black-jupyter (linked to the validation processes put in place by Eric on github on the notebooks)
- commonmark (depency with black-jupyter?)
- dataclasses  (class introspection)

B/ And these ones, but I don't remember having asked for them, I proposed not to install them right now (maybe some of them are dependencies of the 1st group)

- fftw  
- future (compatibility python 2/3). 
- gstreamer-orc
- heapdict (dictionnaries)
- ipython  (interactive shell)                 
- libcurl 
- libdap4 
- libtool 
- libudev1 
- libxslt 
- lxml     
- mypy-extensions 
- nodejs 
- portaudio    
- python-slugify
- tokenize-rt 
Refers to closed issue: https://github.com/landlab/landlab/issues/1485

**Comment by mdpiper** [comment]
I've opened a new issue, https://github.com/csdms/jupyterhub-management/issues/12, with this request.

I'll close the present issue (English is failing me; this one right here) since it's out of scope for Landlab.
