### ISSUE TITLE
Fastscape Eroder: No fluvial erosion when m < 1

### ISSUE THREAD

**Issue by eb-mars** [landlab/landlab#1626]
Hi! 

I am trying to model the formation of valley "inlets" into impact craters. I wrote a simple code to generate impact-shaped topography (following the procedure of Howard, 2007), and I was hoping to use Landlab for the modeling, with the idea of varying the parameter m (exponent to surface area in stream power, relating discharge to surface area, as a possible "climate"/ environment proxy). However, in my model runs so far, there isn't any fluvial erosion and growth of valleys unless m = 1, which sucks because I want to vary m (and vary it to as low as m = 0.3, as was used in previous modeling papers for Mars, e.g. Barnhart 2009, Matsubara, etc.). 

I was wondering if the Fastscape Erosion & Landlab team have any thoughts on this??? Is there something about m < 1 that changes the model behaviour that I'm not understanding? 

Attached is a plot of what my landscape looks like after 100,000 years with m = 0.7, n = 0.2, and K = 0.0001. As you can see, valleys form on the walls of the crater, but then that is basically the 'steady state' and nothing changes, even after 100 ka. So is it just that I need something to help drive erosion?? Any recommendations??
![image](https://github.com/landlab/landlab/assets/84507581/c7dcaa39-ff2d-430c-afff-e7d6bc7d6ca1)

FYI - I tried n = 1.5, 1.75, because n is normally higher than m in terrestrial cases (and tried to keep m/n > 0.5), and this helped a little (do some more erosion), but then isn't appropriate for my modeling idea, because if I increase n to beyond 0.5, the erosion changes and is very "evenly spread" around the crater, leading to 'crater wall backwasting' but no real formation of inlet valleys. 
e.g. 
![image](https://github.com/landlab/landlab/assets/84507581/ac2e8732-c382-4507-81bc-06737860763a)

Edited to add: my crater in the center does not have a rim around it, and I had this code previously working, though the parameters and my crater generation were off, (i.e. unrealistic K, unrealistic slope), e.g.  with slope = 0.1, K_sp=0.001, m_sp=1, n_sp=1, threshold_sp=3., dt = 1
![image](https://github.com/landlab/landlab/assets/84507581/fb773d6b-5310-4605-b8f4-eb62d22a4939)

**Comment by nicgaspar** [comment]
FastScape should work with any positive values for m and n. I haven't seen people use m > n, but I can't think of a reason why that wouldn't work. If you have a threshold in your models, then erosion will stop once the channels reach the threshold value. Otherwise, as long as you have a slope and drainage area (by definition every node has a drainage area because every node drains itself) and zero threshold, erosion should occur, although possibly very slowly.

**Comment by eb-mars** [comment]
Thank you, thank you! It was a threshold. A simple line I paid no mind to, and had been down in a coding hole thinking it was something more complicated. I'm sorry for taking your time, but this simple un-muddled insight is all I needed. Thank you!
