### ISSUE TITLE
Tutorials on visualizing Landlab output in ParaView

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1646]
ParaView is a powerful open-source visualization package. It would be nice to have tutorials on how to get Landlab grid and field output into ParaView. I envision tutorials for at least two different file formats:

1. NetCDF files for raster grids
2. Legacy VTK files for hex, raster, unstructured

**Comment by benbovy** [comment]
@gregtucker you might also be interested in a few other open-source tools that allow paraview-like 3D visualization within jupyter notebooks:

- ipygany: https://github.com/QuantStack/ipygany (based on three.js)
- pyvista: https://docs.pyvista.org (based on vtk.js)
- pyvista-xarray: https://github.com/pyvista/pyvista-xarray

They don't have as much features as Paraview, but their advantage is that there's no need to create temporary output files, and staying in jupyter is great for tutorials. It could also probably be deployed on EarthscapeHub.

I've tried some time ago using `landlab` with [ipyfastscape](https://github.com/fastscape-lem/ipyfastscape), which is built on top of ipygany, ipywidgets and xarray. There's a screenshot (animation) [here](https://twitter.com/benbovy/status/1324716676064174081) and the notebook is [here](https://notebooksharing.space/view/c5f812e6eff5bca4cb4b004147d534a9fcb684de7fc64bed4d265d603c3a321d#displayOptions=). It only works with raster grids but with some work it is possible to visualize arbitrary grids (the raster grid is actually converted into an unstructured mesh before it is passed to ipygany for the visualization).

There is also a paraview-like jupyterlab extension: https://github.com/trungleduc/jupyterview. I haven't tried it much yet, though. I think it is still requires saving outputs to files.

**Comment by gregtucker** [comment]
Thanks @benbovy these looks great!
