### ISSUE TITLE
Assigning flood_status_code in PriorityFloodFlowRouter

### ISSUE THREAD

**Issue by cmshobe** [landlab/landlab#1683]
PriorityFloodFlowRouter creates the grid field flood_status_code but currently does not update it to reflect the flooded status of any closed depressions. flood_status_code needs to be set = 3 (_FLOODED) in any flooded areas. @BCampforts and I discussed one way to do this by comparing the depression-free elevation surface (filled sinks) with the real elevation surface:

`self.grid.at_node["flood_status_code"] = np.where(self.grid.at_node["depression_free_elevation"]==self.grid.at_node["topographic__elevation"], 0, 3)`

**Comment by BCampforts** [comment]
Good catch! I will implement the solution as discussed.
