### ISSUE TITLE
DepthDependentTaylorDiffuser should support hex grids

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1694]
`DepthDependentTaylorDiffuser` relies on the grid having an attribute `dx`, representing grid-cell spacing. Raster grids possess this attribute, but hex grids use `spacing` instead. The component should be smart enough to handle either case.

**Comment by mcflugen** [comment]
@gregtucker A possible solution would be to use the `length_of_link` attribute, which is available on all grids. One issue with that, though, is that it is an array of length *n_links* so we would have to use, for example, something like `np.min(grid.length_of_link)`.

**Comment by gregtucker** [comment]
@mcflugen that sounds right to me. I guess there's a choice to be made between calculating the minimum link length ahead of time, during `__init__`, or calculating it each time the Courant condition is applied. The former increases performance but could fail if one had a deforming or AMR ("active mesh refinement") grid; the latter is slower and allows deforming/AMR grids. I guess I lean toward the first, as I'm unaware of anyone using this or other LL components on deforming or AMR grids.

**Comment by mcflugen** [comment]
@gregtucker I agree. This is something to keep in mind but, until *Landlab* allows grids to evolve after they have been created, not something we need to support yet.

**Comment by gregtucker** [comment]
Addressed by PR #1707
