### ISSUE TITLE
Core cells incorrectly updated on node-status change

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#171]
I could be wrong but it seems the core cells are not being updated correctly after a node status change. For example,
```python
>>> import landlab
>>> grid = landlab.RasterModelGrid((4, 5))
>>> grid.status_at_node[7] = landlab.CLOSED_BOUNDARY
>>> grid.core_cells
array([0, 1, 2, 3, 4])
```
I think what's happening is that the old-style indexing is still being used here. That is, *core cells* have their own indexing. Probably, then, `ModelGrid._reset_lists_of_nodes_cells` needs updating. It needs updating not just for the indexing problem but also it's using old terminology (*active* nodes and cells vs. *core* nodes and cells). Truthfully, I'm not 100% sure what the correct answer for the above example is (I would guess `[0, 2, 3, 4 , 5]`) but I'm pretty sure it's not `[0, 1, 2, 3, 4]`.

**Comment by mcflugen** [comment]
Looking closer at this, there is some more cleaning that needs to be done. There are still attributes that use the old-style naming and indexing.

The following attributes should be **removed**:
- `activecell_node`
- `node_corecell`
- `corecell_node`
- `node_activecell`

The following should be **renamed**:
- `active_cells` -> `core_cells`

I'm not sure any of these are really used. I'm in the process of cleaning this up now.

**Comment by mcflugen** [comment]
The function `calculate_flux_divergence_at_core_nodes` is unused. Can we remove it?

**Comment by jadams15** [comment]
I'm ok with removing it.

**Comment by mcflugen** [comment]
Thanks. I think I'll probably get rid of it. I think you can (or probably should be able to) do the same thing with `calculate_flux_divergence_at_nodes`.

**Comment by gregtucker** [comment]
Agreed, it should be equivalent to:
fd = calculate_flux_divergence_at_nodes(q)
fdcn = fd[core_nodes]

**Comment by gregtucker** [comment]
Eric, for the core_cells numbering issue, my sense is that the cells should still have separate numbering (since they are different from nodes), but of course we now no longer have yet another numbering scheme for "core" nodes and cells. So, in a 4-row by 5-column grid, there would be 6 cells, numbered 0 to 5. They all happen to be core cells. So, grid.core_cells should just return [0, ..., 5]. Does that sound right?

**Comment by mcflugen** [comment]
Thanks, Greg. That sounds right. The problem was that if one of the nodes (say, node 7) is set as a closed boundary node, it is no longer *core*. The corresponding cell (1) is also no longer *core*. Thus, the `core_cells` array should now be `[0, 2, 3, 4, 5]` (not `[0, 1, 2, 3, 4]` as was being returned). Am I understanding this correctly?

**Comment by SiccarPoint** [comment]
I think that’s right, Eric.

**Comment by gregtucker** [comment]
Sounds right to me too. The default for a raster ("regular" or whatever) grid is not to have any non-core cells, because the only non-core nodes are around the perimeter, and those nodes don't have cells. But if one sets an interior node to boundary, then the corresponding cell should be non-core too.

**Comment by mcflugen** [comment]
We still have a grid method called, `get_active_cell_node_ids`. I believe it should return the nodes of all cells that are either **core** or **open boundary**. It's used by quite a number of components, including:
- `flow_accum`
- `sed_trp_shallow_flow`
- `simple_power_law_incision`
- `stream_power`
- `transport_limited_fluvial`

I believe these components belong to @gregtucker, and @SiccarPoint. I guess this should really be rewritten as:
``` python
np.where(self.status_at_node != CLOSED_BOUNDARY)
```
and so should maybe be better called something like `non_closed_node` (`open_node`)? What do you think?

**Comment by mcflugen** [comment]
Or, instead, those components simply use,
``` python
np.where(grid.status_at_node != CLOSED_BOUNDARY)
```
and we don't have a special method in `ModelGrid` for this. Actually, I think this is probably the best way. It's more explicit and easier to understand.

**Comment by SiccarPoint** [comment]
Yeah, the name is bad. Like, really bad. It’s putting cells at the grid boundaries!

>>> mg = RasterModelGrid(10,10)
>>> mg.get_active_cell_node_ids()
100
(!!!)

You’re quite right about what this is doing: np.where(self.status_at_node != CLOSED_BOUNDARY).

**Comment by SiccarPoint** [comment]
Yes. Think you’re right. Are you happy to make these changes?

**Comment by mcflugen** [comment]
Yes. In fact, it would make me quite happy!

**Comment by gregtucker** [comment]
I think that's a *really* early version of what later became simply grid.core_nodes

**Comment by mcflugen** [comment]
But it's not *exactly* `core_nodes`, right? As far as I understand, the way things are right now, a core node wouldn't include nodes that are *open* boundary nodes.

**Comment by SiccarPoint** [comment]
Exactly, Eric. There are loads of cases where you want to solve on “nodes that aren’t closed”, not “core nodes”.
