### ISSUE TITLE
accumulate_flow taking too long to compute

### ISSUE THREAD

**Issue by n-ivanovic** [landlab/landlab#1756]
Hi,

I'm working on adapting the DRYP (https://github.com/AndresQuichimbo/DRYP/tree/main) hydrological model for the regional extent (25×30 [°]), but the accumulate_flow function (https://github.com/AndresQuichimbo/DRYP/blob/main/components/DRYP_routing.py), which is imported directly from the landlab module, 
(https://github.com/landlab/landlab/blob/master/landlab/components/flow_accum/flow_accumulator.py#L1151) takes too long to compute (~4 [min] per time step).

Some information about the areal extent: 
No. of columns:      2895
No. of rows:            2930
Cell size:                 1000 [m]
No. of cells:            8482350

I've traced back the problem to the _accumulate_bw cython function where it calculates drainage area and discharge (https://github.com/landlab/landlab/blob/master/landlab/components/flow_accum/cfuncs.pyx). The function works, although it appears that the drainage area takes a while to compute for a single iteration. I wanted to check if I'm, perhaps, doing something wrong, or the function indeed requires a decent amount of time to compute. Perhaps, you've encountered a similar question so far? Let me know, please.

Thanks,
Nikola

**Comment by gregtucker** [comment]
Have you tried PriorityFloodFlowRouter? It uses an optimized algorithm and will likely be faster on your size DEM. More info here: [https://landlab.readthedocs.io/en/latest/reference/components/priority_flood_flow_router.html](https://landlab.readthedocs.io/en/latest/reference/components/priority_flood_flow_router.html)
