### ISSUE TITLE
map_link_vector_to_nodes is "not correct and needs to be changed"

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#1786]
In going through our *docstrings*, I came across the following warning contained in ``ModelGrid.map_link_vector_to_nodes``,
```
THIS ALGORITHM IS NOT CORRECT AND NEEDS TO BE CHANGED!
```
Does anyone know if this is still true? If so, should we fix it or should we simply remove this method? It doesn't seem to be used anywhere.

**Comment by gregtucker** [comment]
This looks like something I probably worked on years ago. I wanted a general way to derive vector components from links that could work on non-raster grids (which already have the components decomposed). Somewhere along the way I discovered that you can't recover vector information from a single link. You need a pair of them, and given such a pair, it is possible to translate into orthogonal (x and y) vector components.

We now have `map_link_vector_components_to_nodes`, which accomplishes the task for raster and hex grids. Given that this older and apparently unused routine is incomplete, I do think we should remove it. Ultimately, it would be good to implement a version for unstructured grids.

**Comment by mcflugen** [comment]
Closed with #1815.
