### ISSUE TITLE
Wouldn't it be awesome to have a NEW Quasi-Spherical Grid Type based on an Icosphere tesselation?

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1808]
We live on a planet. Planets are round.

It would be just fabulous if we could have at least one type of Landlab grid that wraps a sphere! An icosphere in particular would be nice, as it provides a relative uniform distribution of nodes and related elements, plus it has a natural dual. And an icosphere can be densified to any resolution desired.

Of course, the earth is actually a spherOID, not a perfect sphere. However, given a spherical grid, one could assign a field for topography that represents the true surface of the spheroid, or alternatively, a geoid surface.

**Comment by mcflugen** [comment]
If only! That, unfortunately, sounds like pie-in-the-sky stuff.
