### ISSUE TITLE
 Get run off rate based on precipitation events with different intensities

### ISSUE THREAD

**Issue by hhhmomo** [landlab/landlab#1819]
Hi, I'm relatively new to the LandLab. I'm intending to model the landscape evolution after precipitation events. It seems like combining precipitation distribution, flow accumulator, fastscape erosion, and linear diffusion is not adequate to solve this problem because the topographic elevation remains the same even after changing the mean rainfall depth. Would adding OverlandFlow and then running the flow accumulator help?

**Comment by gregtucker** [comment]
@hhhmomo can you provide a minimal code example that reproduces the problem you are seeing?

**Comment by hhhmomo** [comment]
@gregtucker Never mind, I've figured it out. I forgot to modify the water_unit_flux_in field previously. Thanks for your reply!
