### ISSUE TITLE
Request for MassWastingRunout Component

### ISSUE THREAD

**Issue by mathusivas** [landlab/landlab#1834]
I recently came across a paper titled "A landslide runout model for sediment transport, landscape evolution and hazard assessment applications", where the authors discussed the implementation of a MassWastingRunout component in Landlab. After checking the current state of the Landlab package, it appears that this component is not present in the latest release. Do you have any release date for the component? Or is it already available?

**Comment by mcflugen** [comment]
@mathusivas I think this is probably a question for @keckje.

You may want to have a look at #1830, which is a pull request to add ``MassWastingRunout`` to *Landlab*. It not's ready to merge yet, but I suspect it's not too far off.

**Comment by mathusivas** [comment]
Thank you for your prompt response! I've already reached out to @keckje and received the information I needed.
