### ISSUE TITLE
Python 2.7 builds fail on AppVeyor

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#184]
Our AppVeyor builds that use Python 2.7 are failing. It's not that our tests are not passing. The Miniconda script fails trying to install Python. At this point it's unclear if it's a problem with AppVeyor or Miniconda.

**Comment by mcflugen** [comment]
It would be helpful if someone with easy access to a Windows machine could try to install Miniconda so that we could isolate the problem to either AppVeyor or Miniconda. @jadams15, @saisiddu?

**Comment by jadams15** [comment]
My old Windows machine is currently disassembled. I could do it on another lab computer sometime later this week. It would probably happen quicker if @saisiddu does it. If not done by Thursday, say, I can do it.

**Comment by saisiddu** [comment]
Hi Eric, I can try to do this but I am not sure what needs to be done. I am already behind on merging the pull requests. I have my qualifiers next week and am grading too. So, I cannot promise anything at this moment. Sorry!

Sai


________________________________

**Comment by mcflugen** [comment]
Thanks, Sai. If you can get to it, great. If not, no biggie. I have a VM I can try with.

**Comment by mcflugen** [comment]
I've filed an issue with AppVeyor and am waiting to hear back. Disabling the Python 2.7 builds just made the 3.4 builds fail so I'm pretty sure it's a problem on their side not ours or Anaconda's.

**Comment by mdpiper** [comment]
With #1270, Landlab uses GitHub Actions for continuous integration.
