### ISSUE TITLE
Future Warning landlab.plot.graph.plot_graph()

### ISSUE THREAD

**Issue by sebastien-lenard** [landlab/landlab#1910]
The use of the landlab.plot.graph.plot_graph(graph.plot_graph(grid, at="node") in a notebook returns this warning:

/home/jupyter-sebastien-lenard/landlab/landlab/graph/graph.py:414: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  return self.ds.dims["node"]

**Comment by mcflugen** [comment]
@sebastien-lenard Thanks. I thought I had already fixed this. I'll have a look.
