### ISSUE TITLE
NetworkSedimentTransporter bug resulting in excess topographic change

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#1921]
@Ashaniekam and I found a bug in the `NetworkSedimentTransporter` component that resulted in excess calculated topographic change. The stored volume at a link was calculated as sediment (rock + pore space) volume, but in a later calculation assumed to be just rock volume. Essentially, the porosity correction was done twice. 

Minor code edit to resolve the issue. I have a pending[ pull request](https://github.com/landlab/landlab/pull/1920) to fix this on @mcflugen's branch ([speed-up-nst](https://github.com/landlab/landlab/tree/mcflugen/speed-up-nst), which currently houses the much-needed edits to the component. 

@mcflugen does this work, or should I do a separate pull request into landlab/landlab?

**Comment by mcflugen** [comment]
> @mcflugen does this work, or should I do a separate pull request into landlab/landlab?

If this is a bug in the main *Landlab* branch, then it might make sense to have a pull request into the *master* branch that fixes this bug. The way you've done it is also fine, though—it's just that users won't see the bugfix until we merge the branch.

**Comment by pfeiffea** [comment]
Closing. Addressed in https://github.com/landlab/landlab/pull/1920
