### ISSUE TITLE
Update NetworkSedimentTransporter with transport dependent abrasion

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#1952]
Minor upgrade to the NST: I've added transport dependent abrasion (as in Pfeiffer et al., 2022) to the component. The default is no transport-dependence, so existing users should not be impacted. Pull request to @mcflugen 's [speed-up-nst](https://github.com/landlab/landlab/tree/mcflugen/speed-up-nst) branch coming shortly. 

FYI @jonczuba @ashaniekam

**Comment by mcflugen** [comment]
@pfeiffea I've you've been using my [speed-up-nst](https://github.com/landlab/landlab/tree/mcflugen/speed-up-nst) branch and have been ok with it, maybe I should merge that pull request. Would you all be ok with that?

**Comment by pfeiffea** [comment]
Closing. Incorporated in https://github.com/landlab/landlab/pull/1985
