### ISSUE TITLE
Cell area array broken for Voronoi grids

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#201]
As reported by @SiccarPoint, the `cell_areas` array is broken. When trying to use the `cell_areas` attribute for Voronoi grids the following error is raised,
```python
AttributeError looking for _setup_cell_areas_array
```

**Comment by SiccarPoint** [comment]
I'm on this, @mcflugen, as part of a gentle (but necessary) overhaul of flow routing.

**Comment by SiccarPoint** [comment]
(The operation of forced_cell_areas was also basically wrong... This is what drew my attention in the first place)

**Comment by mcflugen** [comment]
I've actually already fixed it. I was just about to send a pull request. I didn't touch the `forced_cell_areas` stuff, though. The problem was that we were using both `cell_areas` and `area_of_cell` to get arrays of cell areas. I opted to switch to `area_of_cell`. It's easy enough to switch to another name but, at least for the moment, things are consistent.
