### ISSUE TITLE
Issue printing arrays when using numpy<2

### ISSUE THREAD

**Issue by davshus** [landlab/landlab#2018]
It looks like since #1956 was merged, landlab supports numpy v2. A change was introduced in https://github.com/landlab/landlab/commit/efcfe47bc5fd68d006d124778b1979ee4bdae831 which calls `np.set_printoptions(legacy="1.25")` in `__init__.py`. This legacy option was [added sometime after numpy 1.26.4](https://github.com/numpy/numpy/blob/9815c16f449e12915ef35a8255329ba26dacd5c0/numpy/core/arrayprint.py#L85-L96).

This results in the following breaking behavior after importing landlab (while using numpy 1.26.4, which is still supported according to pyproject.toml):

```
Python 3.10.15 | packaged by conda-forge | (main, Sep 30 2024, 17:51:04) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.arange(5)
>>> print(a)
[0 1 2 3 4]
>>> import landlab
/.../site-packages/landlab/__init__.py:38: UserWarning: legacy printing option can currently only be '1.13', '1.21', or `False`
  np.set_printoptions(legacy="1.25")
>>> print(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../numpy/core/arrayprint.py", line 1599, in _array_str_implementation
    if (_format_options['legacy'] <= 113 and
TypeError: '<=' not supported between instances of 'str' and 'int'
>>> np.__version__
'1.26.4'
```

Maybe landlab should bump the required version of numpy to 2.0, or check the numpy version before calling `set_printoptions`?

**Comment by mcflugen** [comment]
@davshus Thanks for reporting this and sorry for the trouble!

I hope that #2019 will fix this issue.
