### ISSUE TITLE
Flow routing, irregular grids, and internal closed nodes

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#203]
The way the router formerly handles nodes without cells was inconsistent between regular and irregular grids.
This needs to be resolved by ensuring no discharge can ever come from a node without a cell.

A related issue is that where closed nodes are present inside the grid, they get their own area, whereas more consistent with the above would be if they got zero.

Unit tests are needed, esp. for Voronoi and internal closed nodes.

**Comment by gregtucker** [comment]
I'm not sure I agree that internal closed cells should have a zero cell area. An app might want to treat them open for one process and closed for another (admittedly I'm struggling to think of an example).
