### ISSUE TITLE
Duplicated web structure

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#215]
I'm trying to update the web docs to be at least partially in line with new best practice... only to realise again that we're maintaining (& exposing to users) two parallel versions of the same documentation. I think they might already be starting to diverge. We need to fully commit to the wiki (if that is definitely our decision) & expunge the rst doc structure we have in landlab/docs - or remove the wiki - ASAP.

In the course of doing this I did however realise an advantage of the structure we have: because the web pages exist locally as a git repository on all our machines, updates in a search-and-replace fashion become totally straightforward. This is NOT the case for the wiki, where I'm struggling to work out how to check where we use SPEroder (...which I just replaced).

**Comment by jennyknuth** [comment]
Hi Dan, totally agree that we need to do away with duplication ASAP, it is not maintainable. And yes, transitioning to the wiki will be different and provide some functionality not available on readthedocs and vice versa. I agree it's been too long with the two parallel resources. I say lets commit to the wiki and comment out the readthedocs user guide (so we can go back if we do regret our decision) and replace it with a link to the wiki. I am happy to do this. I can make that quick change now but can't commit to more detailed restructuring until the end of the week.  

And the wiki is a repository that you can clone and push to. It doesn't show up automatically, but it is a repo just like any other on GitHub. Download link on the right. So, you can work on it locally and push changes. Does that help you with the updates? 

So tell me more about how you are updating and what functionality you need. I think a search bar is a great idea and after an initial search it looks like it is not impossible but also not straightforward. It would be nice for users to have a search bar (yes, hello GitHub!), but in the meantime, for us, I found this extension for searching GitHub wikis that looks super helpful if you use Chrome: https://chrome.google.com/webstore/detail/github-wiki-search/gdifdhnjmjaidbajhapmbcbnoocoeooc/reviews?hl=en.

Let me know of any other problems maintaining the wiki. One problem I have encountered is that GitHub rst is different from sphinx rst. Markdown and html work better on the wiki. But the rst we have does mostly work and ipython notebooks work. Like I said, they both have pros and cons.

**Comment by mcflugen** [comment]
@SiccarPoint: you can also clone the wiki to your desktop just like any other repository. It's just a bunch of GitHub ~~flavored~~ flavoured markdown files that you can do search and replaces with - just as you would with the old rst files.

**Comment by mcflugen** [comment]
Oops. What @jennyknuth said.

**Comment by SiccarPoint** [comment]
Ah, cool. I had totally missed that you can clone the wiki. That will totally do the job, and takes pressure off the urgent need for a search bar - from our perspective. Might be worth reaching out to the github guys to see if they have plans to add such a feature. Would save us work if it’s forthcoming, and would seem an obvious next step for them.

Re duplication, we just need to make sure that for now we duplicate *everything* out of the docs folder into the wiki. Lots is currently missing. We can re-organise/restructure/correct/refine it once it’s there. Looking at the wiki structure under the hood, there’s no inherent problem with maintaining some parts as RST and some in pure Github style… for now. We can iterate towards standardisation at our leisure. We can add new material in Github style, as appropriate.

D

**Comment by jennyknuth** [comment]
Okay, so assume that the wiki is the standard and the place for updates. I will go through and make sure that all the manually maintained content from readthedocs gets transferred to the wiki (basically that's the user guide). The doc-string stuff will stay in readthedocs in a new structure that should make things easier to find.

**Comment by SiccarPoint** [comment]
Sounds like a good plan to me.
