### ISSUE TITLE
set_fixed_link_boundaries_at_grid_edges()

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#217]
The method signature and docstring for this method no longer match. It's impossible to figure out how it works... I'm assigning Jordan, on the basis you have the best chance of figuring out what happened here, but no rush.

**Comment by jadams15** [comment]
got it! I'll take a peek at it but likely won't get to it until after AGU.

**Comment by jadams15** [comment]
Once pull request #234 is merged, this issue can be closed.

**Comment by jadams15** [comment]
I know this is going to drive you crazy - but once again, I am getting different results since you changed find_active_neighbors_for_fixed_links() again. I need to unit test this now. Maybe we hold off on merging until I can prove to myself which one is correct?

**Comment by mcflugen** [comment]
You're talking about #234? I didn't make any changes to `find_active_neighbors_for_fixed_links`. I added something to the docstring, but that should have been all.

**Comment by jadams15** [comment]
oh oops. too many windows open. yeah, you're right - I didn't merge in my changes back to the overland_flow component. I read that wrong. no matter. I'm still building a unit test now so it was a worthwhile mistake (and hopefully not a can of worms)
