### ISSUE TITLE
Node ordering in Voronoi

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#218]
If I'm seeing this right, the node ordering in Voronoi is still unstandardised. Should be y then x from the origin, right? At the moment, node order appears randomised.

Cheeky assignment to Greg, as he'll know.

**Comment by mcflugen** [comment]
It looks good to me. I think. I added the following doctest to `VoronoiDelaunayGrid`. Do you think this adequately tests this issue?
```python
>>> import numpy as np
>>> from landlab.grid import VoronoiDelaunayGrid
>>> x = [0, 0, 0, 0,
...      1, 1, 1, 1,
...      2, 2, 2, 2,]
>>> y = [0, 1, 2, 3,
...      0, 1, 2, 3,
...      0, 1, 2, 3]
>>> zip(x, y) # doctest: +NORMALIZE_WHITESPACE
[(0, 0), (0, 1), (0, 2), (0, 3),
 (1, 0), (1, 1), (1, 2), (1, 3),
 (2, 0), (2, 1), (2, 2), (2, 3)]
>>> vmg = VoronoiDelaunayGrid(x, y)
>>> zip(vmg.node_x, vmg.node_y) # doctest: +NORMALIZE_WHITESPACE
[(0.0, 0.0), (1.0, 0.0), (2.0, 0.0),
 (0.0, 1.0), (1.0, 1.0), (2.0, 1.0),
 (0.0, 2.0), (1.0, 2.0), (2.0, 2.0),
 (0.0, 3.0), (1.0, 3.0), (2.0, 3.0)]
```
The points are provided as "column major" but then reordered to be "row major".

**Comment by gregtucker** [comment]
Voronoi nodes should be numbered correctly in gtucker/sort-links, so as soon as we merge that branch we'll be good to go in master.
