### ISSUE TITLE
Fix add_zeros (etc.) for active links

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#22]
In the overland_flow_with_model_grid_dem.py example, the number of active links changes after the call to set_nodata_nodes_to_closed(). If you do

q = mg.create_active_link_array_zeros()

it recognizes the change. But 

q = mg.add_zeros('active_link', 'name')

uses the original number of active links, not the modified value.

**Comment by SiccarPoint** [comment]
I note that creating data on only active links is now not best practice, so hopefully this problem will go away on its own.

**Comment by gregtucker** [comment]
Guys, I'm going to close this issue---as Dan says, it isn't best practice, and I suspect that the recent work on updating grid data structures when BCs change will have fixed this anyway.
