### ISSUE TITLE
set_closed_boundaries_at_grid_edges: unsupported iterator index error

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#224]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-c9ac7a580a5b> in <module>()
      3 z[5] = 50.
      4 z[6] = 36.
----> 5 rg.set_closed_boundaries_at_grid_edges(False, False, True, True)  # needs updating
      6 print(z)

/Users/gtucker/Dev/Landlab/Clone/landlab/landlab/grid/raster.pyc in set_closed_boundaries_at_grid_edges(self, bottom_is_closed, left_is_closed, top_is_closed, right_is_closed)
   2510         --------
   2511         >>> from landlab import RasterModelGrid
-> 2512         >>> rmg = RasterModelGrid(4, 5, 1.0) # rows, columns, spacing
   2513         >>> rmg.number_of_active_links
   2514         17

IndexError: unsupported iterator index

**Comment by mcflugen** [comment]
@gregtucker, I'm having trouble reproducing this problem. Could you please provide the smallest code snippet that reproduces this error? Thanks!

**Comment by gregtucker** [comment]
With branch master, pulled this morning:

from landlab import RasterModelGrid

rg = RasterModelGrid(3, 4)

rg.set_closed_boundaries_at_grid_edges(False, False, True, True)
Traceback (most recent call last):

  File "<ipython-input-3-fb3e5530d5b7>", line 1, in <module>
    rg.set_closed_boundaries_at_grid_edges(False, False, True, True)

  File "/Users/gtucker/Dev/Landlab/Clone/landlab/landlab/grid/raster.py", line 2512, in set_closed_boundaries_at_grid_edges
    self._node_status[right_edge] = CLOSED_BOUNDARY

IndexError: unsupported iterator index

**Comment by mcflugen** [comment]
Something funny is going on. The following works just fine for me (on master and all up-to-date),
```python
>>> from landlab import RasterModelGrid
>>> grid = RasterModelGrid((3, 4))
>>> grid.set_closed_boundaries_at_grid_edges(False, False, True, True)
>>> grid.status_at_node
array([1, 1, 1, 1,
       1, 0, 0, 4,
       4, 4, 4, 4], dtype=int8)
```
The landlab version is,
```python
>>> import landlab
>>> landlab.__version__
'0.1.41'
```

**Comment by gregtucker** [comment]
Agreed!

>>> import landlab
>>> landlab.__version__
'0.1.41'
>>> from landlab import RasterModelGrid
>>> rg = RasterModelGrid(3, 4)
>>> rg.set_closed_boundaries_at_grid_edges(False, False, True, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gtucker/Dev/Landlab/Clone/landlab/landlab/grid/raster.py", line 2451, in set_closed_boundaries_at_grid_edges
    self._node_status[right_edge] = CLOSED_BOUNDARY
IndexError: unsupported iterator index


Gregorys-MacBook-Pro:grid gtucker$ python --version
Python 2.7.11 :: Anaconda 1.9.2 (x86_64)
Gregorys-MacBook-Pro:grid gtucker$ ipython --version
4.0.1



Gregorys-MacBook-Pro:grid gtucker$ git pull origin master
From https://github.com/landlab/landlab
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Gregorys-MacBook-Pro:grid gtucker$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

**Comment by mcflugen** [comment]
Maybe it's a problem with a dependency? What version of `six`, `numpy`, and `scipy` are you using? Those seem to be the most relevant.
```python
>>> import six
>>> six.__version__
'1.10.0'
>>> import numpy
>>> numpy.__version__
'1.10.1'
>>> import scipy
>>> scipy.__version__
'0.16.0'
```

**Comment by gregtucker** [comment]
It was a numpy version issue: for some reason, I had been running 1.8.2. When I upgraded to 1.10.2, via conda update numpy, the problem went away.
