### ISSUE TITLE
Docs: have __init__ docstring and function signature appear in readthedocs API doc

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#241]
When users get documentation for a class, such as a component, the class's __init__ method docstring should ideally appear. Yet it doesn't in the scraped files, probably because they are set up to ignore __magic__ sorts of functions.

**Comment by SiccarPoint** [comment]
Here’s a solution. You can either have the __init__ docs bolted onto the end of the class docstring, or have __init__ appear as a separate item in the methods list.

I would advocate for the former I think, as do we really want all our users to have to understand what an __init__ method is in order to use LL??

http://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method

**Comment by jennyknuth** [comment]
I looked into this, and yes, as Dan shows, it is easy to bolt the doc string from __init__ on to the end of the class docstring. However, this also includes a repeat of the autosummary of attributes and methods AND it looks like much of the __init__ documentation is redundant with the class docstrings anyway. 

So perhaps a better solution is to—from now on—document the __init__ method in the class docstring. The __init__ docstring can have as much information as you'd like, but if you want the info to be scraped, put it in the class docstring. Many of the classes already do this. For the ones that don't, I will go through and copy any non-redundant info from the __init__ methods into the class doc string. Greg thinks this won't take that long... But from now on, **the standard is to include __init__ documentation in the main class doc string**.

**Comment by mcflugen** [comment]
I agree. I very much like including the `__init__` documentation in the main class docstring. The main way I use docstrings is by typing, for example, `help(RasterModelGrid)`. The documentation about how to create the class is usually what I'm looking for and so is nice to have at the top.

**Comment by SiccarPoint** [comment]
+1 this. Good call.
