### ISSUE TITLE
Stream Power component: why do elevations sometimes INCREASE?

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#245]
I have a test case with a DEM drainage basin, and am using FastScapeStreamPower component. After one time step, some elevations *increase*. Stream power should ONLY lower elevations. Why is this happening?

@siccarpoint: I'll email you the files.

**Comment by SiccarPoint** [comment]
Addressed by #247. The answer was related to routing across lake flats where the lake floor gradient pointed upstream still (and was also an issue in the other SP component). This was resolved by 1. forbidding all elev increases in both components, and 2. allowing a flag to suppress changes beneath lakes entirely.
