### ISSUE TITLE
links_at_node on Voronoi

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#252]
This is busted. It shouldn't be. The method is looking for the property _links_at_node, which apparently doesn't exist/no longer exists (?) in the general case.

Anyone know what's going on here? I feel like this used to work. The method exists in base, which implies it used to be fine.

**Comment by gregtucker** [comment]
I've got work in progress on this in one of my branches

**Comment by SiccarPoint** [comment]
What's it looking like? Are you changing the basic form of the data structure? That could be problematic, as it's now pretty widely used in the mappers.

**Comment by SiccarPoint** [comment]
Resolved by pull #253 .
