### ISSUE TITLE
Fewer tests are running on Travis and AppVeyor than are locally

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#264]
Our CI testing on AppVeyor and Travis was not finding about 70 tests (mostly in the components folder) that are found when the tests are run locally. This most likely happens only for development versions of landlab (that is, landlab is installed in development mode with something like `python setup.py develop`).

I suspect this problem would also appear with any version of landlab installed with the usual `python setup.py install` - but I haven't actually tested that.

**Comment by SiccarPoint** [comment]
Temporary solution - make sure you run tests locally before committing, right?

**Comment by mcflugen** [comment]
Yes. Absolutely. That would work - but only for your local setup. It wouldn't catch problems that arise from different versions of Python, operating systems, etc.

In any case, #265 should fix this.
