### ISSUE TITLE
Accelerate KB's GIS slope methods

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#27]
Katy Barnhart has added GIS-style slope-aspect methods to LL. They're super useful, but slow (looped). Accelerate them.

**Comment by SiccarPoint** [comment]
mg.node_slopes(), mg.hillshade() supersedes much of this functionality. Will do for now.

**Comment by saisiddu** [comment]
But didn't we already have GIS styled slope and aspect routine. this method is called calculate_slope_aspect_at_nodes_Burrough(vals = 'Elevation'). This routine is in raster.py. Can we go through these routines and use one of them to avoid duplication?

________________________________

**Comment by SiccarPoint** [comment]
The functions I refer to above are generalised for all grids, so more powerful. I think they should give very similar solutions on a raster though. I lack the enthusiasm for cross-checking, but if you can face it, knock yourself out. I've not really used them much.

**Comment by SiccarPoint** [comment]
(I should also emphasise all these functions are pretty old, I was just trying to close old issues for neatness!)
