### ISSUE TITLE
Make a `width_of_face` property (replaces `face_width`)

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#291]
We agreed to use the terminology:

<attribute>_of_<element>

We now need to implement this change.

**Comment by SiccarPoint** [comment]
This might happen automatically when Eric merges his graph branch, so maybe don't commit to making these changes by hand until we see what he's covered...

**Comment by mcflugen** [comment]
Yes, I'm doing this. However, I think, we decided that it would be `length_of_face` so that it is consistent with `length_of_link`.

**Comment by SiccarPoint** [comment]
I think it’s width too.

**Comment by mcflugen** [comment]
Wait. It's easy for me to change but you're saying you want `width_of_link` and `width_of_face`?

**Comment by SiccarPoint** [comment]
No. IMO, links have length, faces have width. Because in all existing use cases, flux is link parallel, face transverse.

**Comment by gregtucker** [comment]
I understand the argument for consistency, and the fact that what we now call "face width" and "link length" are similar and complementary geometric entities, which will in fact occupy the same role in Eric's new graph-based representation of the dual components of a grid. Nonetheless, I agree with Dan on the use of both "length" and "width". It is more intuitive and in sync with common english usage of "length" to refer to one dimension of a thing, and "width" to another. In a sense, it is the more "literate" option, whereas using the same name would be the more "mathematical" option.

I gave a mini-lecture to the modelers the other day that got me thinking about Literate Programming in general. We don't do "formal" literate programming as originally defined (that would involve using a Python flavor of WEB as our programming language). But I'm proud of how good we've all been at being literate in the more general sense. For example, many of our functions/methods have docstrings that are much longer than the code. This is a strength we can continue to build on. Yay team!

**Comment by SiccarPoint** [comment]
We have this now.
