### ISSUE TITLE
gflex warning coming up when working on tutorial overland flow driver

### ISSUE THREAD

**Issue by kettner** [landlab/landlab#333]
Just want to report a warning, indicating that gflex isn't loaded when importing libraries defined in tutorial overland flow driver. See also screendump.
Fun playing though with landlab.
cheers, Albert.

![screen shot 2016-05-19 at 12 11 32 pm](https://cloud.githubusercontent.com/assets/7075202/15404514/0fa3fafa-1dbb-11e6-9c8b-18c79162a441.png)

**Comment by SiccarPoint** [comment]
Thanks @kettner !

**Comment by mcflugen** [comment]
This is fixed by #367.
