### ISSUE TITLE
Steepest descent methods in the grid

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#360]
The steepest descent methods still in place in the grid are a total mess, bad style, and extremely inefficient. Many are also only defined for Raster. This includes:
* find_node_in_direction_of_max_slope
* find_node_in_direction_of_max_slope_d4
* _calculate_steepest_descent_on_nodes

I believe these methods to be fundamentally unsalvageable. AFAIKT the only place these get used is in flow_routing_D8, which I believe was written by @nicgaspar. I want to just delete these methods, but can't until replacements for Nicole are in place. Thoughts, @nicgaspar ?

**Comment by nicgaspar** [comment]
If I wrote flow_routing_D8 it can be scrapped.  It’s super old and was replaced by your flow routing algorithm.

**Comment by SiccarPoint** [comment]
Awesome. I'll go for a "hard prune" then, as part of the branch I'm working on.

**Comment by SiccarPoint** [comment]
Resolved by #361
