### ISSUE TITLE
"OverlandFlowBates: unable to get input(/output) vars"

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#385]
Using the command line interface, any call to `landlab uses [field]` or `landlab provides [field]` gives the warning "Warning: OverlandFlowBates: unable to get input vars" (or "...output vars", as appropriate). The output that appears after the warning appears broadly correct, except it doesn't include info from the OverlandFlowBates component - as you'd expect from the warning.

I can't see any problem with the field interface as implemented in OverlandFlowBates.

@mcflugen : any ideas?

**Comment by SiccarPoint** [comment]
This is also relevant to @jadams15 .

**Comment by SiccarPoint** [comment]
Solved it. There were locally defined functions overprinting the inherited `input_var_names` and 'output_var_names` from `Component`. I removed them and everything passes (plus a tweak of the tests).

**Comment by SiccarPoint** [comment]
I'll finish it up.

**Comment by jadams15** [comment]
interesting... I also just looked into the Bates component and found a random stray letter in the middle of the code? I am curious how that didn’t cause a larger problem, buuuuuut whatever, fixed now?

**Comment by SiccarPoint** [comment]
weird!

**Comment by SiccarPoint** [comment]
Also, just noticed the "Base et al." typo sitting right there in the first line of the docstring. Good times!

**Comment by mcflugen** [comment]
@jadams15 that "u" is (or, rather, was) important. Sometime in the past that particular docstring must have contained unicode characters.

**Comment by mcflugen** [comment]
@jadams15: after the new docs build on RTFD, have a look at the documentation for `OverlandFlowBates` and make sure it looks like it should.

**Comment by SiccarPoint** [comment]
(I just reinstated the unicode `u`, as there seemed little harm)

**Comment by jadams15** [comment]
just saw all this... my mistake. sorry. so many things I just don’t know!
