### ISSUE TITLE
Create `calc_flux_div_at_face`?

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#409]
At present we have `calc_flux_div_at_node` but no `calc_flux_div_at_face`. Should we create `calc_flux_div_at_face`?

This issue came up because I recently modified the decorator `@use_field_name_or_array` so that it checks that the array it is passed is the size of the sort of element it is expecting (if it is passed and array instead of a field name). (see Issue #410 regarding modifying this decorator).

This resulted in two errors which occurred because `calc_flux_div_at_node` was passed an array at face. My inclination is that a new function `calc_flux_div_at_face` should exist. 

thoughts?

**Comment by mcflugen** [comment]
The `calc_flux_div_at_node` function does return values at *nodes*, so I guess the name as-is is correct and we don't need another function.

The question, then, is where should the unit fluxes that are input to this function be defined. I'm not totally sure how this should work but it seems like when calculating flux divergence at nodes, we should be using *links* not *faces*. If we were using *faces* would not the appropriate function be `calc_flux_div_at_corner`?

I just talked with @gregtucker about this and I think he agrees.

I would suggest changing `calc_flux_div_at_node` to only take values at *links*, not faces.

**Comment by mcflugen** [comment]
In `calc_flux_div_at_node` we're really calculating flux divergence at *cells*, not *nodes* (*nodes* don't have area). Another option is to have a function `calc_flux_div_at_cell` that takes an array of fluxes at links and returns an array of length *n_cells* long. These values could then be mapped to *nodes* if that's what the user is wanting.

To me this is more clear but may be inconvenient to users who like to have all their values defined at nodes rather than cells.

**Comment by kbarnhart** [comment]
Pull request  #411 addresses this issue.

**Comment by SiccarPoint** [comment]
I'd say stick with convenience over precision here. This also is a very user-facing method, which appears in at least one tutorial that has been repeatedly advertised as a good one to do. The return array is nodes-long, so I think `calc_flux_div_at_node` is the right terminology. If we want to add `calc_flux_div_at_node` alongside it, I'd be fine with that too.

The underlying rationale was what @mcflugen is alluding to - links join nodes, so it should be defined at nodes. Cells would be one step removed from this (and require the user to maintain data on two elements, which is annoying and weird). Defining these fluxes "on faces" per se is a bad idea, as (per Eric) they link corners. If @kbarnhart you're alluding to the need to be able to do these calcs on only some subset of the links, then we're back at an old impasse over whether these flux functions should only solve on active links, or on all links. I believe we are still calculating the fluxes on all links not active links, so it's up to the user to not screw this up.

Another option might be to add a keyword flag (defaulting to what we have now) to alter the internal behaviour (again, defaulting to the current behaviour), but that might just be confusing. (Maybe we already do this, looking at the existing code?)

**Comment by kbarnhart** [comment]
I agree that we shouldn't make `calc_flux_div_at_cell`. Incorrect and confusing. 

As far as I can tell there are two outstanding questions

1) Should the decorator `@use_field_name_or_array` check the size of the array it is passed. 

and

2) Should `calc_flux_div_at_node` be able to handle being passed both (a) fluxes on all links or (b) fluxes only on links where there is a face. 

My inclination is that the answer to 1) is Yes and the answer to 2) is (a) but not (b). 

An additional option would be to allow the decorator to be given more than one element name. 
e.g. `@use_field_name_or_array(('node','link')) would indicate that the array passed must be either length `number_of_nodes` or length `number_of_links`. My first thought on this, however, is that it is a bad idea because you then have two sets of fields dicts to check if a string is passed...

But let's discuss this on our conference call in 1 hour!

I've looked at the tutorials and I see this function referenced in these two tutorials:
https://nbviewer.jupyter.org/github/landlab/tutorials/blob/master/gradient_and_divergence/gradient_and_divergence.ipynb and https://nbviewer.jupyter.org/github/landlab/tutorials/blob/master/fault_scarp/landlab-fault-scarp.ipynb

in these the flux divergence is calculated by passing the flux at all links, so I'm not sure there is an issue in removing the ability to pass only the flux at faces. Let me know if I'm missing something. 

Am I correct to assume that the notebook tutorials are run as part of the `python test-installed-landlab.py`?

**Comment by mcflugen** [comment]
I actually think we *should* (also) have a `calc_flux_div_at_cell`. In fact, I think it is more correct and less confusing! Flux divergence is the total flux entering a cell (via links) divided by the cell area. Since nodes don't have area, it doesn't really make sense to calculate at nodes - particularly for perimeter nodes, which don't have associated cells.

I hate to add more keywords but maybe `calc_flux_div_at_node` should have a keyword that gives the value to use as flux divergence at perimeter nodes? Right now it's just 0., which is probably correct for most cases.

**Comment by kbarnhart** [comment]
A short summary of the discussion from today's conference call (and I'm adding Sai and Nicole as Assignees so this pops up in their threads). 

Let me know if the following is not what you remember. 

1) We want `calc_flux_div_at_node` to only work for arrays of length `number_of_links`.
2) We want to create a parallel function to `calc_flux_div_at_cell` that will only operate on arrays of length `number_of_faces` (and will operate not on the faces, but on the `links_at_face`. 
3) We don't want to check the size of arrays in the decorator `@use_field_name_or_array` because functions that use this decorator are called many times and this will add to the computational load of running them. 

Once  I hear what you all think, I can go ahead and make these changes to this branch.

**Comment by saisiddu** [comment]
Sounds good to me! Should I merge this on GitHub?

________________________________

**Comment by kbarnhart** [comment]
I wouldn't merge yet. At the moment the commit associated with this pull request does (1) but not (2) or (3). Regarding (3) it does include the length check.  

Depending on what people want I'll modify the branch.
