### ISSUE TITLE
Should @use_field_name_or_array check the size of the array it is passed?

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#410]
@use_field_name_or_array does not presently check the size of the array it is passed to ensure that the array is `number_of_elements` long.

**Comment by kbarnhart** [comment]
#409

**Comment by kbarnhart** [comment]
Pull request #411 addresses this issue.

**Comment by kbarnhart** [comment]
This past Monday's meeting came down on the side of **no this functionality should not exist** primarily because it would add another step in a frequently used method and thus increase computation time.

**Comment by nicgaspar** [comment]
Katy - This is fine with me although it seemed counter-intuitive to me at first.

I know you tagged me as a reviewer earlier. Do you want me to look at something?
nic

**Comment by kbarnhart** [comment]
Hey @nicgaspar I've just made all of the changes summarized in issue #409 (PR #411). I'm happy for anyone to review it. I assigned you and Sai so that you would know what progress occurred after our discussion (not sure if there is a way to list people as in-the-loop without assigning them).
