### ISSUE TITLE
set_watershed_boundary_condition breaks if the grid has two nodes with the minimum value 

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#425]
the raster function `set_watershed_boundary_condition()` doesn't handle the case in which the grid has two nodes with the minimum value. It throws the following error if this is the case.

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-9f7194105aab> in <module>()
      7 # set_watershed_boundary_condition() and it would find it.
      8 
----> 9 outlet=grid.set_watershed_boundary_condition(z, nodata_value=-9999.,)
     10 grid.set_closed_boundaries_at_grid_edges(True, True, True, True)

/Users/katybarnhart/git/landlab/landlab/grid/raster.py in set_watershed_boundary_condition(self, node_data, nodata_value, return_outlet_id, remove_disconnected, method)
   5272             i = 0
   5273             while (i < len(min_locs) and local_not_found):
-> 5274                 if self.has_boundary_neighbor(min_locs[i]):
   5275                     local_not_found = False
   5276                     # outlet_loc contains the index of the outlet location

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()```


This came up in a test dem that @saisiddu shared with me.

**Comment by jadams15** [comment]
So in this case there are two core nodes adjacent to boundary nodes, with the same elevation values? Is this one delineated watershed?

**Comment by saisiddu** [comment]
Yes, this is a delineated watershed.
________________________________

**Comment by jadams15** [comment]
thanks, just making sure I understand the issue! I can see this being problematic. Do you know if the two "outlet"/min value elevations are next to each other?

**Comment by saisiddu** [comment]
Yes, they are connected. The watershed itself was a little problematic at first. But, after using the DepressionFinder correctly, the router behaved well.
________________________________

**Comment by kbarnhart** [comment]
In Sai's watershed they are adjacent (node ids: 1389 and 1390).

**Comment by kbarnhart** [comment]
See PR #426 
That fixes this issue

There are, however some outstanding issues in _how to handle_ this sort of issue. 

I'll tag you in that PR @jadams15 and suggest we discuss how to handle it in that PR instead of here.

**Comment by kbarnhart** [comment]
[hugows10mpitf.txt](https://github.com/landlab/landlab/files/700113/hugows10mpitf.txt)
So we have @saisiddu 's raster in this issue thread I'm attaching it now.

**Comment by kbarnhart** [comment]
@saisiddu @jadams15 I think I can close this, right?

**Comment by saisiddu** [comment]
Yes! I haven't checked if it's working recently but I assume it would. It worked after you solved it after the issue was created.
________________________________

**Comment by jadams15** [comment]
I think this is good to close!
