### ISSUE TITLE
active_link_dirs_at_node not updating properly

### ISSUE THREAD

**Issue by jadams15** [landlab/landlab#428]
So, I ran into a bug(?) in a highly specific boundary condition case. If we change a closed node (status == 4) to an open boundary (status == 1), the boundary status in the grid is updated, but the active_link_dirs_at_node are not updating properly. 

A use case for this would be a grid with closed perimeter nodes with one open boundary outlet on the edge, like the grid below:
X X X X
X C C X
X C C X
X O X X

Where the outlet_id is node 1, and the link between the outlet and it's north neighbor is link id 4.

A code snippet to describe the issue I'm seeing:

First, I'll set the grid edges to closed. The status of node 1 and link 4 is set to closed/inactive (or status == 4). All links out of node 1 are inactive, so all active_link_dirs_at_node are 0. 

```
>>> rmg = RasterModelGrid(4, 4)
>>> rmg.set_closed_boundaries_at_grid_edges(True, True, True, True)
>>> rmg.status_at_node[1]
4
>>> rmg.status_at_link[4]
4
>>> rmg.active_link_dirs_at_node[1]
array([0, 0, 0, 0], dtype=int8)
```

Then I'll update the outlet to be an open boundary, and the link 4 status is updated to ACTIVE. BUT the active_link_dirs_at_node are *not* updated. 

```
>>> rmg.status_at_node[1] = 1
>>> rmg.status_at_link[4]
0
>>> rmg.active_link_dirs_at_node[1]
array([0, 0, 0, 0], dtype=int8)

```
This seems like abnormal behavior. I *believe* that the CORRECT array for rmg.active_link_dirs_at_node[1] should return an array of:
`array([0, -1, 0, 0], dtype=int8)`

I think what's happening is that changing the node status from OPEN->CLOSED->OPEN does not update the active_link_dirs_at_node arrays. This seems... wrong. I tried to fix and failed/broke a lot of different unit tests. 

Insight appreciated!

(Also, as a side note, to explain how I found this issue: I created a steady-state landscape using the FlowRouter/StreamPowerEroder components, starting from random noise. Output as an ascii file. When I read it back in, the workflow:

```
>>> rmg.set_closed_boundaries_at_grid_edges(True, True, True, True)
>>> rmg.status_at_node[1] = 1

```
seemed most intuitive for me to reset the boundary conditions given random noise on the edges - can't use NODATA nodes unless I changed the values on those edge nodes).

**Comment by jadams15** [comment]
I tagged @gregtucker because I believe you most recently worked on this section of code? and @mcflugen because you're a wizard with the grid. 

I think a lot of the problem lies in the fact that these arrays are set within some Cython code, which admittedly, I am not super familiar with.

**Comment by gregtucker** [comment]
Thanks for catching this @jadams15. I'm currently flat out on another project for the next few days, so I think the earliest I can look at this would be Tuesday afternoon. So if someone else has time and motivation before then, go for it! :)

**Comment by jadams15** [comment]
certainly no rush on this - I am out of the office through Monday anyway. thank you!

**Comment by jadams15** [comment]
Another update - this is a problem in `set_watershed_boundary_condition` too, so even with NODATA nodes provided. 

So, a test case...

# creating a highly simplified grid, with NODATA on perimeter except for outlet node.
```
>>> mg = RasterModelGrid(4, 4)
>>> z = np.ones(mg.number_of_nodes)
>>> z[mg.nodes_at_bottom_edge] = -9999.
>>> z[mg.nodes_at_left_edge] = -9999.
>>> z[mg.nodes_at_top_edge] = -9999.
>>> z[mg.nodes_at_right_edge] = -9999
>>> z[1] = 0.5
```

# Checking active link dirs at node [1], the outlet...
```
>>> mg.active_link_dirs_at_node[1]
array([ 0, -1,  0,  0], dtype=int8)
```

# Running set_watershed_bdy...
`>>> mg.set_watershed_boundary_condition(z)
`
# Checking active link dirs at node [1], the outlet after boundary condition update
```
>>> mg.active_link_dirs_at_node[1]
array([0, 0, 0, 0], dtype=int8)
```

This is problematic, because in some of our deprecation warnings we actually suggest the user take link values, and plot them on nodes using some form of:
`link_vals[grid.links_at_node]*active_link_dirs_at_node`

and at the outlet, EVEN IF there is an OPEN BOUNDARY with an ACTIVE LINK attached, the changing boundary status sets that active_link_dir to 0. So multiply anything by 0 and you're losing data on the edge of the grid. 

I noticed this as I am trying to evolve my landscapes using OverlandFlow on scales of 10^4. Because the active link and attached core node have a active_link_dur of 0, the core node was not incising, thus creating pits upstream of the outlet...
