### ISSUE TITLE
documentation missing in 'latest' branch, time for a new release or new work flow?

### ISSUE THREAD

**Issue by jennyknuth** [landlab/landlab#435]
Due to a typo, the default 'latest' branch of the documents is missing much of the section on rectangular grids. The typo has been fixed, so perhaps it is time to do another release so the docs are in sync? Or maybe there is a better workflow to sync the docs if a release is not warranted at this time.

**Comment by mcflugen** [comment]
I think it might be easiest to create a new branch off of `release` to fix the docs. Once fixed, this branch can then be merged into `release` (and also into `master`). Do you think that make sense?

**Comment by jennyknuth** [comment]
Yeah, that does make sense, so docs branch off of release in future, not off of master. That's a good idea for the docs to stay in sync with the release. Will do!
