### ISSUE TITLE
ipython and landlab not working in conda virtual environment

### ISSUE THREAD

**Issue by BenjiDa** [landlab/landlab#441]
Hi all,
I installed landlab in a conda virtual environment via: `conda install landlab -c landlab`
as shown in this [issue](https://github.com/landlab/landlab/issues/440)

When i import landlab in python (python installed in the virtual environment) it works fine, when i import landlab in ipython (also installed in the conda virtual environment) it errors: `ImportError: No module named landlab`
I have not tried this in jupyter notebook yet. Still getting up and running. 

Thanks

**Comment by mcflugen** [comment]
Did you install `ipython` in your virtual environment?

If you run the following commands, do you get paths to python and ipython that are in your virtual environment?
```bash
$ which python
$ which ipython
```
My guess is that the second point to your base Anaconda install location. Is that right? If so, you just need to install ipython into your virtual environment.

The following works for me:
```bash
$ conda create -n landlab-env python=2.7
$ source activate landlab-env
$ conda install landlab -c landlab
$ conda install ipython
$ python -c 'import landlab'
$ ipython -c 'import landlab'
```

**Comment by BenjiDa** [comment]
Both python and ipython are installed inside the virtual environment with conda install

```
/Users/myname/anaconda2/envs/sandbox/bin/python
/Users/myname/anaconda2/envs/sandbox/bin/ipython
```

I uninstalled and tried installing via pip, same problem. Strange.

**Comment by mcflugen** [comment]
That is weird. Is your `sys.path` the same in both python and ipython? Or more importantly, is the path to your landlab install (`/Users/myname/anaconda2/envs/sandbox/lib/python2.7/site-packages`) in `sys.path`?
```bash
$ python -c 'import sys; print sys.path'
$ ipython -c 'import sys; print sys.path'
```
Have you set any ipython configuration options (or environment variables, `PYTHONPATH`, `DYLD_LIBRARY_PATH`, etc.) that might relate to your `PYTHONPATH`?

If you start ipython with the `--quick` option, it should start without reading any configuration files. How about try:
```bash
$ ipython --quick
In [1]: import landlab
```
Anything?

**Comment by BenjiDa** [comment]
`ipython --quick import landlab` works
it looks like i have to add it to the sys.path

Thanks

**Comment by mcflugen** [comment]
Cool. This seems to indicate that somewhere along the way you've changed some ipython configuration options (perhaps through Jupyter) that is causing problems.

You shouldn't really ever have to set `sys.path` (or `PYTHONPATH`). You may want to look at your ipython settings to try to really fix this problem. One easy thing to try is to simply remove (or, to be safe, rename) your `~/.ipython` folder (all your profile settings are in there). If you do that, the next time ipython starts it will create a new `.ipython` folder with factory settings, which should work for you. Of course, you would then lose any current settings that you may want.

**Comment by BenjiDa** [comment]
Yes, i just deleted that folder and on restarting ipython i was able to import landlab no problems. Not sure how or when the ipython configuration got changed.
Thanks for your help
