### ISSUE TITLE
Not compatible with Python 3.6

### ISSUE THREAD

**Issue by bpmurphy** [landlab/landlab#446]
I installed Anaconda & Landlab on a machine yesterday. The newest version of Anaconda now comes with Python 3.6. When I went to install Landlab, I received an incompatibility error message. I apologize for not copying down the error, but it said Landlab was compatible with python 3.5 but not python 3.6. I was able to circumvent the issue by returning to Terminal and typing:

conda install python=3.5.0

Landlab then installed without a problem. I'm not sure the reason for the incompatibility, but given this will be an issue for anyone downloading Anaconda for the first time, I thought I'd share. I realize 3.6 was just released before the new year, but in case this takes some time to figure out, it might be helpful to add this simple workaround to the install instructions.

**Comment by mcflugen** [comment]
Thanks, @bpmurphy. What steps did you take to try to install landlab?

**Comment by bpmurphy** [comment]
I followed the instructions found at @ https://github.com/landlab/landlab/wiki/Installing-Landlab-with-Anaconda

I updated conda and setuptools, installed netCDF4, and then went to install landlab, typing the following into Terminal:

conda install landlab -c landlab 

But it failed to install with a message that landlab worked with 3.5, but I had 3.6. So after downgrading to 3.5, as I described before, the install worked fine and I was able to verify the install as outlined in the site above.

**Comment by mcflugen** [comment]
Perfect. Thanks, @bpmurphy. We just need to build a new release of landlab for Python 3.6. It shouldn't be a problem.

**Comment by bpmurphy** [comment]
@mcflugen 
Update: previous issue was with install on a Mac. That install was ultimately successful. However, now with attempted landlab install on a PC (after installing newest version of Anaconda), I encountered the same python 3.6 incompatibility issue, with the error in command prompt (copied this time):

C:\Users\bpmurp>conda install landlab -c landlab
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - landlab -> python 3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

So I attempted the same workaround as before (installing python 3.5). Afterwards I no longer get the above incompatibility error, but instead it returns:

C:\Users\bpmurp>conda install landlab -c landlab
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\bpmurp\Anaconda3:

The following NEW packages will be INSTALLED:

    landlab:            1.0.2-np110py35_0  landlab

The following packages will be UPDATED:

    scikit-image:       0.12.3-np111py35_1         --> 0.12.3-np110py35_1

The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.4.3-py35_0               --> 1.2.3-py35_0
    astropy:            1.3-np111py35_0            --> 1.1.2-np110py35_0
    bottleneck:         1.2.0-np111py35_0          --> 1.0.0-np110py35_1
    h5py:               2.6.0-np111py35_2          --> 2.6.0-np110py35_0
    jpeg:               9b-vc14_0                  [vc14] --> 8d-vc14_2          [vc14]
    libtiff:            4.0.6-vc14_3               [vc14] --> 4.0.6-vc14_2       [vc14]
    llvmlite:           0.16.0-py35_0              --> 0.11.0-py35_0
    matplotlib:         2.0.0-np111py35_0          --> 1.5.1-np110py35_0
    netcdf4:            1.2.4-np111py35_0          --> 1.2.2-np110py35_0
    numba:              0.31.0-np111py35_0         --> 0.26.0-np110py35_0
    numexpr:            2.6.2-np111py35_0          --> 2.4.6-np110py35_0
    numpy:              1.11.3-py35_0              --> 1.10.1-py35_0
    pandas:             0.19.2-np111py35_1         --> 0.18.1-np110py35_0
    pillow:             4.0.0-py35_1               --> 3.4.2-py35_0
    pyqt:               5.6.0-py35_2               --> 4.11.4-py35_7
    pytables:           3.2.2-np111py35_4          --> 3.2.2-np110py35_1
    qt:                 5.6.2-vc14_3               [vc14] --> 4.8.7-vc14_9       [vc14]
    qtconsole:          4.2.1-py35_2               --> 4.2.1-py35_0
    scikit-learn:       0.18.1-np111py35_1         --> 0.17-np110py35_1
    scipy:              0.18.1-np111py35_1         --> 0.16.0-np110py35_0
    statsmodels:        0.8.0-np111py35_0          --> 0.6.1-np110py35_1

Proceed ([y]/n)?

However, when I proceed, I get the error:

CondaError: CondaHTTPError: HTTP 522 ORIGIN CONNECTION TIME-OUT for url <https://repo.continuum.io/pkgs/free/win-64/llvmlite-0.11.0-py35_0.tar.bz2>
Elapsed: 00:15.333826
CF-RAY: 33863fdaf90a6d0c-SJC

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
HTTPError('522 Server Error: Origin Connection Time-out for url: https://repo.continuum.io/pkgs/free/win-64/llvmlite-0.11.0-py35_0.tar.bz2',)

I retried multiple times without success. I then tried directly installing llvmlite 0.11.0 using:

conda install llvmlite=0.11.0

This looks for the package at the same url as above though and returns the same error. Checking for llvmlite packages on conda, it appears the version necessary to run landlab (0.11.0) is not available through conda:

anaconda search -t conda llvmlite
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     aetrial/llvmlite          |          | conda           | linux-64, osx-64
                                          : A lightweight LLVM python binding for writing JIT compilers
     anaconda-backup/llvmlite  |   0.16.0 | conda           | linux-64, win-32, win-64, linux-32, osx-64
     anaconda/llvmlite         |   0.16.0 | conda           | linux-64, win-32, win-64, linux-32, osx-64
     antoine/llvmlite          | 0.8.0.dev | conda           | linux-64, win-32, win-64
                                          : A lightweight LLVM python binding for writing JIT compilers

I also tried downloading the llvmlite 0.11.0 package onto my machine to attempt an local install, but I find that approach is not working either. My next step is going to be to try to download an older version of Anaconda. I will update on the outcome.

**Comment by mcflugen** [comment]
Thanks, @bpmurphy. We now have a version that works with Python 3.6 on Mac/Linux/Windows. We've yet to release it yet but were planning to do so in the next few days. Is that OK, or are you need something sooner?

**Comment by bpmurphy** [comment]
Great. I can wait. Will you announce the release? If not, can you please let me know when it is out?

**Comment by mcflugen** [comment]
@bpmurphy: We've released landlab v1.0.3, which provides a build for Python 3.6. Please give it a try and let us know how it goes.
