### ISSUE TITLE
netCDF byte encoding issue?

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#455]
Recently wrote out a netCDF with write_netcdf and then read it back in with read_netcdf as part of a multi-step modeling workflow. 

After reading the netcdf back in, I ran set_watershed_boundary_conditions on it, and then the FlowRouter. 

FlowRouter initialized, when I run route_flow() I get the following error:

```python

  File "<ipython-input-11-2505789182c2>", line 3, in <module>
    fr.route_flow()

  File "/Users/katybarnhart/git/landlab/landlab/components/flow_routing/route_flow_dn.py", line 369, in route_flow
    baselevel_nodes=baselevel_nodes)

  File "/Users/katybarnhart/git/landlab/landlab/components/flow_routing/flow_direction_DN.py", line 206, in flow_directions
    steepest_slope)

  File "landlab/components/flow_routing/cfuncs.pyx", line 15, in landlab.components.flow_routing.cfuncs.adjust_flow_receivers (landlab/components/flow_routing/cfuncs.c:1718)

ValueError: Big-endian buffer not supported on little-endian compiler
```

A cursory check of the dtype of each at_node field for the grid that wrote the netcdf and the grid created by reading the netcdf indicates that they are all the same. 

I was able to remove the problem in my workflow by writing the file out as an ascii text grid. That is to say that writing it out the same data as ascii, reading it back in later, and running flow router on the read-back-in data produced no problems. 

This leads me to suspect that the error is coming from a netcdf byte ordering issue that isn't playing nice with the compiled cython adjust_flow_receiver routine.  Googling provides a bit of support for this hypothesis (https://pandas-docs.github.io/pandas-docs-travis/gotchas.html#byte-ordering-issues).

**Comment by kbarnhart** [comment]
perhaps someone knows if one of the netcdf formats 

format : {‘NETCDF3_CLASSIC’, ‘NETCDF3_64BIT’, ‘NETCDF4_CLASSIC’, ‘NETCDF4’}

would fix this sort of problem?

**Comment by mcflugen** [comment]
@kbarnhart could you please give a minimal example that reproduces the problem?

**Comment by kbarnhart** [comment]
Here is a minimal example that reproduces the error on my computer.

```python
landlab import RasterModelGrid
from landlab.io.netcdf import write_netcdf, read_netcdf
from landlab.components import FlowRouter

import numpy as np

# create a grid, and run flow router on it
grid = RasterModelGrid((10,10))
z = grid.add_field('topographic__elevation', np.random.randn(10,10))

# this doesn't break
fr = FlowRouter(grid)
fr.run_one_step()

# write out the grid, and read it back in
filename = 'test_out.nc'
write_netcdf(filename, grid, names=['topographic__elevation'])
grid2 = read_netcdf(filename)

# initalize the flow router on the new grid, this one breaks with
# ValueError: Big-endian buffer not supported on little-endian compiler
fr2 = FlowRouter(grid2)
fr2.run_one_step()
```

**Comment by mcflugen** [comment]
It doesn't exactly fix your problem but if you use the NetCDF4 writer, it will work.

To do this, replace
```python
write_netcdf(filename, grid, names=['topographic__elevation'])
```
with
```python
write_netcdf(filename, grid, names=['topographic__elevation'], format='NETCDF4')
```
It seems that `scipy.io` writes and reads your data as big-endian and doesn't convert it to native format when reading it back in. You can see this in your `z` array. Before you read from the NetCDF file,
```python
>>> z.dtype.byteorder
'='
```
but after you read it back in,
```python
>>> z.dtype.byteorder
'>'
```

**Comment by kbarnhart** [comment]
Thanks @mcflugen! This fixed the issue for me.
