### ISSUE TITLE
map_max_of_inlinks_to_node vs. map_sum_of_inlinks_to_node?

### ISSUE THREAD

**Issue by amanaster2** [landlab/landlab#470]
Hi, I'm looking into OverlandFlow examples and was wondering why would one map the maximum value of in-links to a node and not the total. Is there a rationale behind using the maximum rather than the sum?

Thanks,
Amanda Manaster
Erkan's Ecohydrology Lab

**Comment by kbarnhart** [comment]
Hi @amanaster2,
Thanks for asking the question. I suspect @jadams15 will be the best person to answer it since she is the main developer of the Overland Flow component. 
Cheers,
Katy

**Comment by jadams15** [comment]
Hi @amanaster2, it sounds like that might be an older code - which one are you currently using? I poked around a bit and can't seem to track it down. There is a method in OverlandFlow that takes into account the sum of all links flowing into a node (not just inlinks or outlinks, actually takes directionality into account), called discharge_mapper(). It sounds like this is what you want. Do you have a copy of the OverlandFlow paper? I can send you a polished version if needed, as that has a sample algorithm. Let me know if you have more questions! and please let me know where you're seeing that so I can fix it.

**Comment by amanaster2** [comment]
Hi @jadams15, you're right --- it was an older code! I was looking at the Landlab OverlandFlow Component Users Manual (https://github.com/landlab/landlab/wiki/OverlandFlow-Component-Users-Manual --- See Step 7. Iterate through time)... I realize now that the algorithm in the OverlandFlow paper has discharge_mapper(). Thanks for the clarification!

**Comment by jadams15** [comment]
I am going to fix that immediately. thank you for following up!

A few other notes, so you can make the best decision for your purposes:
1) There is a large suite of raster mappers here: https://github.com/landlab/landlab/blob/master/landlab/grid/raster_mappers.py

2) When I couple my OverlandFlow component with and erosion module, I don't use discharge mapper, I instead use the max flow rate so I can tie it to a specific (max) slope. These examples are in the manuscript repository: https://github.com/landlab/pub_adams_etal_gmd

Do you mind if I go ahead and close this issue?

**Comment by amanaster2** [comment]
Yes, go ahead and close this issue! Thank you for your help!!

**Comment by jadams15** [comment]
no problem! keep me posted as you progress the component. happy to help!
