### ISSUE TITLE
1 failure and 2 errors when running landlab.test()

### ISSUE THREAD

**Issue by amanaster2** [landlab/landlab#508]
After uninstalling and reinstalling the developer version of Landlab earlier today, I ran landlab.test() and I received 1 failure and 2 errors, all of which were related to reading and writing netcdf files in Landlab (see below).

![image](https://user-images.githubusercontent.com/26778806/27810580-10bbb1fa-6011-11e7-9b54-6b1a1b008e72.png)
![image](https://user-images.githubusercontent.com/26778806/27810578-00b103a0-6011-11e7-9aa3-7a8a3588051e.png)

This has been an issue every time I've run landlab.test(), I just didn't think to create an issue until @saisiddu suggested it. Have any other users experienced a similar issue? Any thoughts/suggestions/tips are greatly appreciated!

Thanks,
Amanda

**Comment by mcflugen** [comment]
@amanaster2: It appears to be a problem with netcdf4 on your machine. Could you try the following,
```python
>>> import netCDF4
```
* Do you get an error or does `netCDF4` import successfully?
* What version of `numpy` do you have installed?
* It looks like you are on Windows, is that correct?

**Comment by amanaster2** [comment]
@mcflugen: 

- I get an ImportError when I try to import netCDF4. (DLL load failed: The specified module could not be found.)
- I have numpy 1.12.1
- That is correct -- I am on Windows

**Comment by mcflugen** [comment]
Thanks, @amanaster2. The problem is not a landlab problem but a netcdf problem. I'm having trouble reproducing your error but I suspect it has to do with a version of one of your packages being built with an old jpeg library (8d vs. 9b). What version of jpeg do you have installed?

You may want to try updating your version of anaconda (with `conda update --all`) and see if your packages that use the old library are updated to use the new one. If that fails, try downgrading your version of jpeg to something less than 9.

**Comment by mcflugen** [comment]
@amanaster2, it would also be helpful if you run both `conda info` and `conda list` and paste the results here.

**Comment by amanaster2** [comment]
@mcflugen I apologize for the delayed response --- The notification email got lost among the myriad emails in my inbox...

jpeg version is 8d

```conda info```
![image](https://user-images.githubusercontent.com/26778806/28035876-0989faea-656b-11e7-87fd-84c7f39ba189.png)

```conda list```
![image](https://user-images.githubusercontent.com/26778806/28035960-4c9810d8-656b-11e7-8abe-11bc2b88cb52.png)
![image](https://user-images.githubusercontent.com/26778806/28035973-5fcac2ea-656b-11e7-87b9-7aeedcac624b.png)
![image](https://user-images.githubusercontent.com/26778806/28035993-7057c946-656b-11e7-99f3-dfa92d8b8b25.png)
![image](https://user-images.githubusercontent.com/26778806/28036013-826ff504-656b-11e7-8cfa-e85456cf2ecf.png)
![image](https://user-images.githubusercontent.com/26778806/28036028-91537bea-656b-11e7-92a9-3df25cc22679.png)

**Comment by fzeng2** [comment]
i have  downgraded my version of jpeg to 8.0 and 7.0, but both of them did not work.

**Comment by mdpiper** [comment]
Verified that all Landlab tests are currently passing on Windows.
