### ISSUE TITLE
Can't import any landlab component into spyder

### ISSUE THREAD

**Issue by Carralex** [landlab/landlab#538]
Hi, 
I was able to run landlab into my spyder (I've installed it on a developper mode on my mac machine) and I coud import any landlab components. But a recent bug appeared (I've attached the message error) and anytime I'm trying to import a component there is this message error. I seems there is a bug into the .cfuncs file to import the brent_method_erode_variable_threhold method. Note that I can import landlab into spyder and I already re-running python setup.py develop a few times. 
Do anyone has an idea where the bug could come from ?

Thank you in advance,
Alexandra

**Comment by Carralex** [comment]
![capture d ecran 2017-08-24 a 15 30 37](https://user-images.githubusercontent.com/17542220/29670185-328e5d16-88e6-11e7-982f-34cfd8539e59.png)

**Comment by SiccarPoint** [comment]
What files are in your folder `landlab/landlab/components/stream_power` that start with `cfuncs`? If you could also report the "date modified", that might help.

**Comment by SiccarPoint** [comment]
Another thing: how are you running landlab in python? Are you using ipython or Spyder or another GUI, or are you running just simply `python [yourfile.py]` in the terminal?

**Comment by mcflugen** [comment]
@Carralex Just to make sure we are all working with the same version of landlab, could you please make sure your local copy is up-to-date (and, if not, update it and rerun `setup.py develop`)? I assume you are working from a clone of the main landlab repository (not a fork) and are on the master branch, is that correct?

**Comment by Carralex** [comment]
Thanks for the quick answer. I'm running landlab using ipython console into spyder. My folder land lab/landlab/components/stream_power has a few files (I attached a copy) and it starts with __init__.py.
<img width="854" alt="capture d ecran 2017-08-24 a 16 32 16" src="https://user-images.githubusercontent.com/17542220/29671455-e2d398aa-88e9-11e7-87d2-e6a21a4a3e2f.png">

**Comment by Carralex** [comment]
@mcflugen Yes I do, I'm working on a clone of the main landlab repository on my machine. For being sure I'm going to up-to-date again my local copy right now.

**Comment by SiccarPoint** [comment]
OK, just for completenesses' sake, once you've updated one more time, try deleting the files `cfuncs.c` and `chunks.so` out of here, then re-running `python setup.py develop` as you normally would. I doubt this is it, but it's an easy check first up.

**Comment by Carralex** [comment]
Ok I do have the lastest version for sure now and I deleted cfuncs.c and cfuncs.so then re-running python setup.py develop but still the same error message...

**Comment by SiccarPoint** [comment]
OK, so the remaining obvious thing is that you have a weird path issue. We can test this fairly easily. From the command prompt, just type `python`. This will give you the most basic python console, which looks like `>>>`. At this prompt, do:
```
>>> import landlab
>>> landlab.__file__
```
(Note to get out of this console, you need to do `exit()`.)

Then go into Spyder and do the same thing at the python console there.

Do you get the same directory in both cases?

**Comment by mcflugen** [comment]
@Carralex Do you see the same error if you use Python, iPython, and Spyder or does the error just crop up when you use Spyder?

**Comment by Carralex** [comment]
@SiccarPoint  Ok thank you for the instructions. I checked on Python, iPython and Spyder the path and they all gave me the same path : '/Users/Alexandra/landlab/landlab/__init__.pyc'

@mcflugen Indeed I suspect it might be a Spyder issue because there is no error message when I'm running my code into basic python console or ipython console..but is is annoying me as I'm very used to work with Spyder..

**Comment by gregtucker** [comment]
I ran into something similar a month or two ago, and the solution was to completely remove anaconda and reinstall it. I have no idea why that worked, but it did.

**Comment by Carralex** [comment]
I did remove completely anaconda and reinstall it without doing the "conda update --all" command (if I do it I still have the same issue) and it works now into spyder. Than you for all your advices.
