### ISSUE TITLE
Create a high level tab for 'reporting issues'

### ISSUE THREAD

**Issue by saisiddu** [landlab/landlab#559]
I suggest we create a high level tab in documentation, like 'ReferenceManual', that may be named 'Report Issues'. I envision this tab leading to documentation that has a link to our github repo, and requests one to create a github issue (best served by having a snapshot that points to the location where the 'issues' tab on github page is located).

**Comment by gregtucker** [comment]
I agree this is worth trying. Just an additional top menu item on splash page called "Report Issues" that links to Issues on GitHub page

**Comment by jennyknuth** [comment]
PR for a solution to this is here: https://github.com/landlab/landlab.github.io/pull/5 
I can change the tab name to "Report Issues", but was worried that was too long. Also, if someone does not know how to use github issues, would they know what "Report Issues" is? Happy to change if you think "Report Issues" is better.

**Comment by saisiddu** [comment]
Thanks Jenny! I think 'Support' is shorter and better. I am closing this issue!
