### ISSUE TITLE
Remove unused gradient functions

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#583]
In cleaning up the how `RasterModelGrid` handles diagonals, I've come across a couple functions that I would like to remove. They are not used anywhere and make use of old data structures, which appear to me to contain bugs (`RasterModelGrid.diagonal_cells`, for example).

The functions in question (located in `../landlab/grid/raster_steepest_descent.py`) are:
*  `_calc_steepest_descent_across_cell_corners`
*  `_calc_steepest_descent_across_adjacent_cells`

There is also a third function, which has been marked as deprecated, in the same module and could probably also be removed:
*  `_calc_steepest_descent_across_cell_faces`

This third function is only used in the `grid_flow_directions` function (defined in `../landlab/components/flow_director/flow_direction_DN.py`) which is only used in what looks like an old example on how to run the lake mapper.

@kbarnhart this seems like a question for you. What do you think?

**Comment by SiccarPoint** [comment]
I built these, a pretty long time ago! Those leading underscores (and the fact they're related to diagonal processing) means they shouldn't have been used outside the dev team. Hopefully.

If they're not being widely used, and taking them out doesn't break any tests, I say take them out.

**Comment by kbarnhart** [comment]
Sounds like all of them should be removed. 

I agree with your assessment of where the last one is used. Looks like `_calc_steepest_descent_across_cell_faces` gets used only in `grid_flow_directions` which is only used at the end of what seems to be a test in `def main()`

**Comment by kbarnhart** [comment]
These are no longer around. closing.
