### ISSUE TITLE
ImportError: cannot import name adjust_flow_receivers

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#595]
@kbarnhart @mcflugen 

I think this might be for Eric, but maybe Katie. I have the latest version of Landlab, just synced a couple hours ago. I am now having a weird issue where I can't import components when in Spyder, but I can from an iPython environment launched from my terminal. It doesn't matter what component I try to import, I always get the error below in Spyder. I'm attaching two screenshots, one that shows the error in Spyder, and one that shows that I don't get error on the command line. Weird right?

<img width="539" alt="screen shot 2017-11-28 at 3 02 54 pm" src="https://user-images.githubusercontent.com/6990475/33344827-dba87dd2-d44f-11e7-9669-9e41deb5784c.png">
<img width="593" alt="screen shot 2017-11-28 at 3 02 07 pm" src="https://user-images.githubusercontent.com/6990475/33344828-dbbb8012-d44f-11e7-87a7-9c30ee7ec4da.png">

from landlab.components import ChiFinder
/Users/nicgaspar/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Traceback (most recent call last):

  File "<ipython-input-1-34b0cd19dc51>", line 1, in <module>
    from landlab.components import ChiFinder

  File "/Users/nicgaspar/landlab/landlab/components/__init__.py", line 6, in <module>
    from .flow_routing import FlowRouter, DepressionFinderAndRouter

  File "/Users/nicgaspar/landlab/landlab/components/flow_routing/__init__.py", line 3, in <module>
    from ..flow_director import flow_direction_DN

  File "/Users/nicgaspar/landlab/landlab/components/flow_director/__init__.py", line 1, in <module>
    from .flow_director_d8 import FlowDirectorD8

  File "/Users/nicgaspar/landlab/landlab/components/flow_director/flow_director_d8.py", line 15, in <module>
    from landlab.components.flow_director import flow_direction_DN

  File "/Users/nicgaspar/landlab/landlab/components/flow_director/flow_direction_DN.py", line 16, in <module>
    from .cfuncs import adjust_flow_receivers

ImportError: cannot import name adjust_flow_receivers

**Comment by kbarnhart** [comment]
This looks similar to issue #590 made by @Glader011235 . I'm thinking about it.

**Comment by nicgaspar** [comment]
I think you are right that this is the same issue. I'm closing this. Thanks for spotting that Katy. And sorry I spelled your name wrong initially.

**Comment by saisiddu** [comment]
Thanks for this issue and follow up. I just freaked out because of the same error. Fortunately, I did figure that running it from terminal doesn't cause this issue. I have this issue on my linux box (more complicated as I am a windows user).
