### ISSUE TITLE
is landlab for linux 32-bit available?

### ISSUE THREAD

**Issue by ricsatjr** [landlab/landlab#617]
**tried to install landlab using:**

_conda install landlab -c landlab -c conda-forge_

**and got these as results:** 

Fetching package metadata ...............

PackageNotFoundError: Packages missing in current channels:
            
  - landlab

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/landlab/linux-32
  - https://conda.anaconda.org/landlab/noarch
  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/linux-32
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-32
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-32
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-32
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by mcflugen** [comment]
@ricsatjr We don't currently build landlab for 32 bit Linux. You're the first to request this. However, this is something we could probably add.

In the meantime, if you can't find a 64 bit linux machine, you can always build landlab from source on your machine.  Assuming all of our dependencies are available for 32 bit Linux, it should build just fine. If this is something you're interested in trying, our wiki has instructions for [building landlab from source](https://github.com/landlab/landlab/wiki/Installing-Landlab-from-source-code-(%22developer-install%22)).

**Comment by ricsatjr** [comment]
Thanks, Eric. Will try to do as what you have advised, and get back to you
as soon as I have results.

*Ric Saturay*

*Project Chief Science Research Specialist*
DYNASLOPE Project
Philippine Institute of Volcanology and Seismology
CP Garcia Ave., Diliman, Quezon City
Philippines


*Senior Lecturer*
National Institute of Geological Sciences
University of the Philippines - Diliman
Velasquez St., UP Campus, Diliman, Quezon City
Philippines

*Geologist*
AGHAM - Advocates of Science and Technology for the People
2nd Flr., Elden Tejada Bldg.
#2 K-H St., West Kamias, Quezon City
Philippines

**Comment by mcflugen** [comment]
@ricsatjr Sounds good.
