### ISSUE TITLE
XZ or YZ model - irregular grid-shapes following DEM

### ISSUE THREAD

**Issue by PeterBetlem** [landlab/landlab#618]
Hei,

I have been looking through the documentation on achieving irregular grids, but have been unable to figure out whether it is possible to obtain a grid that follows the DEM in the top (ragged) and base (parallel to top), and has straight left and right boundaries? 

As part of a greater 3D model I have Pd dataframes featuring XYZ coordinates and data, and I was hoping to run a heat diffusion model in a 2D transect using YZ (or XZ) coordinates and filling it up with the corresponding values to compare with my other script for computing times/efficiency.  Would there be any tips on setting this up?

**Comment by kbarnhart** [comment]
@PeterBetlem Thanks for the question. 

I'm not sure I understand what you mean by "that follows the DEM in the top (ragged) and base (parallel to top), and has straight left and right boundaries". If X-Y is the coordinate of the plan view DEM, do you mean to make an X-Z or X-Y cross section to run a 2D heat diffusion model? Or do you mean something different?

@mcflugen has developed the capacity for layers in landlab grids, which may be of interest to you.

Regarding your modeling effort, it is hard for me to tell if landlab is an appropriate modeling framework for your work. Could you elaborate a bit more on your modeling effort and whether you are planning to use existing landlab components or build new ones so we can help provide guidance?

**Comment by PeterBetlem** [comment]
@kbarnhart - Apologies! I should have been more specific. Yes, the DEM would be the X-Y plane, with each consecutive layer in the main model being a layer lower. I was hoping to run a couple of heat models along cross-sections in the X-Z or Y-Z planes. Such a setup would have the top of the model, as in the very first layer, follow the DEM, and thus not be a regular grid when viewed through a perpendicular axis. Since the cross-section retains the X-Y plane boundaries, the left and right sides of the X-Z cross-section would appear regular again. Does that make sense?

And I wasn't aware that there was a capacity for layers in grids yet! Thanks for letting me know. This might help slightly with figuring out the thermobaric conditions in my study area.  I am guessing the full implementation/example will be added in a future version of Landlab?

The main model I have, as based on geological data and tied to exploration wells, is currently mostly static, and it is my aim to update it to allow for changes over time. While I would be able to do this through commercial software packages, I'd rather stick to using Python, and use a component-based solution such as Landlab. Currently there is just a need to show such time-dependence in a very narrow section of the whole, making a 2D cross-section model a proper first step to get some hands-on experience with Landlab. This would also allow me to see whether Landlab is indeed the way to go, at which point I would have to decide whether to implement only existing components or contribute by adding new ones.

Either way, thanks for the quick reply!

**Comment by gregtucker** [comment]
One solution to consider would be to use a rectangular grid, and simply mirror the topography by setting  boundary status nodes in a "ragged" fashion, if that makes any sense. A simple way to do this would be to set one grid cell in each column to represent the ground surface. The position of this grid cell---whether at the top of the grid, or some distance down from the top---would depend on the elevation at that location. The cells above it would also be flagged open boundary. The elevation increments would have to be equal to the grid cell size.

**Comment by PeterBetlem** [comment]
@gregtucker I indeed considered doing so, and I will probably implement it like that. Thanks for the headsup, and I look forward to seeing the implementation with layers being brought live.
