### ISSUE TITLE
animation workflow by modifying imshow_grid

### ISSUE THREAD

**Issue by nathanlyons** [landlab/landlab#622]
I think this is a simple and flexible way to make animations. It will require imshow_grid to return the AxesImage object that is in turn returned from imshow. I propose modifying imshow_grid to return this object. Are there any reasons not to do this? If this seems like an OK idea, I will create a pull request to do this.

Below is an example of how this can work in a driver. Other figure types such as plt.plot can be animated using this technique.

The output gif produced by this driver is also below. Other formats work including mp4. I used gif here because thats what github can display.

```python
from landlab import RasterModelGrid
from landlab.components import FlowRouter, FastscapeEroder
from landlab.plot import imshow_grid
import matplotlib.animation as animation
import matplotlib.pylab as plt
import numpy as np


mg = RasterModelGrid((100,100), 50)
z = mg.add_zeros('node','topographic__elevation')
z += np.random.rand(z.size)

mg.set_closed_boundaries_at_grid_edges(True, False, True, False)
mg.set_fixed_value_boundaries_at_grid_edges(False, True, False, True)
    
fr = FlowRouter(mg)
sp = FastscapeEroder(mg, K_sp=1e-3, m_sp=0.5, n_sp=1)

dt = 1000
uplift_rate = 0.01
uplift_per_step = dt * uplift_rate
n_steps = 100

artists = []
fig = plt.figure()

for i in range(n_steps):

    z[mg.core_nodes] += uplift_per_step
    fr.run_one_step()
    sp.run_one_step(dt)

    if i % 10 == 0:
        im = imshow_grid(mg, z, allow_colorbar=False)
        artists.append([im])

ani = animation.ArtistAnimation(fig, artists, interval=500)
plt.show()
ani.save('animation.gif', writer='imagemagick')
```

![animation](https://user-images.githubusercontent.com/9955408/36354141-59c26806-1495-11e8-8a4d-9bf090a0f976.gif)

**Comment by kbarnhart** [comment]
@nathanlyons this looks great! Definitely an enhancement that I support adding!

My only thought is to assess if there are any instances in which a prior users uses of imshow_grid might break if we change it to return an AxesImage object. It seems like testing and backwards compatibility are hard things to do with plotting functions, so perhaps @mcflugen has some guidance?

**Comment by ChristinaB** [comment]
Hi Nathan,  This is so great!! 
BUT, when I run this code I get this error. Any ideas why?  I can't find an answer in StackOverflow...

![image](https://user-images.githubusercontent.com/4108369/36936397-e8b1ecfc-1eb9-11e8-980b-6eabdb340210.png)

**Comment by nathanlyons** [comment]
Hi Christina, I'm glad this may be helpful.

The workflow described in this issue is not yet possible. The error message that you are recieving is because imshow_grid returns 'none'. The above workflow needs a matplotlib artist returned by this plotting function.

Given a recent discussion with other Landlabbers, I think that this workflow will be annoying to maintain. All the plotting functions we develop will have to return a certain object type.

I expect to finish by Monday a workflow that is just about as simple as the one described here. It will not require changes to Landlab plotting functions.

**Comment by nathanlyons** [comment]
I no longer propose modifying imshow_grid to return artists for the sake of making animations. 

Matplotlib.animation workflows will require additional software. (I previously said the above workflow did not. This is not true. I previously installed the software and did not realize the workflow used it.)

I now propose the workflow in this tutorial: [https://github.com/landlab/tutorials/blob/master/plotting/animate-landlab-output.ipynb](https://github.com/landlab/tutorials/blob/master/plotting/animate-landlab-output.ipynb)

This also requires additional software. I do not suggest we package the software with Landlab. Instead, users who wish to animate using this workflow may download the software.

**Comment by SiccarPoint** [comment]
Ha! Just to add I went through this exact chain of actions about 3 years ago, only to reach the same final conclusion that you need external software/codecs to do this. I also had managed to add the necessary stuff on my dev machine without realising 😬 Sorry I didn't notice you were heading down this rabbit hole early enough to jump in and head you off...

**Comment by nathanlyons** [comment]
I feel better reading your comment that I did not give up too early on finding a solution without additional software. At least demonstrating how to animate instead of baking in one animation workflow provides flexibility.
