### ISSUE TITLE
Problems installing LandLab

### ISSUE THREAD

**Issue by yuvalsmilo** [landlab/landlab#625]
Hello,
We have some issues with installing LandLab in Windows and MacOS.
In Windows, We didn't managed to install landlab via conda because some conflicts occurred during installation. Then, we manage to install it via pip without conflicts, but we failed landlab.test()

Then we tried to install it in MacOS. The conda installed it properly and we passed landlab.test().
But, when we tried to run tutorials e.g., "The transport-length hillslope diffuser" some of the models were not found.

We prefer to use LandLab in Windows but we hope for any help.
Bests

**Comment by kbarnhart** [comment]
@yuvalsmilo, thanks for the question. 

Could you provide a bit more information about the Windows and MacOSX platforms you used as well as what python distribution you are using. 

We recommend using conda to install landlab, could you provide the output of the conda log for your Windows installation attempt. 

I'm going to tag @mcflugen and @saisiddu as they are often very helpful for Windows installation issues.

**Comment by yuvalsmilo** [comment]
Hey Kathy! Thanks For the quick response.

I attached the log of landlab installation in windows via conda and pip:

Problem Using Conda:

(base) C:\Users\yuvals>conda install landlab -c landlab -c conda-forg
Solving environment: -
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forg

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that
the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
failed

UnsatisfiableError: The following specifications were found to be in
conflict:
  - anaconda -> mkl-service==1.1.2=py36h57e144c_4
  - anaconda -> numexpr==2.6.4=py36h30784b8_0
  - anaconda -> scikit-learn==0.19.1=py36h53aea1b_0
  - anaconda -> tk==8.6.7=hcb92d03_3
  - landlab
Use "conda info <package>" to see the dependencies for each package.

Problem Using Pip:
here the installation was successfull. The problem occurred in the test:

(base) C:\Users\yuvals>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900
64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import landlab
>>> landlab.test()
landlab version 1.2.0
landlab is installed in
C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\landlab
Python version 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC
v.1900 64 bit (AMD64)]
nose version 1.3.7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\landlab\testing\nosetester.py",
line 79, in test
    return super(LandlabTester, self).test(**kwds)
  File
"C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\testing\nose_tools\nosetester.py",
line 406, in test
    label, verbose, extra_argv, doctests, coverage, timer)
  File
"C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\testing\nose_tools\nosetester.py",
line 300, in prepare_test_args
    if self.check_fpu_mode:
AttributeError: 'LandlabTester' object has no attribute 'check_fpu_mode'Hey
I attached the log of my installtions of landlab in windows via conda and
pip:

Problem Using Conda:

(base) C:\Users\yuvals>conda install landlab -c landlab -c conda-forg
Solving environment: -
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forg

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that
the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
failed

UnsatisfiableError: The following specifications were found to be in
conflict:
  - anaconda -> mkl-service==1.1.2=py36h57e144c_4
  - anaconda -> numexpr==2.6.4=py36h30784b8_0
  - anaconda -> scikit-learn==0.19.1=py36h53aea1b_0
  - anaconda -> tk==8.6.7=hcb92d03_3
  - landlab
Use "conda info <package>" to see the dependencies for each package.

Problem Using Pip:
here the installation was successfull. The problem occurred in the test:

(base) C:\Users\yuvals>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900
64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import landlab
>>> landlab.test()
landlab version 1.2.0
landlab is installed in
C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\landlab
Python version 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC
v.1900 64 bit (AMD64)]
nose version 1.3.7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\landlab\testing\nosetester.py",
line 79, in test
    return super(LandlabTester, self).test(**kwds)
  File
"C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\testing\nose_tools\nosetester.py",
line 406, in test
    label, verbose, extra_argv, doctests, coverage, timer)
  File
"C:\Users\yuvals\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\testing\nose_tools\nosetester.py",
line 300, in prepare_test_args
    if self.check_fpu_mode:
AttributeError: 'LandlabTester' object has no attribute 'check_fpu_mode'

Thank you very much for your help!
Sincerely Yuval.

**Comment by mcflugen** [comment]
@yuvalsmilo it looks like the first problem is a typo. The channel is conda-forge, not conda-forg.

**Comment by yuvalsmilo** [comment]
Hi Eric,
My mistake, here is the log after i fixed the typo:

(base) C:\Users\yuvals>conda install landlab -c landlab -c conda-forge
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in
conflict:
  - anaconda -> gevent==1.2.2=py36h342a76c_0
  - anaconda -> mkl-service==1.1.2=py36h57e144c_4
  - anaconda -> numexpr==2.6.4=py36h30784b8_0
  - anaconda -> scikit-learn==0.19.1=py36h53aea1b_0
  - landlab
Use "conda info <package>" to see the dependencies for each package.


(base) C:\Users\yuvals>conda install landlab -c landlab -c conda-forge

Thanks again,
Yuval

**Comment by kbarnhart** [comment]
@yuvalsmilo consider using a conda environment which should help with your conflicts. 

Checkout Issue #500 where  @saisiddu  describes how to make a conda environment on Windows for landlab.

**Comment by margauxmouchene** [comment]
The failing tests might be related to numpy version 1.14 (see issue #616), they should pass if you use numpy 1.13.

**Comment by mcflugen** [comment]
@yuvalsmilo: @margauxmouchene makes a good point. I wouldn't be too worried if all the tests don't pass. The `AttributeError: 'LandlabTester' object has no attribute 'check_fpu_mode'` failure, for instance, has nothing to do with landlab and can be ignored (it's the result of a change in numpy 1.14).

I also notice that we don't have the most current release (v1.2.0) available for Windows right now. I'll work on building one today. In the meantime, using 1.1 should be fine.

Following @kbarnhart's suggestion, you can install a minimal version of Python into an environment with the following (from the Anaconda prompt),
```bash
$ conda create -n landlab python=3.6 landlab -c landlab
```
(assuming you want to use python 3.6--you don't have to) and then,
```bash
$ activate landlab
```
This should eliminate the package conflicts (it does for me, anyway).

**Comment by yuvalsmilo** [comment]
Hey you all. It seems Eric advice was useful and the installation via conda
was successful and i passed landlab.test().
Although, the library doesn't work properly. I tried to run
the TLHDiff_tutorial and i got the same errors as i run it with pip:

cannot import name 'TransportLengthHillslopeDiffuser'
cannot import name  'FlowDirectorSteepest'

Is it possible that these models are deprecated?
some of the modules do work. for instance: RasterModelGrid
I really appreciate all of your help!
Thanks,
Yuval.

**Comment by mcflugen** [comment]
@yuvalsmilo: That's because those components are not included in the latest release of landlab. They are only in the development version. To get them, you'll have to install landlab in [developer mode](https://github.com/landlab/landlab/wiki/Installing-Landlab-from-source-code-(%22developer-install%22)). Sorry for the confusion.

**Comment by yuvalsmilo** [comment]
Okay I understand.
Thank you very much you really helped me a lot
Yuval
