### ISSUE TITLE
Failing tests of ErosionDeposition and SPACE in 5th decimal place

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#660]
In master, I'm seeing 3 test failures related to ErosionDeposition and SPACE. These seem to be discrepancies in the predicted and actual elevation fields in about the 5th significant figure.

File "/Users/gtucker/Dev/Landlab/landlab/landlab/components/erosion_deposition/erosion_deposition.py", line 176, in landlab.components.erosion_deposition.erosion_deposition.ErosionDeposition.__init__
Failed example:
    mg.at_node['topographic__elevation'] # doctest: +NORMALIZE_WHITESPACE
Expected:
    array([-0.47709521,  1.03606698,  2.0727653 ,  3.01126678,  4.06077707,
            1.08157495, -0.07997982, -0.06459322, -0.05380581,  5.00969486,
            2.04008677, -0.06457996, -0.06457219, -0.05266169,  6.02641123,
            3.05874171, -0.05350698, -0.05265586, -0.03498794,  7.05334077,
            4.05922478,  5.0409473 ,  6.07035008,  7.0038935 ,  8.01034357])
Got:
    array([-0.47709521,  1.03606698,  2.0727653 ,  3.01126678,  4.06077707,
            1.08157495, -0.0799788 , -0.06459321, -0.05380581,  5.00969486,
            2.04008677, -0.06457995, -0.064572  , -0.05266169,  6.02641123,
            3.05874171, -0.05350698, -0.05265586, -0.03498753,  7.05334077,
            4.05922478,  5.0409473 ,  6.07035008,  7.0038935 ,  8.01034357])

**Comment by kbarnhart** [comment]
@gregtucker are you seeing these on your computer or on Travis? Because I had the same issue on my computer when I was working on PR #655 and it wasn't a problem on Travis.

**Comment by gregtucker** [comment]
Mine -- haven't done a PR yet, so not sure if it appears on Travis. Different machine architecture maybe? An obvious solution would be to round the tests to say 4 decimal places, but first want to make sure that isn't just masking a deeper problem.

**Comment by kbarnhart** [comment]
Going to rope @cmshobe into this in case he has ideas.

**Comment by cmshobe** [comment]
I haven't had this issue on my machine, but I also haven't used SPACE since all of the Hex grid changes etc. Let's see what Travis has to say and we can dig into the code if these tests still crash.
