### ISSUE TITLE
Travis gives a green check when tests don't pass

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#701]
I've seen this happen in #658 and #674. It may have happened elsewhere. 

There seem to be other cases in which it does behave as expected (throws a red x when tests fail). 

I believe that @mcflugen knows about this and is generally updating the testing implementation. 

With CSDMS meeting coming up, I don't anticipate this will be resolved in short order, but the issue mostly exists to remind us all to actually look at the results of the tests on Travis and Appveyor between now and when this is fixed. 

@mcflugen @SiccarPoint @nicgaspar @gregtucker @saisiddu @erkanistan

**Comment by mcflugen** [comment]
I believe #707 fixed this.
