### ISSUE TITLE
Contact Landlab team for contribution/question/request

### ISSUE THREAD

**Issue by margauxmouchene** [landlab/landlab#715]
We don't have a 'contact' page on the wiki.
What is the recommended way for people wanting to contribute to Landlab, ask for an improvement, etc.?
- Make an issue
- Slack?
- Twitter?
- Other?

I am going to go ahead and create a [page](https://github.com/landlab/landlab/wiki/Contact) giving these options, fell free to edit.

**Comment by kbarnhart** [comment]
I think it should be an issue.
