### ISSUE TITLE
Docs broken due to new sphinx

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#734]
The RTFD docs error with the error described [here](https://github.com/rtfd/readthedocs.org/issues/4057).

I've fixed this in TerrainBento [here](https://github.com/TerrainBento/terrainbento/pull/32).  

I can fix it the same way for Landlab... but the Landlab docs are a bit more complicated than TerrainBento's and I wasn't the one to set them up. So I want to make sure its OK to fix in the same way before I go ahead and do it. 

@mcflugen @SiccarPoint @gregtucker @jennyknuth feel free to weigh in.

**Comment by gregtucker** [comment]
Looks like a simple fix re: versioning. Go for it!

**Comment by kbarnhart** [comment]
In a landlab call we punted on deciding how to fix this. The short story is that the issue is with `numpydocs` which is no longer supported. Instead one can used `napoleon`. This was easy for me to change in terrainbento, but it was unclear if it would be so simple to transition away from `numpydocs` in landlab. 

However, Issue #762 has occurred because the docs are broken so we should make a decision and fix this.

**Comment by SiccarPoint** [comment]
Not clear to me what the problem might be... What are the key differences? Nothing I've built differs from "standard" Sphinx/rtd styling, so hopefully no problems.

**Comment by kbarnhart** [comment]
I've just been asked about the functionality of the `channel_profile` plotting utility as the docs still list `plot_channels_in_map_view` but the master branch doesn't support this.

**Comment by kbarnhart** [comment]
This has been fixed by PR #776. @mcflugen I think it makes sense for us to make a release so that both the `release` and the `master` docs are working.

What do you think?

Then we can close this issue.

**Comment by kbarnhart** [comment]
Fixed now in both `release` and `master`. closing
