### ISSUE TITLE
flow__distance utility is not recognized into Hydroshare

### ISSUE THREAD

**Issue by Giuseppecipolla95** [landlab/landlab#740]
Hy everybody, I'm about to upload my model into Hydroshare to share it with you all. The problem is when I try to import the _flow__distance_ utility because it gives me the following error:
`No module named 'landlab.utils.flow__distance'`
Does anybody know why this happens? In my laptop everything is fine since I've already updated landlab to 1.5 version.
Thanks in advance.

**Comment by kbarnhart** [comment]
@Giuseppecipolla95 we just released the version of Landlab that has this utility in it and I don't think Hydroshare has been updated yet. 

The new version is  Landlab version 1.5.0.
You can check the version on Hydroshare with:

```python
>>> import landlab
>>> landlab.__version__
```

**Comment by Giuseppecipolla95** [comment]
@kbarnhart Yes, I've already imagined this. The version of Landlab on Hydroshare is 1.4.0.
I'm wondering if It's possible to update Landlab on Hydroshare, so, I can run my model on it. Who can I ask to do it?
Thanks in advance.

**Comment by kbarnhart** [comment]
@mcflugen can you comment on the typical process/timeline for new Landlab releases on Hydroshare?

**Comment by margauxmouchene** [comment]
I think Christina recommended we open an issue on Hydroshare (I guess [here](https://github.com/hydroshare/hydroshare)) when we want Landlab to be updated.  @ChristinaB can you confirm?

Alternatively, @Giuseppecipolla95 you can upgrade directly within a notebook using:

`!/opt/conda/bin/conda install landlab=5.0`

or

`!/opt/conda/envs/python2/bin/conda install landlab=5.0`

**Comment by Giuseppecipolla95** [comment]
@margauxmouchene With the command you suggested, would I be able to update Landlab on Hydroshare? I think it'd allow me to upgrade it just on my laptop.

**Comment by margauxmouchene** [comment]
@Giuseppecipolla95 How do you run your model on Hydroshare to get the error?

If you run it through a Jupyter Notebook, make sure you use a Python 3 kernel (top right of the notebook, you can change it in the "Kernel" menu).

Check the version:
`import landlab`

`landlab.__version__`

If it is not 1.5, you can add the following command as the first lines of the notebook (ignore the commands in my previous comment, they don't work, sorry for the confusion) :

`!/opt/conda/bin/conda install -c landlab landlab --yes`

This way whoever runs the notebook will have an upgraded version of Landlab (not on their laptop, just in the notebook in their own space on Hydroshare) and they can use the flow__distance utility.

If you are still having trouble with this, please give me link to where your model is on Hydroshare so I can look at it directly.

**Comment by Giuseppecipolla95** [comment]
@margauxmouchene I've tried your suggestion and it worked! Many thanks!
