### ISSUE TITLE
Negative runoffs/infiltration

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#744]
Not sure whether to label this as a bug or an opportunity:

At present the runoff accumulator quite happily takes negative numbers as its ``runoff`` argument, or as `water__unit_flux_in`. If you do this, the output permits negative flow accumulations, which is clearly nonsense.

If we treat this as a pure bug, there needs to be an input check that runoff >= 0., and a test.

BUT

Better surely to treat this as an opportunity to implement simple infiltration/transpiration losses - which I don't believe is currently something we can do, right? So, keep the option for runoff < 0., but ensure that surface_water__discharge >= 0. at all nodes, as it's calculated. And appropriate test.

Seems like a simple fix either way, presumably modifying the Cython loop in the second case. Happy to do this myself, though want @kbarnhart 's input beforehand - and you may well be able to do it faster, too.

**Comment by SiccarPoint** [comment]
Did it myself. Note I've carved off a small portion of your accumulation code into a cfunc, on the assumption that the extra logical test I needed inside the existing loop would not be a good idea in due Python. Also appears to reduce duplication slightly, assuming `flow_accum_bw.py` still gets used somewhere. If you approve, I'll throw a simple test on and we'll go with that.

**Comment by SiccarPoint** [comment]
This no longer reduces "duplication", as I was being a moron. Approach good though I think. Still need new tests. Run the attached notebook to see the new functionality in action.

Might be a good idea to check I haven't contrived to actually slow down flow routing by doing it this way. Some speed hit is inevitable, but if it's too punishing would be easy enough to make two versions of these _accumulation funcs, then only use the slower ones where `np.any(runoff_rate < 0.)`

**Comment by SiccarPoint** [comment]
Nope, won't let me upload a notebook. See... PDF of notebook?
[Untitled.pdf](https://github.com/landlab/landlab/files/2181311/Untitled.pdf)

**Comment by SiccarPoint** [comment]
PDF of notebook. See the end for the infiltration loss happening.
[Untitled-3.pdf](https://github.com/landlab/landlab/files/2181357/Untitled-3.pdf)

**Comment by kbarnhart** [comment]
@SiccarPoint I think this is a good idea. I might let some others who have applications that may involve infiltration (@jadams15 ? @saisiddu ?) weigh in on how they'd expect this to behave.

**Comment by kbarnhart** [comment]
also... confirming that `flow_accum_bw.py` is still used
