### ISSUE TITLE
ERROR: Failure: ValueError ('/Users/barnhark/projects/landlab/landlab/landlab/grid/tests/testing_hex_grid/__init__.py/__init__.pyc' is not a package)

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#748]
@mcflugen @SiccarPoint  @gregtucker @saisiddu @nicgaspar @margauxmouchene @nathanlyons @erkanistan 

Anyone else getting this error on `master`? I can confirm that I am on the most updated version of `master` and that I have run `python setup.py develop` since updating. 

This is the only error I see. 

```
======================================================================
ERROR: Failure: ValueError ('/Users/barnhark/projects/landlab/landlab/landlab/grid/tests/testing_hex_grid/__init__.py/__init__.pyc' is not a package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda3/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/anaconda3/lib/python3.6/imp.py", line 210, in load_package
    raise ValueError('{!r} is not a package'.format(path))
ValueError: '/Users/barnhark/projects/landlab/landlab/landlab/grid/tests/testing_hex_grid/__init__.py/__init__.pyc' is not a package
```

**Comment by mcflugen** [comment]
@kbarnhart I think it's just because `testing_hex_grid` was renamed in a recent change by @gregtucker in #720. If you just remove the associated `.pyc` files, you should be fine.

**Comment by kbarnhart** [comment]
@mcflugen thanks! removing the directory `/landlab/grid/tests/testing_hex_grid` solved the problem. 

Is there anything like `make clean` that will remove all the no-longer-used .pyc files (and folders that once held stuff that has been removed or renamed?)

**Comment by mcflugen** [comment]
@kbarnhart There is a useful tool called `pycmd` that does this (as well as other useful things). There doesn't appear to be conda package for it but it can be installed with `pip install pycmd`. All of the commands start with `py.`. What you're looking for, I think, is `py.cleanup`

**Comment by kbarnhart** [comment]
Thanks for the info @mcflugen. I'll close this now.
