### ISSUE TITLE
"Download all tutorials" link on wiki doesn't point to current tutorials

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#753]
It instead points to 'https://github.com/landlab/tutorials/archive/master.zip'

@mcflugen is all we need to do to update this .zip file or is there more to it?

(also, I'll look at pytest PR later today)

Thanks @nreitman for pointing this out

**Comment by margauxmouchene** [comment]
I'd say it should point to: [https://github.com/landlab/tutorials/archive/release.zip](https://github.com/landlab/tutorials/archive/release.zip)

**Comment by margauxmouchene** [comment]
Actually, all the links on the [Tutorials page](https://github.com/landlab/landlab/wiki/Tutorials) point to tutorials in the 'master' branch, they should point to the release branch. I'm going to change this.

**Comment by margauxmouchene** [comment]
Done: 
- updated 'download all tutorials' and other links on the [wiki](https://github.com/landlab/landlab/wiki/Tutorials)
- updated all the links within the notebooks themselves ([PR 28 in tutorials](https://github.com/landlab/tutorials/pull/28))
