### ISSUE TITLE
Examples for SteepnessFinder and ChiFinder don't import SteepnessFinder and ChiFinder

### ISSUE THREAD

**Issue by nreitman** [landlab/landlab#754]
Examples for SteepnessFinder and ChiFinder initialize the components without importing them first. 

http://landlab.readthedocs.io/en/latest/landlab.components.steepness_index.html
http://landlab.readthedocs.io/en/latest/landlab.components.chi_index.html

**Comment by SiccarPoint** [comment]
Resolved by #759
