### ISSUE TITLE
Depositional Stratigraphy Example?

### ISSUE THREAD

**Issue by ThomasMGeo** [landlab/landlab#765]
Does anyone have a strat example that there willing to share?

**Comment by ThomasMGeo** [comment]
Something like this would be fantastic: https://serc.carleton.edu/NAGTWorkshops/sedimentary/activities/14172.html

**Comment by ThomasMGeo** [comment]
http://mygeologypage.ucdavis.edu/sumner/gel109/labs/nordlund99fuzzim.pdf

**Comment by nathanlyons** [comment]
@ThomasMGeo I am not aware of a completed model example or capabilities to build subaqueous stratigraphy using Landlab. I suggest exploring if any of the models on the  CSDMS website meet your needs: https://csdms.colorado.edu/wiki/Model_download_portal. If you wish to couple a stratigraphy model with another, e.g. Landlab, take a look at the basic model interface: https://csdms.colorado.edu/wiki/BMI_Description. Alternatively, please let us know if you code a stratigraphy model component using Landlab (see the tutorial: https://github.com/landlab/landlab/wiki/Develop-your-own-component) and wish to contribute it to our repository.

**Comment by gregtucker** [comment]
Actually Mike Steckler and @mcflugen are currently working to translate Mike's original SEQUENCE model into Landlab. I believe they've basically got it working in the mode of vertical slices (i.e., quasi-2D).

**Comment by ThomasMGeo** [comment]
Any updates to that @mcflugen and @gregtucker ?

**Comment by gregtucker** [comment]
I'll defer to @mcflugen as to the current status of Sequence...
