### ISSUE TITLE
Developer version not installing on Windows with Python 3.6.5

### ISSUE THREAD

**Issue by saisiddu** [landlab/landlab#768]
I always had Anaconda Python 2.7 installed and working on my Windows 10 32-bit laptop. Installing developer version of Landlab required installing compilers from Microsoft Visual C++ tools (got them installed from the link that is spit out when we try the installation first time). On 26th July 2018, I uninstalled my Anaconda Python 2.7 and installed Anaconda Python 3.6.5. I tried to install developer version of Landlab but it failed and asked me to install Visual C++ tools from a link. The link didn't work. I tried to install the latest tools from other websites but nothing worked. 
Finally, I installed from the link 'https://wiki.python.org/moin/WindowsCompilers'. Before installing the tools from this link, I uninstalled the lurking Python 2.7 visual C++ tools. The downloads from this link also installed Windows 10 SDK files. This solution worked. So, if you face similar issues, you can try one of the things I tried. Also, remember to update setuptools, 'conda update setuptools'.

**Comment by dichongli** [comment]
I had tried this webpage, and download Microsoft Visual C++ 14.0 standalone: Build Tools for Visual Studio 2017 (x86, x64, ARM, ARM64), and my problem is solved.  Thanks !

**Comment by saisiddu** [comment]
Thanks Chongli! Do you remember how big were these files? Did you have to download any other files (other than standalone Visual C++ 14.0 build tools)?

**Comment by dichongli** [comment]
Yes, I had dowanload other files and standalone Visual C++ 14.0, the files are about 6.9G, anyway, it works now.
