### ISSUE TITLE
New data structure to record time- and/or space-dependent variables 

### ISSUE THREAD

**Issue by margauxmouchene** [landlab/landlab#769]
This is an outline for the new data structure that @nathanlyons and I are working on, 
The issue is to keep track of what we need to put in this new tool.

Fell free to add/comment!

1. Tentative name: DataRecord (courtesy of @nathanlyons)

2. Aim:
to combine @kbarnhart 's ItemCollection and @nathanlyons 's RecordCollection
will use xarray, 
will record time- and/or space-dependent variables describing the model and/or a set of items

3. Structure

The xarray DataSet created by DataRecord will have the following characteristics:

- Dimensions (one or both):
   - time: (size=number_of_timesteps)
   - item_id (size=number_of_items)
- Coordinates:
   - time (time) float [dt, 2dt, 3dt, ... number_of_timesteps * dt]
   - item_id (item_id) int [0, 1, 2, ... number_of_items - 1]

- Data variables (if Item_id is specified, the following two variables must exist; if not, no constraints on data variables):
   - Grid_element 		(item_id, time) str 	[‘node’, ‘node’, ‘link’, …]
   - Element_id		(item_id, time) int 	[0, 3, 3, …]

- Other possible variables (examples):
   - Mean_elevation	(time) float		[100, 110, 113, …]
   - Item_type		(item_id) str		[‘granite’, ‘limestone’, ‘granite’, …]
   - Item_size		(item_id, time) float	[5, 0.3, 2, …]

4. Methods and properties
- Methods we need:
   - “Checking methods”: if items are defined: 
	 - Check that they all have grid_element AND element_id specified
	 - Check that all grid_elements exist in the grid type that is used (e.g. Network grid doesn’t have cells)
        - Check that all element_ids exist on the grid (e.g. cannot be node 9 on a 3x3 grid)
    -	Add/delete:
         - Add/delete item (concat/drop?)
         - Add/delete time (concat/drop?)
         - Add/delete data variable 
    - Get/set values (do we need specific methods for this? Indexing makes this easy to do without calling a method)
    - Split/Groupby etc. (inherited from xarray?)
    - From ItemCollection:
        - Get_items_on_grid_element(at=’node’, element_id=0)
        - Calc_aggregate_value(func, var, at='node', fill_value=_FILL_VALUE, args=(), **kwargs)

- Properties:
From RecordCollection:
   - Number_of_timesteps
   - Model__times (array of all recorded timesteps)
   - Model__earliest_time (and latest_time, and prior_time)

**Comment by margauxmouchene** [comment]
When instantiating, the user could specify 'time' as:
- only the first timestep, later records will be concatenated as model runs
- an array of identified timesteps they're interested in, if they don't want the full record, e.g. [0, 1000, 1500, 1600, 3000]
- [first_timestep, timestep_size, number_of_timesteps]

**Comment by margauxmouchene** [comment]
Units are not handled by xarray but can be specified in the 'attributes'

**Comment by kbarnhart** [comment]
@margauxmouchene and @nathanlyons this looks really nice! 

A quick question related to backwards compatibility with ItemCollection:
How do you think it makes sense to ensure that the current use of ItemCollection (by you and by @pfeiffea) is accomplished?

One idea could be to change the name of ItemCollection to the name of the new tool, merge that, and then replace the interior of the new-name-for-ItemCollection with the tool you are making.

I'm not sure that this is the best way, but at minimum it would make it so that we would know when changes would break the current ItemCollection behavior.

**Comment by margauxmouchene** [comment]
Yes, I guess we can do that!

Unfortunately, I think the switch from pandas to xarray is going to break some stuff. For instance, in pandas, the data are in DataFrame, while the equivalent thing is called DataSet in xarray. A lot of the methods work similarly but won't always take the same arguments (because more dimensions can be created in xarray).

Since @pfeiffea and I are the only ones using ItemCollection at the moment, and it is not in master yet, it shouldn't be too hard to fix.
@pfeiffea: I can coordinate with you to edit whatever script you have that uses ItemCollection and explain how the new data structure works.

I will make sure that everything that is currently in ItemCollection is included in the new tool. Is the latest version of ItemCollection on Katy's branch barnhark/create_item_collection? Is that what Allison is using?

**Comment by nathanlyons** [comment]
@margauxmouchene Thanks for the thorough outline and doing the first round of coding on this. This seems to me the way to go. Some thoughts about the outline are below.

Instantiation inputs

- I can envision situations when no information about a time or item is yet available at instantiation. For example, a property of SpeciesEvolver will be a DataRecord instance that is instantiated in SpeciesEvolver’s init. This will often be before a model time loop. Perhaps the only required DataRecord instantiation inputs could be whichever combination of time and item is needed, and not require the first time, or any timestep info. I am proposing that the DataRecord init inputs that you listed be optional.
- Good idea on allowing the number of timesteps to be in the init. Maybe this improves performance(?). I also wonder if instantiating with the data variable labels improves performance. I will look into this and do rudimentary benchmarking of this when I create tests for this data structure.

Methods

- Regarding add/delete vs concat/drop for method labels, perhaps a design principle could be use xarray terminology when possible. I do not have a strong preference on this if anyone prefers add/delete.
- `modify`: A DataRecord method that modifies an existing record. The first method input could be a dimension (time or item_id) and the second input a dictionary of variable labels (the dict’s keys) and values. A data variable is created is it does not exist. Or, did you envision using xarray’s approach to modifying values?
- Regarding other xarray methods such as split and groupby:
    - We decide what xarray functionality is most important, create methods to do those things, and in the documentation indicate how to use the rest of xarray’s functionality by using DataRecord.DataSet
    - split and groupby seem especially useful and seems straight forward to use, which makes me think we should just use these directly. Although, other methods, e.g. add/concat will be called by DataRecord.add(…) where this would be DataRecord.Dataset.groupby(…), which seems confusing. So, perhaps DataRecord could simply pass inputs to these methods so we could use DataRecord.groupby(…)
    - It seems there should be a way to pass function calls from a base class (here, DataRecord) to methods of a property (DataSet) without coding each in the base class. I suppose its safer to leave it for us to decide what to implement.

Properties

I wonder if the double underscores I used for some RecordCollection properties are necessary, e.g. `model__latest_time`. In https://csdms.colorado.edu/wiki/CSN_Searchable_List, `model__time` is a standard name, but does this only make unnecessarily long variable names? Could we drop `model__` from each, e.g. `latest_time`, or is it better to use standard names for even properties?

**Comment by pfeiffea** [comment]
Hi all. Sorry for the slow response. Yes, @margauxmouchene, I'm sure it won't be hard to work around this in my existing code.

**Comment by margauxmouchene** [comment]
Answering Nathan's points (in same order):

Instantiation inputs:
- For now, all inputs (except the grid) are optional. You can create a Datarecord with only time, only item_id, both, or none. If you know that with the SpeciesEvolver you will want to record some variables relating to time, you can (1) instantiate DataRecord with the 'time' dimension option ON, and a first dummy record (time=0, data_variable_1=nan) that will be updated when you actually start running the model, or (2) simply instantiate a completely empty Datarecord and add the dimensions and variables at your first model timesteps. I created the methods to add records (time and/or item). I don't know which option is best, this relates to your second point

- If you pass your first time step and number of time steps, this will create the dimension 'time' with all its coordinates and empty arrays for all data variables that vary with time. Then you would replace the empty spots as you run the model. The other option is to create the dimension 'time' with only one coordinate (0), then create a new time coordinate after each time step as the model runs, and append the values to the variables that changed with time.  You are right, we should definitely test which is the most efficient.

Methods:
- Add/delete: so far I only created the methods to add items or time record. This was tricky because of the different options we offer when creating the initial Datarecord: it can have one or two dimensions, and variables can have different dimensions. The easiest method that I could find, to fit all configurations, is to actually create a new Dataset with whatever you want to add and 'merge' it with the original one. Other methods like `concat` only allow to work along one dimension. The methods are named 'add_item' and 'add_record' for now, we can change them if they are not clear. `Add_item` is to define new item(s) (=adding coordinates to the 'item_id' dimension). If time is recorded, this can be done at a new timestep (=adding coordinates to both dimensions). `Add_record` is to add a new timestep and a time-related record, for instance the new position of an existing item at the new timestep or a non-item-related record (e.g. mean elevation at the new timestep).
Still to do: delete/drop methods

- modify: To do! I agree with your inputs, would just change the order to be consistent with the other methods. I wouldn't allow the `modify` method to create a new variable if it doesn't exist: this can be done using `add_record` (will make it clear in the method documentation).

-xarray methods such as split and groupby: I agree with you that most methods inherited from xarray are straightforward to use and we should use them directly. I will test them with the current version of Datarecord to see if it make sense to write specific methods.
As of now, Datarecord inherits directly from Dataset so we can actually call `Datarecord.groupby`, etc. (not `Datarecord.Dataset.groupby`) so that's simple!

Properties:
I agree, standard names tend to be long... Looking around Landlab, time is mostly mentioned alone so we can drop `model__` here,  I think it's clear enough.

**Comment by nathanlyons** [comment]
@margauxmouchene Is it possible to add a record with data that is a list? For example, this code:

`dr.add_record([1], new_record={'species': (['time'], [['dog', 'cat']])})`

returns this error:

`ValueError: dimensions ('time',) must have the same length as the number of data dimensions, ndim=2`

Do I need to add an additional coordinate to DataRecord in order to add a list?

**Comment by margauxmouchene** [comment]
The error is raised because your input is interpreted as two values ('dog' and 'cat') for only one time coordinate (1). This is because data variable entries are not meant to be lists, but single values. 
My suggestion would be to convert your list as a single string before passing it to Datarecord. I guess your list is the output of some other part of the Species evolver. You could do something like that:

`from landlab import RasterModelGrid`
`from landlab.data_record import DataRecord`
`grid = RasterModelGrid((3,3))`
`dr = DataRecord(grid, time=[0.])`


Convert your list and pass it to add_record:
`my_list=['dog', 'cat']`
`my_string=', '.join(my_list)`
`dr.add_record(model__time=[1], new_record={'species': (['time'], [my_string])})`

This gives you:
`dr`
`<xarray.DataRecord>`
`Dimensions:  (time: 2)`
`Coordinates:`
`  * time     (time) float64 0.0 1.0`
`Data variables:`
`    species  (time) object nan 'dog, cat'`

And if you need to get the list back:
`dr.get_data(1., data_variable='species').split(', ')`
gives:
`['dog', 'cat']`

(don't forget the space after the comma in both `join` and `split` commands)

Would that work for you? I know it's not exactly what you asked but I think we should not try to force it to take lists as data entries, this is not how xarray is meant to work.

**Comment by nathanlyons** [comment]
Thanks. You motivated me to find another way to deal with the arrays.

DataRecord works quite well. Once I understood it, it just worked where I was using RecordCollection.

Below are my next couple questions. I next need to tinker with adding items.

### Incorrect value of number_of_timesteps returned

Example:
```python
mg = RasterModelGrid(10, 10, 1)
dr = DataRecord(mg, time=[0])
print(dr.number_of_timesteps)
1

dr.add_record([1], new_record={'my_var': (['time'], [100])})
print(dr.number_of_timesteps)
1
```

The property, `number_of_timesteps` returns the value of `_number_of_times` that is only updated in `__init__`, and not in `add_record` or if a time is deleted using xarray methods.

How about this instead:
```python
@property
def number_of_timesteps(self):
    """Return the number of time steps in the Datarecord.
    """
    return len(self.time)
```
and removing `_number_of_times`? This property is so simple maybe we should leave it to users to do `len(dr.time)`. Although, the consistency of `number_of_timesteps` and `number_of_items` is good.
### Method parameters as 1-element lists

I find the 1-element lists confusing. I wonder if its necessary in all cases. For example:
- Variable dictionaries: the value is a two-element tuple, both elements are 1-element lists. Maybe this is an xarray thing.
- time is most often taken as a one-element list
- Although, in `set_data` the parameters `model__time` and `new_value` cannot not be in lists.

Do you think 1-elements lists could be eliminated in parameters, or are these needed?

### Parameter label `time` vs `model__time`.

`__init__` uses `time` and some other methods use `model__time`, perhaps a relict of RecordCollection. I like the succinctness of `time`, but really just consistency is needed. (Please forgive me(!) giving a fine detail when I should be giving higher level comments now).

**Comment by margauxmouchene** [comment]
Thank you, this helps a lot.

> Incorrect value of number_of_timesteps returned
Good catch, that was dumb on my part... I changed it to your suggested solution and did the same with `number_of_items`. I agree that it is a pretty simple method but I find it useful anyway, I say we should keep it.

> Method parameters as 1-element lists
Yes I can definitely work on simplifying the parameters formats and make them consistent between methods. 
For the 'time' inconsistency, that's on my part and I can improve that.
In general, I don't like how there are so many brackets and parentheses and braces in the input formats I defined. But as we are dealing with things that are sometimes 1-d and sometimes 2-d this is how xarray can make the difference and assign the right dimension(s) to each variable. So for the variable dictionary, this format is needed (that's actually how they do it in the [xarray examples](http://xarray.pydata.org/en/stable/data-structures.html#creating-a-dataset)). We could have simpler input formats and do the formatting within our instantiation method, but I am not sure what input format to have?

> Parameter label time vs model__time.
I agree we should keep `time` only, I just changed that.

**Comment by margauxmouchene** [comment]
Added a method: `ffil_grid_element_and_id`
Fills NaN values of the fields 'grid_element' and 'element_id' by propagating values forward in time.
This is needed for aggregating, if data has been added: the `add_data` method automatically fills with `nan` where no new value is provided; if aggregating on nodes, you might need all entries to be populated. Other variable fields can be filled with xarray's native `ffill` method but that was not working for `grid_element`, hence this new method.

**Comment by nathanlyons** [comment]
@margauxmouchene, you proposed something like these options for initializing time. Here is what I think may work. I can implement these in a branch based upon what you and others think.

## Init time parameter

`time` initiates these ways:
1. `None`, the default, sets the DataRecord instance to not record time
2. [], an empty list, the DataRecord records time, no initial time, and this avoids the need to create a dummy time
3. a one-element list, a single time
4. multiple times in a list

So `time` in init has two type options: None and a list/array. This could be in the init:
```python
if isinstance(time, (list, np.ndarray)):
    # create coordinates for the dimension 'time':
    self._times = np.array(time)
elif time is not None:
    raise TypeError('time must be a list or numpy array')
```

Or Option 2 could be taken as a float or int as well.

## Performance

Here is a simple comparison of runtime for Option 2 and 4.

In a trial of both options:
- DataRecord was instantiated with 1 data variable.
- Over 10,000 time steps, the variable value was changed using the `add_record` (Option 2) or the `set_data` (Option 4) method.
- The method was timed inside the for loop, and the run time stats of the trials are below.

Time in seconds. I ran this on my laptop.

Option 2:
sum 18.6773056984
mean 0.00186773056984
std 0.000267958375929

Option 4:
sum 4.03629732132
mean 0.000403629732132
std 3.13017436792e-05

This comparison is only with one data variable and no coordinates in addition to `time`. Higher dimensional records will be slower.

I did optimize `set_data` method a bit, and not the `add_record`, so maybe this comparison is a little unfair. Before I optimized, the sum of Option 4 was 9 seconds.

## A summary or something

The different time options seem useful. Option 4 when the number of timesteps is fixed, Options 2 and 3 when they are not and at the cost of a longer run time.

A caution of performance can be included in the documentation as well as pointing to simpler data structures.

DataRecord is handy when multidimensional structures need to be passed among components, model drivers, and other python objects.

**Comment by margauxmouchene** [comment]
@nathanlyons 
Thank you for the tests and improvements.

I agree with you that it seems useful to have all options. In particular, since your performance tests show that option 4 is faster than option 2, the input as a list is a good option to keep. I don't think I had it implemented in the DataRecord yet, did you do it on your branch? We can probably merge that if it works.
