### ISSUE TITLE
DrainageDensity documentation is not discoverable

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#771]
It needs to be listed in its own automodule .rst file and linked to by index.rst. Tagging @cmshobe (talk with me if you have questions on how to do this).

**Comment by kbarnhart** [comment]
It would also be great if the docstrings included a description of how the supported parameters (e.g. slope exponent) are used.

**Comment by kbarnhart** [comment]
@jdgemperline you and I just discussed this. Apparently I made an issue of it three weeks ago.

**Comment by cmshobe** [comment]
ok @kbarnhart @jdgemperline I'm going to address this now.
