### ISSUE TITLE
Travis OSX builds all fail

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#779]
This seems to be an issue with at least PR #674 and #776. 

I can vouch for testing both these PRs locally with OSX and Py 3.6 (though not in an identical build environment).

Looking at the TravisCI log, it appears that in progress work by @margauxmouchene and @saisiddu is also affected. Ditto the [recent build of 1.5.2](https://travis-ci.org/landlab/landlab/builds/421853471).

In all cases the builds that complete with errors take ~50 minutes (while a landlab build typically takes less than 10 minutes). 

Somehow @mcflugen's PR #778 does not seem to be affected. 

@mcflugen maybe you understand this.

If not, this PR gives us a single place to discuss.

**Comment by margauxmouchene** [comment]
I was just looking at this, I get the same errors as you. Did not get them just a few days ago.
I don't get any errors when testing locally either (OSX, Python 3.6 also).

**Comment by mcflugen** [comment]
@kbarnhart This is a [problem](https://github.com/pytest-dev/pytest/issues/3888) with the newest release of pytest (v3.7.3). You should be fine if you limit pytest to less than that (I only tried 3.7.1 but, from the sounds of it, 3.7.2 should work). It looks like they've fixed the problem but they don't have a release with the fix yet.

If, in `.travis.yml` and `meta.yaml`, you install `pytest==3.7.2` your tests should pass.

**Comment by kbarnhart** [comment]
OK. I made a PR that makes a fix.

**Comment by kbarnhart** [comment]
This was fixed by #777.
