### ISSUE TITLE
Documentation in ErosionDeposition

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#792]
The docs in ErosionDeposition aren't full enough. I've got Davy & Lague '09 sat in front of me, and I still can't follow what's going on here. In particular, I'm left wondering:
1. Does this follow the full generalised scheme of D&L09, or are there simplifications? The simplicity of the scheme makes it look like the latter, but it's not clear.
2. What's the solver doing here? omega is clearly stream power, i.e., the sediment mobilising term in D&L. But, the next couple of lines in `_calc_erosion_rates` are very opaque, with neither equation appearing in the paper. I'm guessing this is a scheme adapted from a combination of @kbarnhart's new, smarter solvers in `StreamPowerEroder` and the stuff in the `SmoothThresholdEroder`?? But I'm really groping in the dark here.
3. The descriptions of the parameters are quite foggy, e.g., `m_sp` and `n_sp`. Because you don't explain the scheme or give the equations, these aren't defined. The really killer one is that `v_s` term. Why is it important? How is this selected? How can I tune it if I want a simpler DL or TL model in isolation? I haven't had time to fully parse out all the math in the D&L paper, but I'm struggling to understand how this is the only important term, and why e.g. a flow velocity isn't also turning up in here. Regarding the documentation of `v_s` that there is, where do I choose a "grain size metric", and why and in what way is this only an "effective" settling velocity?? I fundamentally don't get it :-(

I'd settle for an answer to these questions only ;-) But what this really needs is a few paragraphs actually describing the model, how yours differs from D&L09, and any handy hints for deploying it. For example, how should I calibrate this to recover the traditional DL and TL dynamics as discussed by Davy & Lague at some length? How can I calibrate it in general? I have a use case for this I think, so it would be cool to be able to get it firing!

Tagging @cmshobe as I reckon you're the guy with the knowledge most easily to hand...? Also I feel guilty about tagging @kbarnhart so relentlessly.

**Comment by kbarnhart** [comment]
As  #836 dealt with this, closing.
