### ISSUE TITLE
Fields in ErosionDeposition

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#795]
The ErosionDeposition component claims it makes use of the `'drainage_area'` field. However, inspection of the code reveals this is in fact redundant, and in fact by default it looks at the `'surface_water__discharge'` field provided in the run method.

Per @kbarnhart 's comments on the call yesterday, this might be a candidate for moving the `discharge_field` argument out of the `run_one_step` method altogether, and just committing to using the `'surface_water__discharge'` field? Either way, `'drainage_area'` needs to come out of the params, IFAICT.

Flagging @cmshobe as a likely person to actually make the change...?

**Comment by gregtucker** [comment]
I favor removing parameters from run_one_step in general, and instead using parameters passed to __init__. For this component, though, I like the idea of defaulting to drainage area as surface_water__discharge if caller does not specify another field.

**Comment by cmshobe** [comment]
I've addressed this in #836
