### ISSUE TITLE
Testing instructions out-of-date

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#796]
On our Github homepage (i.e., in `readme.rst`) we still declare that freshly-installed Landlab can/should be tested with
```
> python -c 'import landlab; landlab.test()'
```
This does not work as of Landlab 1.5, and needs removing/modifying.

**Comment by kbarnhart** [comment]
Agreed, it needs to be changed. 

I think a major issue for a quick fix is that `pytest` is not required for running (so its not in the `requirements.txt`). I assume that means that it doesn't come with the `release` versions. 

For people on a developer version, we can just say that they need to install `pytest`. 

I'm not sure what to recommend for people on a distributed conda release.

**Comment by SiccarPoint** [comment]
Resolved by #797.
