### ISSUE TITLE
Installation of LandLab hangs on "solving environment" loading 

### ISSUE THREAD

**Issue by AlexLipp** [landlab/landlab#806]
I have attempted to install LandLab on a fresh Anaconda installation of Python. 
Running 

`where python`
`where ipython`

returns 

`C:\Users\myname\Anaconda3\python.exe`
`C:\Users\myname\Anaconda3\Scripts\ipython.exe` 

I've also updated the packages with `conda update --all`

However when I run `> conda install landlab -c landlab -c conda-forge` from within CMD it hangs on 

`Solving environment: \` 

where the dash is a loading animation. Unfortunately this does not progress any further. It does not proceed after waiting for around 20 minutes, but I have not waited longer. 

Is there something wrong with my set-up? What does "Solving Environment" mean?

**Comment by mcflugen** [comment]
@AlexLipp There might just be a problem with Anaconda.org. Are you able to `conda`-install any packages right now? For me, things are running *really* slowly. Definitely slower than usual. It might help if you don't specify the *landlab* channel (it's not needed). Try,
```
conda install landlab -c conda-forge
```

**Comment by mcflugen** [comment]
@AlexLipp your setup is probably fine. During the *Solving environment* step, `conda` is trying to figure out what packages and versions need to be installed along with *landlab*. To figure out what's needed and what's available can sometimes take some time (but definitely shouldn't take 20 minutes).

To help `conda` out, you may want to install landlab into a [separate environment](https://conda.io/docs/user-guide/tasks/manage-environments.html) so that there are fewer packages that need to be managed. You can do this with conda,
```
conda create -n landlab python=3.6
activate landlab
conda install landlab -c conda-forge
```
The actual commands may be different on Windows (I know the above would work on Mac/Linux) but the above link should cover how to do this on Windows. If it's different at all.

**Comment by AlexLipp** [comment]
Hi @mcflugen. It's come out slightly better now and has proceeded beyond the "Solving Environment" stage, with some stages including error bars and "completing transactions". 

However, I get a few error messages and when I try to run "import landlab" from within Python I receive a ModuleNotFound error message. 
I've tried running the same installation a few times to see if it's just a matter of the installation process missing a few dependent packages (like in R) but this hasn't seemed to work. Do you have any suggestions for how to proceed from here?

**Comment by mcflugen** [comment]
@AlexLipp What's the error message? Does it say what module is not found?

After you run `conda install landlab -c conda-forge`, run `conda list` to see what packages are installed. You should see `landlab` (v1.5.3) listed.

If you've successfully installed landlab and you get an error message saying that landlab can't be found, my guess is that you've installed landlab into one environment but are running python in another environment. Before you run Python, make sure you've activated the same environment that you installed landlab into.

**Comment by AlexLipp** [comment]
So the following error messages occur after "downloading and extracting packages"

[image](https://user-images.githubusercontent.com/10188895/46457152-3eb12f80-c7a9-11e8-82fd-8dd40507bc88.png)

The final error is `"CondaError: cannot link a source that does not exist". `

I have tried running the suggested "`clean conda`" command, and will now attempt to reinstall landlab. It was not on the list of installed packages when I ran `conda list`

**Comment by mcflugen** [comment]
@AlexLipp Have a read through of conda/conda#6057. It sounds like the same problem you're having.

From the sounds of it, you may have a broken version of `conda`. Try running `conda update conda` to get the newest version.

**Comment by AlexLipp** [comment]
@mcflugen 
I've now managed to successfully install LandLab by creating an environment. The commands for mac and linux were the same for windows. Thank you very much for the help, this issue can be closed :+1:
