### ISSUE TITLE
Watershed utility could be made faster by using flow__upstream_node_order

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#830]
This has come up because of time considerations @mcflugen has had with delineating watersheds in Puerto Rico (associated with @christinab's rapid).

@nathanlyons I know you are at GSA

**Comment by nathanlyons** [comment]
Cool! I will review in just a bit.

@mcflugen, this is how I create a colormap for watersheds. Non-watershed cells are colored white. Perhaps this can be a simple plotting function, although generalized to create random colormaps given a number of elements (eg watersheds). 

```python
# Get an array of colors with the length of the max mask id. Change `prism` to use
# other colormaps.
vals = np.linspace(0, 1, max(masks))
colors = plt.cm.prism(vals)

# Create a cmap of the shuffled colors.
np.random.shuffle(colors)
cmap = plt.cm.colors.ListedColormap(colors)

# Grid areas not assigned an id by the watershed util are assigned -1. Color
# these cells  white.
cmap.set_under('white')

imshow_grid(mg, masks, cmap=cmap, vmin=0)
```
