### ISSUE TITLE
Multiple accounts running AppVeyor builds

### ISSUE THREAD

**Issue by mcflugen** [landlab/landlab#845]
@SiccarPoint and I just noticed today that there are two sets of builds being run on AppVeyor: one under @mcflugen's account and one under @kbarnhart's account. This means that every time the CI is run on AppVeyor it is run twice and that even if we cancel a build under one account, it's not canceled under the other.

You can see the builds here:
* mcflugen's: https://ci.appveyor.com/project/mcflugen/landlab/history

and here:
* kbarnhart's: https://ci.appveyor.com/project/kbarnhart/landlab/history

This needs fixing. AppVeyor is already overworked, we don't need to burden it with unnecessary builds.

**Comment by kbarnhart** [comment]
I'm not sure how I did this, but I agree that it should be solved. 

I think the way to solve this is for me to delete landlab as one of my Projects on AppVeyor.

@mcflugen do you think this is the right way to go about it?

Do you know if it will result in my not being able to cancel AppVeyor jobs? I sometimes need to do that.

I don't think this issue also exists on Travis, but if someone else thinks it is, let me know.

**Comment by mcflugen** [comment]
@kbarnhart If you remove landlab from your AppVeyor builds, that should solve the current problem.

I'm not certain, but I don't think you can cancel builds that are under my account. I know we tried to set this up at one time but I'm not sure we ever got it working.

Note that the way it is now (as far as I can tell), you can cancel builds under your account but they will still run under my account. So instead of running twice, they'll only run once.

**Comment by kbarnhart** [comment]
Just deleted it... let me know if you think the problem still persists. 
Sorry about that.

**Comment by mcflugen** [comment]
I can no longer see your builds so I think that's fixed. Are you able to see my builds?

https://ci.appveyor.com/project/mcflugen/landlab/history

and, if so, are you able to cancel them?

**Comment by SiccarPoint** [comment]
I appear to have access to your AppVeyor Eric, so hopefully yes!

**Comment by kbarnhart** [comment]
@mcflugen I can see the builds, but I don't have any of the cancel/restart privileges that I previously had (on my own builds). 

reading a bit here: https://www.appveyor.com/docs/team-setup/#permissions
indicates that we should probably make two landlab teams:
admin: @mcflugen @SiccarPoint @kbarnhart (and anyone else, or everyone)
core: everyone else currently in core (but not the people in admin)

then the admin team gets appveyor privileges. It looks like if I'm in both groups, appveyor gets confused.

**Comment by mcflugen** [comment]
@kbarnhart Yeah, that's kind of what I figured.

I think the best solution would be to set up a landlab organization on  AppVeyor and add all of us to it. I was going to do that but I wanted to use a landlab email address but I'm not sure what it is. Do you know if we have one?

**Comment by kbarnhart** [comment]
I have no idea... If we have one, it predates me.

**Comment by mcflugen** [comment]
I think this is all fixed now. @kbarnhart, adding you to the "Users & Collaborators" in my AppVeyor account allowed you to be able to cancel and restart jobs. Let me know if that's not the case and we can reopen this issue.
