### ISSUE TITLE
trouble implementing DataRecord in time

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#890]
Hi @margauxmouchene and/or @kbarnhart : 

I'm trying to use the time dimension of DataRecord and am at an impasse. I keep hitting an error when I try to instantiate. The simplest example is below: 

```
import numpy as np

from landlab import RasterModelGrid
from landlab.data_record import DataRecord
from landlab.plot import graph

grid = RasterModelGrid((3, 3))
time = [0.]

element_id = np.array([0, 0, 1, 1, 2, 2], dtype=int
)

volume = np.ones((np.size(element_id),1)) 

items = {"grid_element": "link", 
         "element_id": element_id
}

variables = {
    "volume": (["item_id","time"], volume)
}

parcels = DataRecord(grid, 
                     time = time,
                     items=items, 
                     data_vars=variables
)

```

When I remove time, it works. 

I suspect comes from a mismatched size issue, where volume doesn't match the size [item_id,time]; however, I haven't been able to 'reshape' my way around this issue. Any insights?

Thank you!!

**Comment by kbarnhart** [comment]
@pfeiffea I've assigned @nathanlyons and @margauxmouchene since they know DataRecord the best.
