### ISSUE TITLE
Request/advice: DataRecord calc_aggregage_value across a particular dimension

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#895]
Hi @nathanlyons and/or @margauxmouchene : 

I'm using DataRecord to calculate aggregate values (e.g. sum up all the volumes of items on a link), but I am only interested in the volumes on that link at a particular timestep. From what I can tell, I need to use a 'filterarray' to do this.

Two questions: 

1. Is there some very concise syntax to get a filter of only the current time? My attempts are clunky..

and/or 

2. Would it be possible to update DataRecord so we can pass something like 'dimension = time' (or 'dimension = item_id') as an argument in calc_aggregate_value? 

FYI @jonczuba

**Comment by nathanlyons** [comment]
Hi @pfeiffea,

A time filter can be created with `dr['time'] == 2`, where the time you want in this example is 2. A similar syntax can be used with the `and` operator (or np.all) to filter by the item as well to use with calc_aggregate_value:

```python
f = dr['time'] == 2 and dr['item_id'] == 0
s = dr.calc_aggregate_value(func=np.sum, data_variable='volumes', at='link', filter_array=f)
```

Although, if I am understanding correctly, there is no summing because you want the value of 1 data variable at 1 time and at 1 link, correct? If yes, maybe all you need is the `get_data` method:

```python
dr.get_data(time=[2], item_id=[0], data_variable='volumes')
```

**Comment by pfeiffea** [comment]
Thanks @nathanlyons ! That syntax is way tidier than what I had been using... makes the filter array much less cumbersome. 

And sadly, I do need to use calc_aggregate_value. I'm summing things (e.g. volumes) of all of the items that reside on a single link at a single time.

**Comment by pfeiffea** [comment]
A belated return to this issue, in case anyone else runs into this: 

the syntax suggested above ( `f = dr['time'] == 2 and dr['item_id'] == 0` ) yields a value error for me: 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

My workaround is the following: 
`f = dr_3['thing_size']<= 4
f[:,0:-1]= False # workaround to only look at current timestep`
