### ISSUE TITLE
weathering component default behavior is not intuitive

### ISSUE THREAD

**Issue by cmshobe** [landlab/landlab#899]
The exponential weatherer component fails to warn if you pass in an optional argument that the component doesn't take. This is a problem because the optional arguments names were fairly recently (~last 6 months) changed, so there's no warning for those using slightly old code that their variable values aren't being used. It uses a default weathering rate of 1 m/yr, which is a pretty wild value given that there's no warning given to the user that this value will kick in.

This is part of a broader pattern of problems caused by the **kwargs system. So I'm hoping that rather than specifically changing the exponential weatherer, I can advocate for a more structural reworking of the way unwanted parameters are passed to components and then quietly disregarded.

**Comment by kbarnhart** [comment]
@cmshobe thanks for pointing out that the **kwargs presented these problems for you. While this is unlikely to be fixed in the short (1-3 month) term, know that addressing this is part of the Landlab 2.0 plan.

**Comment by kbarnhart** [comment]
We have fixed this on `v2_dev`. Closing
