### ISSUE TITLE
Make a new pypi release

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#921]
@mcflugen now that you've updated the CI in #915 can I ask you to make a PyPI release. 

I'm updating the terrainbento CI to keep it in line with LL (on [this PR](https://github.com/TerrainBento/terrainbento/pull/138)) and my builds fail (as expected) because there are no PyPI releases >1.7. For example this [build on Travis](https://travis-ci.org/TerrainBento/terrainbento/jobs/526948490).

This is not a huge priority.

**Comment by mcflugen** [comment]
Sure. What should the new version be? I'm not sure what changes have been made since the last release but probably v1.9?

**Comment by kbarnhart** [comment]
As long as its >1.7 I’m happy! It doesn’t need to be new new.

Thanks!!

**Comment by mcflugen** [comment]
It will have to be based on what's on master right now, so the version number will have to be greater than our latest release (1.8.0). I also want to make sure that what on PyPI and *conda-forge* all match up so, if I create a new PyPI release, I'll also create a new *conda-forge* release.

I think we're probably due for a new release anyway.

**Comment by kbarnhart** [comment]
Sounds good!

**Comment by kbarnhart** [comment]
@mcflugen I just got back to finalizing the update of terrainbento's CI and I get the following error 

(for example [this build](https://travis-ci.org/TerrainBento/terrainbento/jobs/526952151))

```
Collecting landlab>=1.7 (from terrainbento==1.0.1+11.g1ce8e7a)
  ERROR: Could not find a version that satisfies the requirement landlab>=1.7 (from terrainbento==1.0.1+11.g1ce8e7a) (from versions: 0.1.7.macosx-10.5-x86_64, 0.1.6, 0.1.7, 0.1.8, 0.1.9,
 0.1.12, 0.1.14, 0.1.15, 0.1.18, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28, 0.1.29, 0.1.33,
 0.1.35, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.1.41, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.5.0, 1.0.0a0, 1.0.0b0, 1.0.0b1,
 1.0.0b3, 1.0.0b4, 1.0.0b6, 1.0.0b8, 1.0.0b10, 1.0.0b11, 1.0.0b12, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.2.0, 1.3.0,
 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.9.0b0, 1.9.0b1, 1.9.0b3, 1.9.0b4)

ERROR: No matching distribution found for landlab>=1.7 (from terrainbento==1.0.1+11.g1ce8e7a)

The command "pip install -e ." failed and exited with 1 during .
```

This doesn't make much sense to me as there is a 1.8.0 on pypi (https://pypi.org/project/landlab/)
But the setup.py call doesn't see it. 
Any ideas?

**Comment by kbarnhart** [comment]
@mcflugen I've looked into this a bit more, and I think that what needs to happen is that I need a real 1.9 release (rather than the 1.9.b series). Could you please make that on PyPI and on condo-forge?

**Comment by mcflugen** [comment]
@kbarnhart The 1.8.0 version on *pypi* is just for Windows, which is why it can't satisfy the dependency. There's a pre-release version on *pypi* (v1.9.0b4) that you could install using (I believe) the `--pre` option with *pip*. It's only a source distribution though.

In any case, I've created a new *v1.9.0* release that will appear on *conda-forge* as well as *pypi*. From the looks of things, the *pypi* version will still only be a source distribution (except on Windows).

**Comment by kbarnhart** [comment]
@mcflugen I'm not sure what you mean by "only be a source distribution". Is this likely why I get the following error on my current PR attempting to update the terrainbento CI? [example build](https://travis-ci.org/TerrainBento/terrainbento/jobs/552883335)

```
 landlab/graph/object/ext/at_patch.pyx:7:0: 'landlab/graph/sort/ext/argsort/unique_int.pxd' not found
    building 'landlab.graph.object.ext.at_patch' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/travis/anaconda/envs/test_env/include -arch x86_64 -I/Users/travis/anaconda/envs/test_env/include -arch x86_64 -I/Users/travis/anaconda/envs/test_env/lib/python3.7/site-packages/numpy/core/include -I/Users/travis/anaconda/envs/test_env/include/python3.7m -c landlab/graph/object/ext/at_patch.c -o build/temp.macosx-10.7-x86_64-3.7/landlab/graph/object/ext/at_patch.o
    landlab/graph/object/ext/at_patch.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
    #error Do not use this file, it is the result of a failed Cython compilation.
     ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/travis/anaconda/envs/test_env/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-1q9bks3n/landlab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-record-le40_3g7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-install-1q9bks3n/landlab/
The command "pip install -e ." failed and exited with 1 during .
```

**Comment by mcflugen** [comment]
@kbarnhart what I mean is that, for non-Windows builds, *pypi* only provides the landlab source code, not a pre-built binary. However, I'm in the process of fixing this and should have binaries up on *pypi* for all of our supported platforms in the not-too-distant future. In fact, I now have *v1.9.0b5* up for *macos*.
```bash
$ pip install --pre --prefer-binary landlab
```
The error you're seeing is most certainly the result of *pip* getting a source distribution, trying to build it, and then failing.

**Comment by kbarnhart** [comment]
@mcflugen am I correct that now that #965 has been approved that a new release (on pypi and on conda-forge) is imminent?

1.9?

This is also relevant for @jmdelvecchio who likely wants the updated depth dependent diffuser as a conda-forge release.

**Comment by mcflugen** [comment]
@kbarnhart Yes, *v1.9.0* is (I hope) imminent. It's building right now to be deployed on both *PyPI* and *conda-forge*.  With any luck they should be completed later this afternoon.

**Comment by jmdelvecchio** [comment]
Thank you for keeping me in the loop you two! Slowly but surely learning to h4ck

**Comment by mcflugen** [comment]
@jmdelvecchio @kbarnhart It looks like landlab *v1.9.0* is now available on *conda-forge* and *PyPI*. If you already have landlab installed via *conda*, to update to the newest version you should be able to do,
```bash
$ conda update landlab -c conda-forge
```
Double-check you have the latest version,
```bash
$ python -c 'import landlab; print(landlab.__version__)'
1.9.0
```

**Comment by kbarnhart** [comment]
@mcflugen this is now working for me. I'm going to close this Issue. 

@jmdelvecchio if you have issues updating landlab, please let us know via an issue.

**Comment by jmdelvecchio** [comment]
Thanks everyone, this seemed to work! Time to get coding!!
