### ISSUE TITLE
Space, ErosionDeposition, and _GeneralizedErosionDeposition don't have defaults

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#938]
These three components all don't use default values for many parameters.  For example:

```python
    def __init__(
        self,
        grid,
        K_sed=None,
        K_br=None,
        F_f=None,
        phi=None,
        H_star=None,
        v_s=None,
        m_sp=None,
        n_sp=None,
        sp_crit_sed=None,
        sp_crit_br=None,
        discharge_field="surface_water__discharge",
        solver="basic",
        dt_min=DEFAULT_MINIMUM_TIME_STEP,
        **kwds
```

I think that most of these keyword arguments (e.g. K_sed) should have default values instead of None. 

@cmshobe @gregtucker what do you think?

**Comment by cmshobe** [comment]
Personally I am not wild about defaults because 1) they allow users to not bother thinking about effective parameterizations and 2) they can sometimes be quite inappropriate values (remember the blocklab soil production rate default debacle?).

If I’m in the minority that’s ok, but I’d prefer to stay without defaults.

**Comment by kbarnhart** [comment]
I think the any of the following is needed:
1) Defaults given 
OR
2) No defaults that raise appropriate errors
OR
3) Change these kwargs to args.

The block lab soil issue was not actually an issue with default values, but an issue with keyword argument names (it was an issue nonetheless), and I'm excited to get rid of the root issue with the removal of **kwargs in 2.0.

**Comment by cmshobe** [comment]
I'm totally happy with raising an error if these things aren't specified (I actually somehow thought we already had that in). Defaults are also ok if that's getting to be a Landlab-wide standard that needs to be complied with.

**Comment by gregtucker** [comment]
I agree with getting rid of **kwargs. As to whether or not to use defaults, I think we need a team conversation and (ideally) consensus. NOT providing defaults has the advantage of forcing a user to make a decision about each and every parameter (except possibly those that have an obvious default, e.g., g=9.8, or perhaps those where there's a reasonably narrow range in nature, e.g., soil porosity). On the other hand, providing defaults gives users a sense for what an expert would consider a "reasonable" value, and allows people (such as students running some kind of teaching application) to get up and going quickly.

**Comment by cmshobe** [comment]
Yeah that’s a fair point; I see both sides of it. Why don’t we update this issue thread once the Landlab team has had a chance to decide which way is best?

My overarching preference is just that Space and E/D be in compliance with the rest of Landlab so that fewer updates are needed in the future.

**Comment by SiccarPoint** [comment]
I assume we're going to get to this tomorrow, but IIRC **kwargs was in part created to enable the creation of a single dict of all param values, and for this dict to get passed around the components. If we have an alternative workflow for this now (what is it??), I'd be happy with removal I think. This might be a code-breaking-in-the-wild change though, so it should be LL 2.0.

I think we should retain defaults, but let's discuss. IMO would devalue LL a little as a teaching tool, but maybe enhance it as a research tool.

**Comment by kbarnhart** [comment]
@SiccarPoint you are 100% correct about the purpose of **kwargs (and also correct about not removing them until LL2.0). 

Agreed that we should discuss defaults tomorrow on the call.

**Comment by cmshobe** [comment]
Update: I have given defaults in PR #951
