### ISSUE TITLE
imagemagick and ffmpeg links not available anymore in tutorial

### ISSUE THREAD

**Issue by cctrunz** [landlab/landlab#941]
Hi! Found that in tutorial 'animate-landlab-output', links to install imagemagick and ffmpeg are not valid anymore.

**Comment by kbarnhart** [comment]
@cctrunz thanks for making this issue! I've assigned @nathanlyons who is the primary author of that notebook.

**Comment by nathanlyons** [comment]
Thanks for bringing this to my attention, @cctrunz. The links errorenously have an `)` at their ends. We are now working on an updated version of this tutorial. Here are the links in the mean time:

* FFMpeg: [https://www.ffmpeg.org/download.html](https://www.ffmpeg.org/download.html)
* ImageMagick: [https://www.imagemagick.org/script/download.php](https://www.imagemagick.org/script/download.php)

Also, you may need to include this line when running this tutorial:
```python
%matplotlib qt
```
 I suggest adding a new cell at the top of this tutorial, insert this text, and then run it. Let me know if this is not clear.
