### ISSUE TITLE
Three versions of the PotentialityFlowRouter

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#957]
@SiccarPoint as part of LL2.0 cleanup over on #956 I'm working on component submodule cleanup. I've noticed that there are three different versions of the `PotentialityFlowRouter`

They live in three files:
* route_flow_by_boundary.py
* route_flow_by_boundary_1st.py
* route_flow_by_boundary_2nd.py

But only the component in 
route_flow_by_boundary.py
is used. 

Can I delete the following two files?
* route_flow_by_boundary_1st.py
* route_flow_by_boundary_2nd.py

**Comment by kbarnhart** [comment]
@SiccarPoint ping!

**Comment by SiccarPoint** [comment]
Yup

**Comment by kbarnhart** [comment]
thank you!
