### ISSUE TITLE
Remove the ModelParameterDictionary 

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#960]
As part of LL2.0 cleanup, @mcflugen and I were discussing removing the ModelParameterDictionary. 

The reason being: as all components are wrapped by BMI and are PyMT compatible, the functionality of this type of import is superseded by the BMI functions. 

In the code base it is used in the examples, some tests, and only in about 3 (out of 48) components. 

If you would like to see this stay, please describe why in the comments below. 

@SiccarPoint @gregtucker @RondaStrauch @saisiddu @nicgaspar @nathanlyons @margauxmouchene @erkanistan @jadams15

**Comment by kbarnhart** [comment]
A note from our last teleconference. No one has major issues with removing this.

**Comment by gregtucker** [comment]
This was one of the first pieces I ever wrote in what ultimately became Landlab. I agree that the yaml tools make it obsolete.

**Comment by kbarnhart** [comment]
Removed as part of #956
