### ISSUE TITLE
Component expectations about fields

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#961]
As part of the LL2.0 Component cleanup, @mcflugen and I have discussed standardizing the way that components interact with input and output variables (stored as grid fields). 

Creating a standard will mean that all components can have cleaner inits (with less testing for whether a field exists). 

The following is what we propose as the standard expectations. 

## Input fields:
The component base class verifies that all input variables exist on the grid and raises an error if one is missing. 

## Output fields:
The component base class checks if a field exists. If it does, nothing happens. If a field does not exist the component base class with initialize it with an empty array of the dtype indicated by the component metadata. 

It is then the developers prerogative to place default values within a field if that is appropriate to do within the __init__. 

Thoughts @SiccarPoint @gregtucker @RondaStrauch @saisiddu @nicgaspar @nathanlyons @margauxmouchene @erkanistan @jadams15

**Comment by kbarnhart** [comment]
A note from our last call. It was generally thought that this was a reasonable approach. 

I note that we didn't discuss optional fields (as we wanted @SiccarPoint and @gregtucker to be on the call).

I've added the optional field conversation to the next telecom agenda.

**Comment by SiccarPoint** [comment]
This seems eminently sensible. Some thought needs to go into _optional_ input fields. Say I am doing flow accumulation and I can either specify rainfall rates or not. It would be a waste of both memory and calculation time to force the creation of the input field, fill it with 1s, then use them every timestep in the latter case. I've had the case of optional array inputs turn up quite a few times now, so would be good to get some official policy going in v2.

I appreciate this isn't quite the same topic!

**Comment by SiccarPoint** [comment]
I see this is superceded by #962...
