### ISSUE TITLE
Components and optional fields

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#962]
Ping @SiccarPoint you are the component developer this most directly affects. 

@mcflugen and I were discussing the optional fields. Presently these are included in the component base class. They are not commonly used:

The `PrecipitationDistribution` component has a field labeled optional that I think is actually a real output field for rainfall__flux. 

The `SedimentFluxDependentEroder` has a few optional fields that relate to channel properties. 

Originally, based on @mcflugen and my conversation I thought:
As there is no standard place for optional fields in BMI, @mcflugen and I think that removing them from the base class makes sense. 

I just discussed this with @gregtucker and he brought up a few important points. 
1) The examples I've just given are all optional OUTPUT fields, but we also have a number of OPTIONAL input fields. For example, you can indicate a field other than "topographic__elevation" for the flow accumulator to accumulate flow based on. Or you can pass a field of erodibility coefficients to a stream power component. We need to come up with a way (in the discussion here and in #961) that standardizes some of these optional INPUT fields. 

My initial inclination with respect to optional outputs is that the var-doc information stores information indicating that the field is both an output and optional. 

With respect to optional inputs, I'm not entirely sure of what is best. An important consideration to while we mull over a solution is that some of these "optional input fields" are either arrays or field (the FlowAccumulator option). In other cases they are fields, arrays, or scalars (the stream power component option). 

Thoughts?

@SiccarPoint @gregtucker @RondaStrauch @saisiddu @nicgaspar @nathanlyons @margauxmouchene @erkanistan @jadams15

**Comment by kbarnhart** [comment]
I'm going to articulate a proposed approach to this issue. This approach also addresses Issue #968. The approach is intended to be user and developer friendly and accomplish the following goals:

1) Permit some "inputs" to a landlab component to be either a scalar, an array, or already be stored on the model grid with a field name (indicated by a string). I write "inputs" in quotations, to say that these are inputs to the component, BUT that they are not documented in the component header information (e.g., in `_input_var_names`).

2) Permit a user to modify field or array inputs easily by using [:] or .fill()

3) Permit a user to modify a scalar input when a component developer indicates that they want this to be possible. 

## The proposed approach:

1) Inputs of this type (e.g., optional inputs) are not indicated by the header information. This is because they are, just that, optional, so there is nothing to check for. Further, when an input can be a scalar or an array, this means it might live on the grid or or at a grid element. Forcing it to exist would not be memory efficient, or would require lots of checking about living at grid or at node, etc. 

2) Inputs of this type are either at grid element, an array, or a scalar (this is what we currently do). 

3) I think we kill the current ability to broadcast a scalar to an array. 

4) When a component author wants to expose the ability to change the value of this input through a component attribute, this attribute must be documented. 

    - This is identified as the only way to change a scalar input. 
    - If a component author wants to expose these attributes, then it creates a slightly increased amount of work (e.g., they need to document the attribute using `@property`, if they want to permit this attribute to change, they need to create a setter. This may seem burdensome, but remember that some type checking typically occurs on these attributes in the component `__init__`. If we expose, say, the water erodibility coefficient in stream power, we want to make sure that user only sets it to something possible to cast into float (e.g., not `"cat"`). 

5) The current functionality of a user being able to modify an array or a field are unchanged. 

What do you think?

**Comment by kbarnhart** [comment]
we (@kbarnhart @gregtucker @saisiddu @erkanistan @amanaster2 @nathanlyons) discussed this on the call today. We agreed that the proposed approach I outlined was reasonable and a good approach for LL2.0
@mcflugen @nicgaspar @SiccarPoint we want to make sure you think this is OK before moving forward. Can you please comment/approve/indicate either way?

**Comment by SiccarPoint** [comment]
As I read it, seems great. I'm struggling to visualise exactly what the optional input style would look like in practice, so a super simple sketch example might be good? I think I get what you mean about outputs and modification.
