### ISSUE TITLE
Landlab 2.0 and the examples folder

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#963]
One thing I noticed when I was working on #878 is that there are a few uses of the old channel profile plotter in the examples folder, but that they aren't tested (even to just see if they can run). 

These examples pre-date me, so I don't know their history. Can someone fill me in. 

My initial thoughts on LL2.0 are that it should only include examples that work. And that we should test that the examples work. 

Thoughts @SiccarPoint @gregtucker @RondaStrauch @saisiddu @nicgaspar @nathanlyons @margauxmouchene @erkanistan @jadams15

**Comment by saisiddu** [comment]
As far as I remember, we were planning to get rid of the examples folder. I think we moved those files to the tutorials repository. Please correct me if I am wrong.

**Comment by gregtucker** [comment]
That's my recollection too.
