### ISSUE TITLE
How should 2.0 Components handle public attributes 

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#968]
A 2.0 question for discussion. 

We have many components that have undocumented public attributes. 

For example the DepthDependentDiffuser takes an input called linear_diffusivity that is stored at the public attribute self.K. However, no documentation describes what this attribute is or whether one can dynamically change it. This is confusing!

A few components do document some of their attributes (e.g., Lithology.thickness). 

There are mechanisms by which we can have attribute sections be built by the docs (see, for example, the np.ndarray docs [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html)). 

I think we should discuss and come to a joint decision about how landlab components treat public attributes. 

I'll start the discussion with a provocative recommendation (that does not 100% reflect my current thoughts, but Is good for discussion). 

I recommend that we enforce that all public attributes of landlab components are documented with an `@property` definition and docstring. I (currently) argue that this is both developer friendly and user friendly. 

- A developer has a choice regarding whether an attribute is public or private. If they don't want to expose a public attribute, they can use a leading underscore, spend zero time, and be 100% compliant. If they want to expose an attribute, it is their job to document it. 
- If all public attributes are documented, we clearly communicate to the users what these attributes actually are.  

I note explicitly that I have not argued either for or against the creation of getters and setters for all attributes. I will admit that I've never really understood the arguments for or against having them in python. @mcflugen can probably chime in here. My comment is (thus far) only about the existence of documentation for all public attributes. 

Discuss!

@SiccarPoint @gregtucker @saisiddu @nicgaspar @nathanlyons @margauxmouchene @erkanistan @jadams15

**Comment by gregtucker** [comment]
In weighing this issue, it's useful to bear in mind the value of simplicity in component development. We want to encourage our community to develop their own components, and one way to do this is to avoid being too complex. On the other hand, we want components to be functional and well documented.

One alternative to the above proposal (which @kbarnhart and I also discussed in person) is to encourage documentation of attributes as follows:

Public:
Gets documented in header docstring, under Attributes (like Numpy)
example: 

`class MyCoolComponent(Component):`
`    """Calculates a numerical solution to the Notorious Frog problem.`
`    ...`
`    Attributes:`
`    ----------`
`    frogness : float`
`        degree of frogness, in slugs per fortnight`

...etc.

So, the attribute MyCoolComponent.frogness should be listed, but MyCoolComponent._toadification, being private, would not.

This approach has the advantage of not requiring a component author to know about @property or getters and setters. It also appears in auto-generated docs. It might be harder to auto-detect whether a component complies with the documentation requirement, however (I'm not sure about this).

**Comment by kbarnhart** [comment]
A note regarding listing attributes: The [Napoleon sphinx-extension documentation](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy) indicates that 

> Module level variables may be documented in either the ``Attributes``
    section of the module docstring, or in an inline docstring immediately
    following the variable.

We presently use this in building our docs. 

In looking at examples from NumPy and Pandas, it seems that this second option (inline docstring) is typically used. I think it is cleaner. 

This means that component authors would need to used `@property` AND it means that we can more easily assess if documentation is fully compliant. 

At the end of the day, I think that the more difficult thing to do is to write the text that would live either under an Attributes section (as described by @gregtucker above) rather than the act of putting it in the format describe above vs in an independent docstring unique to the property.

**Comment by nathanlyons** [comment]
I agree that in some way, public class attributes should be clearer. I have included descriptions of public attributes, similar to `MyCoolComponent`, in some things I'm developing, and the @property would work, too.

numpy and others also (sometimes) include public method descriptions as well in the docstring. If Landlab takes the docstring approach for documenting attributes, then it seems consistent to also include method descriptions in the docstring. Although, I find it a little redundant to have methods described in the class and method docstring. If the @property approach, then attributes and methods become consistent as both are defined with `def`. 

One benefit of a setter is that they can forbid an attribute to be set to an inappropriate type and/or value. Although developers can take advantage of this even if Landlab takes the docstring approach.

**Comment by kbarnhart** [comment]
we (@kbarnhart @gregtucker @saisiddu @erkanistan @amanaster2 @nathanlyons) discussed this on the call today. We all agreed that the approach of requiring public attributes to be documented in individual docstrings was reasonable and a good path forward for LL2.0. 

@saisiddu had a great idea to help component developers, namely make an example showing how to make the same component with and without properties. 

@mcflugen @nicgaspar @SiccarPoint we want to make sure you think this is OK before moving forward. Can you please comment/approve/indicate either way?

**Comment by SiccarPoint** [comment]
I have made it to this point in my email heap!

I like this. If a user should have access, do it properly and slap an `@property` on it. If not, just add the pseudo-private leading underscore to the variable. We've been bad about this in the past, but it's easy enough to check in review. Would also be able to guide new users though it, hopefully? Plus I suspect there actually aren't _that_ many cases where a user would want to access "by hand" a single model parameter...? (prepares to be proved instantly wrong)
