### ISSUE TITLE
Formats of floats (trailing periods)

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#983]
I notice someone has been through all of the Landlab code and replaced every single float with a trailing period with a decimal place, i.e., `1.` -> `1.0`.

This doesn't appear to be PEP8 styling, and I'm struggling to find an alternative style guide explicitly recommending it. In fact, the opposite, where there seems to be a recommendation to use decimal places to indicate known precision, so an integer 2 at machine precision for use in e.g. a square _should_ be rendered `2.`, not `2.0`.

On manual inspection, the automated changes have in fact actively violated PEP8 in a number of places, by forcing line lengths > 79!

Essentially, I don't like this, and don't think it's something we should be actively enforcing in the future. (Current changes are clearly water under the bridge at this point...)

Thoughts?

**Comment by kbarnhart** [comment]
I think I can half explain and @mcflugen can explain the rest. As part of #834 (de linting) we added a  `make pretty` in the makefile that runs [`isort`](https://github.com/timothycrosley/isort) and [`black`](https://black.readthedocs.io/en/stable/) on the code base. We discussed this on the call at some point, don't remember who was on. Whether @mcflugen and I are the only people who use it or not is not known to me. 

I can describe why I think `make pretty` is a good idea (tl:dr consistency in code style is helpful, especially if a human doesn't have to enforce the consistency). I, however, cannot describe why `2.0` is or is not better (stylistically) than `2.` I'm going to let someone else take that one (@mcflugen ?). 

Regarding the line-length, the linter is presently set up to yell at you if line length exceeds 88 (see `setup.cfg`. Why 88 over the 79... another question for @mcflugen.

**Comment by SiccarPoint** [comment]
Thank you!

**Comment by kbarnhart** [comment]
@SiccarPoint OK to close this?

**Comment by SiccarPoint** [comment]
Yup - but I'd like to make a pitch that we at least reduce that line length to 79, per PEP8. Let's discuss at some point in the future.
